### ISSUE TITLE
Android queryAggregated() function date problem

### ISSUE THREAD

**Issue by iAdil** [dariosalvi78/cordova-plugin-health#10]
I have a trouble with date param in queryAggregated() function.
So that code works perfectly in iOS:

```
navigator.health.queryAggregated({
    startDate: new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000), // three days ago
    endDate: new Date(), // now
    dataType: 'steps'
}, function(msg){
    console.log(msg)
}, function(e){
    console.log(e)
})
```

returns in iOS:

```
endDate: Fri Aug 05 2016 13:25:40 GMT+0500 (AZST)
startDate: Tue Aug 02 2016 13:25:40 GMT+0500 (AZST)

```

return in Android:

```
endDate: Thu Aug 04 2016 19:25:11 GMT+0500 (AZST)
startDate: Thu Aug 04 2016 19:24:11 GMT+0500 (AZST)
```

So you see there are not correct result in Android.
Please help with advice, thanks.

P.S.

That code even don't works on Android, but in iOS works good:

```
var year = new Date().getFullYear();
var month = new Date().getMonth();
var date = new Date().getDate();

var morning = new Date(year, month, date, 0, 0, 0);
var night = new Date(year, month, date, 23, 59, 59);

navigator.health.queryAggregated({
    startDate: morning, 
    endDate:night, 
    dataType: 'steps'
}, function(msg){
    console.log(msg)
}, function(e){
    console.log(e)
})
```

iOS return:

```
endDate: Fri Aug 05 2016 23:59:59 GMT+0500 (AZST)
startDate: Fri Aug 05 2016 00:00:00 GMT+0500 (AZST)
unit: "count"
value: 840
```

Android return:

```
endDate: Invalid Date
startDate: Invalid Date
```

for the same code

**Comment by dariosalvi78** [comment]
I'll check these.

**Comment by iAdil** [comment]
I found the reason. If there no steps on filter date, then the function just return invalid date, not zero resukt.

Also the same for date, resul return first and last dates.

**Comment by dariosalvi78** [comment]
The start and end date returned by the plugin are the first and last timestamps of the available datapoints. If there are no datapoints, then the dates don't exist. If there is one datapoint then you'll probably have the same start and end timestamps.
It's a design decision.
Alternatively, I could have set start and end to exactly the start and end of the query, but then you already have them anyways, so I think that the way it is done now is more interesting.

I don't have a strong opinion in this respect, I'll keep the issue open for a bit to see if there are more comments on it.

**Comment by array-addu** [comment]
@dariosalvi78 
I am using google fit app this time but the result after the "health.query" i got  the start date and end date with a difference of one minute and "STEP" data is 1.
I need to fix this thing as soon as possible.

**Comment by dariosalviwork** [comment]
that's the start and end of the data sample (your single step). If you want to use the same start and end dates as in the query, well, you have them in your query.

**Comment by array-addu** [comment]
HY@dariosalviwork 
Currently i am using this code snippet.
navigator.health.query({
                        startDate: new Date(new Date().getTime() - 7 * 24 * 60 * 60 * 1000), // Seven days ago
                        endDate: new Date(), // now
                       /*  startDate:moment.utc().startOf('day'), // set to 12:00 am today
                         endDate:moment.utc().endOf('day'),// set to 23:59 pm today*/
                        dataType: 'steps'
                       }, 
                 successCallbackrequestquery, errorCallbackrequestquery)
But i get start date and end date of yesterday.

**Comment by dariosalviwork** [comment]
query() returns all data points that are stored within the time window you specify in your query. The start and end dates you are receiving are those of when your data point was stored.
