### ISSUE TITLE
update README.md with upload signing certificate and SHA-1 fingerprint

### ISSUE THREAD

**Issue by marcinggrabowski** [dariosalvi78/cordova-plugin-health#100]
Hi, 
I just spent couple of hours trying to figure out why Google API OAuth has something wrong with configuration (was keep receiving "User cancelled the dialog") but only for app downloaded from the Play Store. Even the same apk which was uploaded to store if installed manually worked.

When i lost all of my hope I accidentally notice in Google Play Console message "Google Play App Signing is enabled for this app".

I go to the Release management > App signing and found there info about different than upload signing certificate and SHA-1 fingerprint. I think it needs to be mentioned, especially for non-native developers for whom the Google Play Developers Console is not an everyday stuff.

**Comment by dariosalviwork** [comment]
czesc,

the docs specify quite extensively that you need to configure your environment correctly. I'll try to improve them though.
