### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'data[i].energy.slice')

### ISSUE THREAD

**Issue by GeorgeHarbers** [dariosalvi78/cordova-plugin-health#101]
I think I have found a bug in the query when using dataType activity on iOS. 

On line 214 of health.js the following code is present: 

> res.calories = parseInt(data[i].energy.slice(0, -2)); // remove the ending J

This results in the following error: 

> TypeError: undefined is not an object (evaluating 'data[i].energy.slice')

This makes it impossible for us to use the activity dataType on iOS. Is there any workaround or fix for this available? 

Thanks in advance!

![img_909116c75539-1](https://user-images.githubusercontent.com/3586773/35625346-4be71ad0-0692-11e8-9d09-d999cb2117bd.jpeg)

**Comment by dariosalviwork** [comment]
the only explanation can be because there is no energy associated with that sample, which is strange. The fix is quite immediate.
