### ISSUE TITLE
blood pressure type

### ISSUE THREAD

**Issue by exabyter** [dariosalvi78/cordova-plugin-health#102]
I try to make a query using blood_pressure type but it does not work. How can I get blood pressure?

**Comment by dariosalvi78** [comment]
You can't. It's not supported (yet).

**Comment by ivarkallejarv** [comment]
@dariosalvi78  Could you give a rough estimate on how long until it is supported?

**Comment by dariosalvi78** [comment]
I don't have a schedule for that, but it's high on the things to do. I'd be happy to merge PR if someone wants to try.

**Comment by nickdunn** [comment]
I'd also love to see this, it's the one thing stopping us using the plugin. Where would we begin?

**Comment by dariosalviwork** [comment]
I have drafted the query() function.
This might work already, but haven't tested it:
https://github.com/dariosalvi78/cordova-plugin-health/commit/0339379681bd409f669d8898bd6d69f7acd13f81

there is one thing that is missing: convert the values returned by Telerik's plugin into the ones of this plugin.
Anyone wants to contribute?

**Comment by dariosalviwork** [comment]
now it's tested on both Android and iOS, please let me know if it works for you too.
