### ISSUE TITLE
Ignore manual steps

### ISSUE THREAD

**Issue by aggarwalankush** [dariosalvi78/cordova-plugin-health#105]
are we planning to resolve this issue? https://github.com/Telerik-Verified-Plugins/HealthKit/issues/75 

Maybe I can open a PR like last time but someone with objective c knowledge would be great.

**Comment by dariosalviwork** [comment]
it would be great to get a PR, we could use the same flag in the query as used for Fit: filtered: true

**Comment by aggarwalankush** [comment]
Replacing `nil` https://github.com/dariosalvi78/cordova-plugin-health/blob/master/src/ios/HealthKit.m#L1506 with 
`NSPredicate *predicate = [NSPredicate predicateWithFormat:@"metadata.%K != YES", HKMetadataKeyWasUserEntered];`
works but I don't know how to pass it via filter.

**Comment by aggarwalankush** [comment]
@dariosalvi78 opened the PR, would be great if mereged. Also, a release would be great else I'll just point to github. 👍

**Comment by dariosalviwork** [comment]
thanks for this
