### ISSUE TITLE
com.google.android.gms:play-services-fitness dependencies

### ISSUE THREAD

**Issue by marioshtika** [dariosalvi78/cordova-plugin-health#108]
Hello Dario.

These last days when I build in android I get the below error

```
Execution failed for task ':processDebugResources'. > 
Error: more than one library with package name 'com.google.android.gms.license'
```

With some search in the internet I found a quick solution, by changing the below line 

`cordova.system.library.1=com.google.android.gms:play-services-fitness:11.+`

in the file **platforms/android/project.properties**.

Is there a way you can fix this or change the dependencies in the [plugin.xml](https://github.com/dariosalvi78/cordova-plugin-health/blob/master/plugin.xml) file

Thank you in advance.

**Comment by dariosalviwork** [comment]
I guess this is the same as (from the README):

> This plugin is set to use the latest version of the Google Play Services API (<framework src="com.google.android.gms:play-services-fitness:+" />). This is done to likely guarantee the compatibility with other plugins using Google Play Services, but bear in mind that a) the plugin was tested until version 9.8.0 of the APIs and b) other plugins may be using a different version of the API. If you run into an issue, check the generated gradle file (build.gradle) under dependencies between // SUB-PROJECT DEPENDENCIES START and // SUB-PROJECT DEPENDENCIES END and make sure that all versions of the com.google.android.gms:play-services-xxxx are the same.

??

**Comment by marioshtika** [comment]
Hello Dario,

You were right. I had an older version of android engine.  `<engine name="android" spec="~6.3.0">`

I run `ionic cordova platform@latest` and now everything works fine.

Thank you again.
