### ISSUE TITLE
Android exec() call threading issue

### ISSUE THREAD

**Issue by secondred-fleckner** [dariosalvi78/cordova-plugin-health#11]
Hi,

in an App where we sync several fitness data to server I encountered an App-freeze on calls. I thought that was a problem with proper dereferencing in the app and found it was caused by the plugins query and queryAggregated methods. (see logcat below)

`W/PluginManager(32105): THREAD WARNING: exec() call to health.queryAggregated blocked the main thread for 643ms. Plugin should use CordovaInterface.getThreadPool().`

`W/PluginManager(32105): THREAD WARNING: exec() call to health.query blocked the main thread for 354ms. Plugin should use CordovaInterface.getThreadPool().`

If I got some spare time I am going to try to fix it by myself, but do not want to leave it unmentioned.

Thank you very much for providing this repo,
keep going and have a nice weekend.

**Comment by dariosalvi78** [comment]
Thanks, I'll be happy to merge your fix
