### ISSUE TITLE
Google fit errors during authentication and query

### ISSUE THREAD

**Issue by KevRyan2** [dariosalvi78/cordova-plugin-health#110]
Running "@ionic-native/health": "^3.12.1" on "ionic-angular": "^3.7.1"

This plugin works perfectly on iOS but on Android running into a few issues.  

Code:
let array = ['distance', 'calories', 'activity', 'workouts', { read: ['heart_rate', 'steps']} ];

this.health.requestAuthorization(array).then(data => {
}, err => {
    //hits an error output which is = ""
    this.health.isAuthorized([array]).then(authorized => {
        //succeeds with   authorized = true, which indicates that even though requestAuthorization 
          failed, I am in fact authorized
    }, err => {
    });
});

Once I have ensured that I'm authorized as shown above, I run an query for steps
this.health.queryAggregated({
     startDate: new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000), 
     endDate  : new Date(), 
     dataType : 'steps', 
     bucket   : 'day'   
}).then(steps => {
}).catch(e => {
    //hits an error output which is = "Unexpected Error"
 });

As you can see the error outputs aren't of much help, and considering I no longer received the dreaded "User cancelled the dialog" response when the user is prompted to choose an email to authenticate with my application and google fit, I believe the API certificates are setup properly in the API Console.  Anybody have any thoughts here?

**Comment by dariosalvi78** [comment]
can you try, on a console, to request a simple access, e.g. to steps?

this.health.isAuthorized(['steps']).then(authorized => {
 console.log('ok');
 }, err => { 
console.error('err ' + err);
 });
});

that may help debug the issue

**Comment by KevRyan2** [comment]
That did help thank you, I eventually realized my issues so hopefully this helps somebody else.  First, if you're using your local environment to run the google fit requestAuthorization during development, you need to create the credentials on the Google Fit API with your debug certificate, not your release certificate, using this method https://developers.google.com/fit/android/get-api-key.  I'm assuming once it is pushed to the live Google Play store you will then also need to create a credential with your release certificate.  Additionally here are some helpful hints related to the errors I got while using this plugin. If, during your requestAuthorization(), you use an incorrect data type such as step_count, which is the way Android reads it but not the user friendly "steps" that you're able to use with this plugin, you may end up being able to get authorized by google fit (seems to pass through the checks and return true) but you won't technically be authorized for anything.  It won't return the "User cancelled the dialog" response, but afterwards isAuthorized() will return true yet you won't be authorized to read or write any google fit data.  If you then try to queryAggregated for anything, you will hit an error (as I did) with "Unexpected error", which I guess is google's very helpful way of saying you can't do that.  Hopefully this helps some people, and @dariosalvi78 thanks for the quick reply.

**Comment by dariosalviwork** [comment]
thanks for these hints, I'm happy it worked in the end
