### ISSUE TITLE
Unable to use filtered flag on queryAggregated

### ISSUE THREAD

**Issue by GaetanWi** [dariosalvi78/cordova-plugin-health#111]
Seems to miss some flags on the `HealthQueryOptionsAggregated` object. 

Judging from the `queryAggregated` Quirks sections of the README : 
`You can query for "filtered steps" adding the flag filtered: true to the query object. This returns the steps as filtered out by Google Fit, or the non-manual ones from HealthKit.`

But taking a closer look at the HealthQueryOptionsAggregated object : 

    export interface HealthQueryOptionsAggregated {
        startDate: Date;
        endDate: Date;
        dataType: string;
        bucket: string;
    }

It clearly lacks the `filtered` flag. 
Also, the flag is present on the `HealthQueryOptions` object. 

I'm using v1.0.5 of the plugin

**Comment by dariosalviwork** [comment]
What's HealthQueryOptionsAggregated ?

Maybe you're on the wrong plugin?

**Comment by GaetanWi** [comment]
@dariosalviwork I'm using Ionic Native Health plugin. But it seems the issue comes from the  `@ionic-native/health` and not the `cordova-plugin-health` itself. 

I think the issue can be closed
