### ISSUE TITLE
Can't read blood pressure data

### ISSUE THREAD

**Issue by ruazakharo** [dariosalvi78/cordova-plugin-health#115]
I'm trying to read blood pressure data using google fit. But when I call the authorization method, I get an error with the text 
 'Cannot authorise health data type com.google.blood_pressure, Application needs OAuth consent from the user'
I also request data for 'steps',' weight ',' distance ',' heart_rate ',' activity '
But for these parameters everything works well, but not for blood pressure

**Comment by dariosalvi78** [comment]
you need authorisation from Google, please check the README or the Google Fit documentation for instructions.

**Comment by dariosalvi78** [comment]
On a better thought, if it's only reading, [you should be able to read the data](https://developers.google.com/fit/android/data-types#restricted_data_types).
Make sure that you are requesting read-only access to blood pressure.

**Comment by ruazakharo** [comment]
@dariosalvi78 yes, I'm sure, because you forgot this changes for HelathPlugin.java
 if (healthscope == READ_PERMS) {
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ));
        } else if (healthscope == READ_WRITE_PERMS) {
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_GLUCOSE_READ_WRITE));
        }

it's necessary to allow read blood pressure. please fix it.

**Comment by dariosalviwork** [comment]
from line 578:
```
        if (bloodpressurescope == READ_PERMS) {
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ));
        } else if (bloodpressurescope == READ_WRITE_PERMS) {
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ_WRITE));
        }
```
there is no `healthscope` defined in the code

**Comment by dariosalviwork** [comment]
BTW, we're at version 1.1.0 now...

**Comment by ruazakharo** [comment]
@dariosalvi78 we can't download this version by npm, only 1.0.5 available now

**Comment by dariosalviwork** [comment]
OK, that was my mistake, I forgot to publish it. It should be online now... Let me know if it works.

**Comment by ruazakharo** [comment]
@dariosalvi78 yes, it's working fine now, thank you for your support. please close the ticket.
