### ISSUE TITLE
Documentation is unclear on how to get detailed sleep information

### ISSUE THREAD

**Issue by SUVOLewis** [dariosalvi78/cordova-plugin-health#117]
Basically, I'm creating an app using this plugin which will tie into Google Fit's information to access sleep data. All I want to do at the moment is to simply get all of the sleep information stored within Google Fit and output it to the console. As a "test run", I queried my step count in the last thirty days, and I got all the information I needed

Looking at the documentation, I've been able to query and display the sleep activities stored in Google Fit, but I don't get back much (if any) useful information. For example, I get back the calories and distance per "sleep" activity.

I would like much more information than that. For example, I can see that this plugin supports additional sleep "types", such as light, deep, REM, etc.
For reference, I am using "Sleep as Android" to record and export my sleep information to Google Fit. Due to the Fit redesign, I can no longer access or view exactly what data is being copied across to Fit, and then accessed in my app afterwards.

Is there something in the documentation that I'm missing? Should "Sleep as Android" be responsible for adding the additional ".deep, .light" types to the activity?

Any help or advice would be much appreciated.

**Comment by dariosalvi78** [comment]
the plugin supports storing and retrieving of different sleep types, you can test it yourself by storing a sample and retrieving it. It is therefore likely that Sleep as Android does not store deep and light sleep, but just sleep.

**Comment by SUVOLewis** [comment]
I didn't have a lot of chance to collect much test data until I slept yesterday, as I only just installed Sleep as Android, and was very unsure how it works.

After viewing a record of a full night's sleep, I've tested my phone with the data this morning and I'm collecting .light, .deep and .rem data within my query response now. Brilliant!
Do you know if the duration of the sleep phase activity is all the information that gets stored into Google Fit? 
It would be nice to see some additional stats get passed, but I'm unable to see everything these records are storing beyond what your queries return, as properly viewing your full sleep data via Google Fit has been taken out since the Fit App redesign. In fact, this plugin appears to be the only way I can view my sleep data at the moment.

**Comment by dariosalvi78** [comment]
AFAIK, duration of each phase is the only data available. The Sleep as Android App, though, also stores a lot of more data and makes it available in raw format, check its documentation (I cant' help you here). I'll close this issue.

**Comment by SUVOLewis** [comment]
Brilliant, thanks for your help!
