### ISSUE TITLE
Authorization not working correctly

### ISSUE THREAD

**Issue by desmeit** [dariosalvi78/cordova-plugin-health#122]
with this code I ask for permissions:

```
function health_auth(){
	
	//Tells if either Google Fit or HealthKit are available.
	navigator.health.isAvailable(function (granted){
								 console.log("health is available: " + granted);
		
		if (granted){
			
		var datatypes = [
						{
							write : ['weight', 'workouts', 'calories', 'distance' ]

								  }
					    ];
								 
			
	//Requests read and write access to a set of data types. 
	navigator.health.requestAuthorization(datatypes, function (granted){
		console.log("health request auth: " + granted);
						
				}, function (error){
						console.log(error);
					
					});
			
	}, function (error){
		console.log(JSON.stringify(error));
	});

}// end auth
```

this is working. I see at health that the permissions are there. then I click on a button to run the following function. immediately after clicking, the permissions for workout and calories are gone away and it asks me again. what I'm doing wrong?

```
function health( kalorien, activitytype ){
	
	//Tells if either Google Fit or HealthKit are available.
	navigator.health.isAvailable(function (granted){
	console.log("health is available: " + granted);
		
				var datatypes = [
								  {
									write : ['weight', 'workouts', 'calories', 'distance' ]
								  }
								];
	//Check if the app has authorization to read/write a set of datatypes.
	navigator.health.isAuthorized(datatypes, function (granted){
				console.log("health is authorized: " + granted);
				
				if (granted){
						  					 
					 navigator.health.store({
					        startDate:  new Date(new Date().getTime() - 21 * 60 * 1000), // 21 minutes ago
					        endDate: new Date(),
					        dataType: 'activity',
						value: activitytype,
						calories: kalorien,
						distance: 20,
						sourceName: 'XXX',
						sourceBundleId: 'XXX'
								}, function (data){
										console.log("health store: " + JSON.stringify(data));
								}, function (error){
										console.log("health store error: " + error);
								 });
	
					
				} 
				
			}, function (error){
				console.log(error);
			});
	
			
		
		
	}, function (error){
		console.log(JSON.stringify(error));
	});


}
```

**Comment by desmeit** [comment]
In addition the following issue:

navigator.health.isAuthorized AND navigator.health.store always give

null

in the callback. At this time I cannot work with this plugin. Too much issues, sorry...

**Comment by desmeit** [comment]
Okay,  I solved the first issue. The problem was that I requested only for "write" permissions, not for read. for storing it disabled the write permissions and asks again, even in addition for read permissions. it seems it is not possible to store without read permissions. or is there a parameter like in the the telerik healthkit plugin: 'requestReadPermission': false ?

Second issue with callback = null is still there.

**Comment by dariosalviwork** [comment]
I've tried your issue with a slightly different approach: I open the web inspector and run the code from the console.
Findings:

- `navigator.health.isAuthorized` returns true, which is what I expect
- `navigator.health.store` is not supposed to return anything
- even if the write permissions to the data types are granted, when trying to store and activity, it asks for read and write permissions for active energy and workouts. This is quite strange, why read and write? Why re-asking the write permissions? 

I've checked the saveWorkout function of Telerik's plugin, and looks like the problem is there. There is this not-well-documented feature that asks for read permissions, but you can skip it with a flag (the one you've found too).

I'll try to use that flag and see what happens.

For reference, this is my script (do not run it all in a once, it's interactive, see the comments):

```
//Tells if either Google Fit or HealthKit are available.
navigator.health.isAvailable(function (granted){
  console.log("health is available: " + granted);
  }, function (error){
  console.log(JSON.stringify(error));
 });

// I wait for the results, then I call
var datatypes = [ { write : ['weight', 'workouts', 'calories', 'distance' ] } ];
navigator.health.requestAuthorization(datatypes,
   function () {
     console.log("health request authorised");
   }, function (error){
     console.log(error);
});

// I get the following list of items to agree: active energy, cycling distance, resting energy, walking+running distance, weight, workouts
// I give all datatypes write access, then I call
navigator.health.isAuthorized(datatypes,
   function (granted){
     console.log("health is authorized: " + granted);
}, function (error){
     console.log(error);
})

// which returns true, as epected
// then I store the activity:
navigator.health.store({
  startDate:  new Date(new Date().getTime() - 21 * 60 * 1000),
  endDate: new Date(),
  dataType: 'activity',
  value: 'dancing',
  calories: 500,
  distance: 20
  }, function () {
    console.log("stored");
  }, function (error){
    console.log("health store error: " + error);
});

// at this point it asks me again for read and write permissions for actie energy and workouts, why is that?
// let's retry, to see what happens
navigator.health.store({
  startDate:  new Date(new Date().getTime() - 22 * 60 * 60 * 1000),
  endDate: new Date(new Date().getTime() - 21  * 60 * 60 * 1000),
  dataType: 'activity',
  value: 'dancing',
  calories: 700,
  distance: 40
  }, function () {
    console.log("stored");
  }, function (error){
    console.log("health store error: " + error);
});

// now it didn't re-ask... strange
// what if I ask for the permissions?
navigator.health.isAuthorized(datatypes,
   function (granted){
     console.log("health is authorized: " + granted);
}, function (error){
     console.log(error);
})

// gives me true again, as expected

```

**Comment by dariosalviwork** [comment]
I have added the `requestReadPermission`  flag to the `store()` function when saving workouts, so now it does not ask for read permissions. As for the other 2 "bugs" (the null returned by `store()` and `isAuthorized()`), one is not a bug, the other I wasn't able to reproduce it.

**Comment by desmeit** [comment]
thanks for your detailed answers. 

- navigator.health.isAuthorized is now returning true, it was my mistake before.
- navigator.health.store returns null: this irritates a little bit, but thats okay. Maybe you can write it to the docs?
- I will try it with requestReadPermission as well.

Thanks for your help.

**Comment by desmeit** [comment]
requestReadPermission is working. perfectly.

**Comment by dariosalviwork** [comment]
> navigator.health.store returns null: this irritates a little bit, but thats okay. Maybe you can write it to the docs?

I'm sorry to irritate you, but, from the README it looks pretty clear to me:

> successCallback: {type: function}, called if all OK

especially if you compare with other functions, for example in query():

> successCallback: {type: function(data) }, called if all OK, data contains ... bla bla bla
