### ISSUE TITLE
requestAuthorization() sometimes fails with "GoogleApiClient is not connected yet"

### ISSUE THREAD

**Issue by marcovtwout** [dariosalvi78/cordova-plugin-health#123]
Sometimes when I call `requestAuthorization()`" the Promise throws the following error:

```
GoogleApiClient is not connected yet
```

I am using the Ionic wrapper with the following code:
```
let datatypes = [
   {read: ['steps']}
];

this.health.requestAuthorization(datatypes)
   .then(result => {
        console.log(result);
   })
   .catch((error) => {
        console.error(error);
   });
```

I have not been able yet to reproduce this consistently, but it seems to happen when I open my app through a local notification. Is there any other health function that needs to be completed before calling requestAuthorization()? Just to be clear, I am always calling requestAuthorization() before trying to perform a query().

**Comment by dariosalviwork** [comment]
I really don't know.
It may be that the app is already there and authorised and you shouldn't really call requestAuthorization... Try removing requestAuthorization() and see what happens.

**Comment by marcovtwout** [comment]
I can reproduce the error now - in my app there is a race condition that causes requestAuthorization() to be called twice so it runs parallel. That probably isn't something this library would have to prevent, but perhaps it is noteworthy?

**Comment by dariosalviwork** [comment]
yes, that's definitely out of the scope of this plugin. Thanks for letting me know
