### ISSUE TITLE
Google Fit Blood Glucose & Pressure Scope Error

### ISSUE THREAD

**Issue by dopplerDistortion** [dariosalvi78/cordova-plugin-health#124]
While compiling for Android it throws this error. 

> symbol:   variable FITNESS_BLOOD_GLUCOSE_READ
>   location: class Scopes
> ..android/src/org/apache/cordova/health/HealthPlugin.java:577: error: cannot find symbol
>             builder.addScope(new Scope(Scopes.FITNESS_BLOOD_GLUCOSE_READ_WRITE));
>                                              ^
>   symbol:   variable FITNESS_BLOOD_GLUCOSE_READ_WRITE
>   location: class Scopes
> ../android/src/org/apache/cordova/health/HealthPlugin.java:580: error: cannot find symbol
>             builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ));
>                                              ^
>   symbol:   variable FITNESS_BLOOD_PRESSURE_READ
>   location: class Scopes
> ../android/src/org/apache/cordova/health/HealthPlugin.java:582: error: cannot find symbol
>             builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ_WRITE));
>                                              ^
>   symbol:   variable FITNESS_BLOOD_PRESSURE_READ_WRITE
>   location: class Scopes

For temprorary fix I changed the scopes to the strings below

static const char | FITNESS_BLOOD_GLUCOSE_READ [] = {"https://www.googleapis.com/auth/fitness.blood_glucose.read"}

static const char | FITNESS_BLOOD_GLUCOSE_WRITE [] = {"https://www.googleapis.com/auth/fitness.blood_glucose.write"} 

static const char | FITNESS_BLOOD_PRESSURE_READ [] = {"https://www.googleapis.com/auth/fitness.blood_pressure.read"}
 
static const char | FITNESS_BLOOD_PRESSURE_WRITE [] = {"https://www.googleapis.com/auth/fitness.blood_pressure.write"}

src: https://developers.google.com/resources/api-libraries/documentation/fitness/v1/cpp/latest/classgoogle__fitness__api_1_1FitnessService_1_1SCOPES.html

My ionic info

Ionic:

   ionic (Ionic CLI)  : 4.2.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.4, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/goksenin/Library/Android/sdk)
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255

**Comment by dariosalvi78** [comment]
You need to have Google Services API downloaded in your SDK and a recent version of them.

**Comment by dopplerDistortion** [comment]
Seems already latest or I am missing something.

![screen shot 2018-10-31 at 14 46 37](https://user-images.githubusercontent.com/1084392/47786151-e6277080-dd1b-11e8-9700-289c1adbc9c1.png)

**Comment by dariosalviwork** [comment]
Yes, it looks like they're updated.
I have a similar setup here and it compiles. I really don't know what's going on.

[Someone has run into your same issue](https://www.outsystems.com/forums/discussion/40563/fails-when-generating-android-app/) but there are no solutions.

**Comment by dariosalviwork** [comment]
Probably your Android project is using an older version of the APIs.
The plugin suggests to use the latest available version, but you may be using another plugin that is constraining the version to an older one.

From the README:

> This plugin is set to use the latest version of the Google Play Services API (<framework src="com.google.android.gms:play-services-fitness:+" />). This is done to likely guarantee the compatibility with other plugins using Google Play Services, but bear in mind that other plugins may be using a different version of the API. If you run into an issue, check the generated gradle file (build.gradle) under dependencies between // SUB-PROJECT DEPENDENCIES START and // SUB-PROJECT DEPENDENCIES END and make sure that all versions of the com.google.android.gms:play-services-xxxx are the same.

**Comment by dopplerDistortion** [comment]
This issue is solved with clean ionic + android studio installation. I am closing with this suggestion.
