### ISSUE TITLE
requestAuthorization losing state on App reopen

### ISSUE THREAD

**Issue by felipeclopes** [dariosalvi78/cordova-plugin-health#125]
Hello, I'm trying to access read-only Steps data on iOS, but it seems like the `isAuthorized` only returns true if I `requestAuthorization` in the current App session. Which means that once I reopen the app the isAuthorized returns false even if the user already authorized it previously.

Is it necessary to always `requestAuthorization` after the app opens?

**Comment by dariosalviwork** [comment]
No, requestAuthorization is needed before any query at least in Android.
Make sure you use the same datatypes in requestAuthorization and isAuthorized.
If you only want to read steps, it should be something like:

```
[
  {
    read : ['steps']
  }
]
```

**Comment by felipeclopes** [comment]
I'm definitely calling the `requestAuthorization` and `isAuthorized` with the same parameters. It does work when I'm on the same screen, but even when changing screens, do I need to `requestAuthorization` again or is there a way for me to maintain the state?

**Comment by dariosalviwork** [comment]
in principle it should be stateless...

**Comment by felipeclopes** [comment]
Thank you, I just migrated to a stateless approach.
