### ISSUE TITLE
Android: error: cannot find symbol FITNESS_BLOOD_GLUCOSE_READ

### ISSUE THREAD

**Issue by gotters** [dariosalvi78/cordova-plugin-health#128]
I am running this plugin via ionic and it won't compile for android. See below for errors
Other than installing the cordova plugin and the ionic native health (described here) is there something else that needs to be setup in my environment to get this to compile?

Thanks

```

C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:574: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_GLUCOSE_READ));
                                             ^
  symbol:   variable FITNESS_BLOOD_GLUCOSE_READ
  location: class Scopes
C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:576: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_GLUCOSE_READ_WRITE));
                                             ^
  symbol:   variable FITNESS_BLOOD_GLUCOSE_READ_WRITE
  location: class Scopes
C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:579: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ));
                                             ^
  symbol:   variable FITNESS_BLOOD_PRESSURE_READ
  location: class Scopes
C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\health\HealthPlugin.java:581: error: cannot find symbol
            builder.addScope(new Scope(Scopes.FITNESS_BLOOD_PRESSURE_READ_WRITE));
                                             ^
  symbol:   variable FITNESS_BLOOD_PRESSURE_READ_WRITE
  location: class Scopes
Note: C:\Workspace\Apps\ProjectT\Mobilev2\platforms\android\src\org\apache\cordova\splashscreen\SplashScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by Losnen** [comment]
I got the same

**Comment by dariosalvi78** [comment]
looks like you're not using the latest version of the fitness APIs

**Comment by dariosalvi78** [comment]
the plugin requires the latest version of the google fitness APIs, but you might have another plugin that fixes the APIs to an older version. Check the README where it says:

> This plugin is set to use the latest version of the Google Play Services API (<framework src="com.google.android.gms:play-services-fitness:+" />). This is done to likely guarantee the compatibility with other plugins using Google Play Services, but bear in mind that other plugins may be using a different version of the API. If you run into an issue, check the generated gradle file (build.gradle) under dependencies between // SUB-PROJECT DEPENDENCIES START and // SUB-PROJECT DEPENDENCIES END and make sure that all versions of the com.google.android.gms:play-services-xxxx are the same.

**Comment by gotters** [comment]
This is all i have in my build gradle...
So I assume thats not the issue? any ideas?

    // SUB-PROJECT DEPENDENCIES START
    debugCompile(project(path: "CordovaLib", configuration: "debug"))
    releaseCompile(project(path: "CordovaLib", configuration: "release"))
    compile "com.google.android.gms:play-services-fitness:+"
    // SUB-PROJECT DEPENDENCIES END

**Comment by gotters** [comment]
In ionic i removed by android platform and re-added it at ver 6.3 and now its working. Looks like the issue was my android 6.2.3 version in ionic.
