### ISSUE TITLE
Google Fit account switching

### ISSUE THREAD

**Issue by v3vinvin** [dariosalvi78/cordova-plugin-health#131]
Hello, I'll like to ask if it's possible to prompt the which google account to get those steps from after the first time of requestAuthorization? I've been searching inside the plugin file, and I can't seem to figure it out.

**Comment by dariosalvi78** [comment]
I am not sure what you mean, but the plugin asks for the user before connecting to the Google APIs

**Comment by v3vinvin** [comment]
> I am not sure what you mean, but the plugin asks for the user before connecting to the Google APIs

I apologise for my poor explanation. 

What I meant is once the plugin asked the user which google account he/she would like to use. Is it possible to switch to another google account? I can't seem to find a way to de-link the google account being selected on the first initialisation. 

Use-case:
1- "User A" turn on the "Google-Fit" toggle button.
2- Fires "RequestAuthorization", ask user to choose or login a Google account.
3- Once selected, get all the data from "User A" Google account. "User A" closes the app.
4- "User B" uses back the same device and wanted to get his "Google Fit" Data. 
5- *Fires "RequestAuthorization*, but the plugin has already request before by "User A". Uses "User A" Google Account instead.

**Comment by dariosalvi78** [comment]
There's a disconnect() that does exactly what you're looking for...

**Comment by v3vinvin** [comment]
Hey there, Dario.

Thanks for the info about the disconnect(). But I was wondering. Have you experienced before whereby after a few times of disconnecting and connecting. the disconnect would have an fail callback of "cannot disconnect,null"?

**Comment by dariosalvi78** [comment]
I haven't used this functionality myself very much to be honest, it's such a niche case...
