### ISSUE TITLE
Does this plugin works with Wear OS (Google) on iOS?

### ISSUE THREAD

**Issue by v3vinvin** [dariosalvi78/cordova-plugin-health#133]
I know that there's no "**Google Fit**" on **iOS**, but they have an alternative to get **Wear OS's smart watches** to sync to "**Google Fit**" which the app is called "**Wear OS**" on **AppStore**. Would it be possible that I could use this plugin on iOS?

**Comment by dariosalviwork** [comment]
No. But if the Wear Os app writes into HealthKit, then you can retrieve data from HealthKit.
