### ISSUE TITLE
what is the way to add Custom dataType to google fit (Health kit doesn't support i know)??

### ISSUE THREAD

**Issue by A1996KASH** [dariosalvi78/cordova-plugin-health#134]
what is the way to add Custom dataType to google fit (Health kit doesn't support i know)??

**Comment by dariosalvi78** [comment]
there are no guidelines, except from [what Google already says](https://developers.google.com/fit/android/data-types#custom_data_types).
You open the code and modify it.
You can use the date of birth as an example.

If you want to make the custom data "official" through a PR, please let's discuss if the data type is general enough first.

**Comment by A1996KASH** [comment]
Thanks for the quick response. I work for a company that basically deals with human Motion data so we have a  Algorithm that generates Gait Velocity Cadence and other parameters using raw data so we wanted to add these parameters as custom dataType so that we can access them using our ionic app.

**Comment by dariosalvi78** [comment]
motion-related data could be of general interest, so I will be happy to add them officially to the plugin. Feel free to send a PR if you're up to!

**Comment by A1996KASH** [comment]
Thanks. Can you please share your Email I'd I would like to discuss more about this if you don't have any issues. My email id is akash.sengar@zeblok.com
