### ISSUE TITLE
crashes in ios 12

### ISSUE THREAD

**Issue by wizk1d** [dariosalvi78/cordova-plugin-health#135]
App crashes when trying to get permission in ios 12. Works fine in ios 11 and before.

**Comment by dariosalviwork** [comment]
any error message?

**Comment by dariosalviwork** [comment]
is this issue still relevant?

**Comment by dariosalviwork** [comment]
Tested here on ios 12.2 and it works.

It's very likely that you have forgotten to set the HEALTH_READ_PERMISSION and HEALTH_WRITE_PERMISSION, or that those were deleted for some reason.

Check if you get something similar in your xcode console:

> NSHealthUpdateUsageDescription must be set in the app's Info.plist in order to request write authorization for the following types....
