### ISSUE TITLE
Unable to authorize google fit in playstore app

### ISSUE THREAD

**Issue by gotters** [dariosalvi78/cordova-plugin-health#138]
When testing directly on my phone I am able to access google fit without any problems.

When I release as a test app in play store I am not able to authorize against google fit.
I DID create new OAuth credentials using the keystore that was used to sign the app. (In other words I have a debug version and a "release" version of my oauth credentials in google api console).

How can I investigate whats going wrong? Am I meant to be doing something with the client ID generated after creating the new credentials?
Could it have somethign to do with the Consent screen which says "Verification Status: Not published"
Once again this all works in debug mode.

**Comment by dariosalviwork** [comment]
looks like an Oauth thing, but I don't know, the error messages from Google are not very self generous with details.
Try dumping the messages with [logcat](https://developer.android.com/studio/command-line/logcat)

**Comment by gotters** [comment]
Not getting too much clarity. This is what I am seeing in logcat.
Not all relevant but I wasnt sure exactly what might be helpful to show you. But you can see the health plugin failing towards the bottom.
Please let me know.
--------------------------------------------

02-07 21:19:13.679   769   794 I ActivityManager: Displayed com.google.android.gms/.common.account.AccountChipAccountPickerActivity: +228ms
02-07 21:19:14.068 13976 14219 V ClClient: SEND(359)	KeepAliveRequest_4()	UID:869a65bd-50c8-4600-a9be-263550e95385
02-07 21:19:14.442 13976 14218 V ClClient: RECV(359)  +0.4s	KeepAliveResponse_5(hasEstablishedSession=true)
02-07 21:19:14.573 30034 30070 D OpenGLRenderer: endAllActiveAnimators on 0x7ed4f01c00 (ListView) with handle 0x7ed3ac4c00
02-07 21:19:14.810 14873 14873 D CordovaActivity: Incoming Result. Request code = 1
02-07 21:19:14.810 14873 14873 D CordovaInterfaceImpl: Sending activity result to plugin
02-07 21:19:14.817 14873 14873 D CordovaActivity: Resumed the activity.
02-07 21:19:15.888   769  5529 I ActivityManager: Process com.google.process.gservices (pid 29324) has died: cch+6CEM 
02-07 21:19:15.889   769   786 W zygote64: kill(-29324, 9) failed: No such process
02-07 21:19:15.889   769   786 I zygote64: Successfully killed process cgroup uid 10019 pid 29324 in 0ms
02-07 21:19:16.386 14873 14873 D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 1 : Checking health data - attempt
02-07 21:19:16.386 14873 14873 I chromium: [INFO:CONSOLE(1)] "Checking health data - attempt", source: file:///android_asset/www/build/main.js (1)
02-07 21:19:16.390 14873 14963 W CordovaPlugin: Attempted to send a second callback for ID: health471167826
02-07 21:19:16.390 14873 14963 W CordovaPlugin: Result was: false
02-07 21:19:16.398 14873 14873 D SystemWebChromeClient: file:///android_asset/www/build/main.js: Line 1 : true
02-07 21:19:16.398 14873 14873 I chromium: [INFO:CONSOLE(1)] "true", source: file:///android_asset/www/build/main.js (1)
02-07 21:19:16.419 14873 14873 I cordova-plugin-health: Connection to Fit failed, cause: null
02-07 21:19:16.419 14873 14873 I cordova-plugin-health: Attempting to resolve failed connection
02-07 21:19:16.420   769 12578 I ActivityManager: START u0 {act=com.google.android.gms.signin.action.SIGN_IN cmp=com.google.android.gms/.signin.activity.SignInActivity (has extras)} from uid 10019
02-07 21:19:16.431 14873 14873 D CordovaActivity: Paused the activity.
02-07 21:19:16.561   769   794 I ActivityManager: Displayed com.google.android.gms/.signin.activity.SignInActivity: +101ms
02-07 21:19:16.649 30034 30081 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-07 21:19:16.649 30034 30081 W Conscrypt: 	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@15090019@15.0.90 (040400-231259764):2)
02-07 21:19:16.649 30034 30081 W Conscrypt: 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@15090019@15.0.90 (040400-231259764):2)
02-07 21:19:16.718 30034 30081 W Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
02-07 21:19:16.719 30034 30081 W Conscrypt: 	at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@15090019@15.0.90 (040400-231259764):2)
02-07 21:19:16.719 30034 30081 W Conscrypt: 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@15090019@15.0.90 (040400-231259764):2)
02-07 21:19:16.732   769  1282 I WifiService: getWifiEnabledState uid=10144
02-07 21:19:16.733   769  5535 I WifiService: getConnectionInfo uid=10144
02-07 21:19:16.733   769  5535 D WifiPermissionsUtil: Denied: no location permission
02-07 21:19:16.733   769  5535 D WifiPermissionsUtil: Denied: The current config is not for an open network.
02-07 21:19:16.898 30034 30034 I SignIn  : [Activity,SignInChimeraActivity] Couldn't fetch app's branding information, but continuing without it.
02-07 21:19:16.900   769  1285 I ActivityManager: START u0 {act=com.google.android.gms.common.account.CHOOSE_ACCOUNT_USERTILE pkg=com.google.android.gms cmp=com.google.android.gms/.common.account.AccountChipAccountPickerActivity (has extras)} from uid 10019
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at java.lang.Class.classForName(Native Method)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at java.lang.Class.forName(Class.java:453)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at java.lang.Class.forName(Class.java:378)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at aet.a(:com.google.android.gms@15090019@15.0.90 (040400-231259764):5)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at aet.onCreateView(:com.google.android.gms@15090019@15.0.90 (040400-231259764):1)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:1933)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2586)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2659)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2067)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:160)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.Activity.performCreate(Activity.java:7016)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.Activity.performCreate(Activity.java:7000)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.os.Looper.loop(Looper.java:164)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatViewInflater" on path: DexPathList[[zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-fCdStwcTogwVwYe3tNbnkg==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-fCdStwcTogwVwYe3tNbnkg==/lib/arm64, /data/app/com.google.android.gms-fCdStwcTogwVwYe3tNbnkg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-07 21:19:16.946 30034 30034 I AppCompatDelegate: 	... 28 more
02-07 21:19:17.076   769   794 I ActivityManager: Displayed com.google.android.gms/.common.account.AccountChipAccountPickerActivity: +153ms
02-07 21:19:17.928 30034 30070 D OpenGLRenderer: endAllActiveAnimators on 0x7ed4efa400 (ListView) with handle 0x7ed3ac4da0
02-07 21:19:18.103 14873 14873 D CordovaActivity: Incoming Result. Request code = 1
02-07 21:19:18.103 14873 14873 D CordovaInterfaceImpl: Sending activity result to plugin
02-07 21:19:18.112 14873 14873 D CordovaActivity: Resumed the activity.
02-07 21:19:19.542   769  3422 I WifiService: getWifiEnabledState uid=10144
02-07 21:19:19.543   769   780 I WifiService: getConnectionInfo uid=10144
02-07 21:19:19.543   769   780 D WifiPermissionsUtil: Denied: no location permission
02-07 21:19:19.543   769   780 D WifiPermissionsUtil: Denied: The current config is not for an open network.

**Comment by dariosalvi78** [comment]
can't see anything in particular. Does it ask to select the account?

**Comment by gotters** [comment]
Yes. I select the account and fails at that point

**Comment by dariosalvi78** [comment]
My only suggestion is to restart the whole oauth thing from the scratch, sometimes it just gets messy...

**Comment by gotters** [comment]
You mean recreate the oauth id for the google api? I already did that.
Is there any way to get more info about what the actual error is?

**Comment by dariosalvi78** [comment]
you can try opening the app with Android studio and debug from there, but I doubt you will see anything that logcat doesn't show already.

**Comment by gotters** [comment]
still not having any luck. recreated oath a bunch of times. Anyone else having this? Once again it works using the debug thumbprint but not one generated for my release. (even though its just an internal testing release)

**Comment by gotters** [comment]
is it possible that once you are trying to authenticate for a release build (even if its only in internal testing in app store) that Google API needs more info...aside from OAuth Client ID, for eg the Consent screen and domain verification?
Can anyone confirm either way?

**Comment by dariosalvi78** [comment]
The fact that the app is in beta shouldn't change anything, but, yes, you
need the consent screen setup.

**Comment by gotters** [comment]
To what extent does it need to be setup? I currently have a name and
support email.
But no logos, domain, private policy link, website link etc..
Do i need all of those??

**Comment by gotters** [comment]
After all that issue is resolved. It turns out Google App Signing was enabled on my app (don't ever remember doing that). I created a new OAuth Client ID using that SHA1 and it worked!
Thanks for all your help

**Comment by dariosalvi78** [comment]
No, you don't need to specify all of them AFAIK.
If the debug keys work then the production keys should work too.

Make sure you are using the same package name and that it is the same in
the package.json. Make sure the Fitness API is active ( it should given
that it works in debug). Make sure the SHA keys are correct.
Can't think of anything else...
