### ISSUE TITLE
Unable to query sleep data in iOS

### ISSUE THREAD

**Issue by Haroon6138** [dariosalvi78/cordova-plugin-health#140]
hello,
first of all, thank you for such a fantastic plugin. i am able to get all the basic data like distance, steps, heartrate etc. via HealthKit on iOS, but i am unable to get sleep data, when i specify datatype: 'sleep' or datatype: 'activity.sleep', gives the following error:

`No DATA:  unknown data type sleep`

The Sleep data is there in HealthKit i've checked & it shows up there, but i am unable to get it here.
i am using ionic 3.

**EDIT:**
I have got the sleep data within the activity Array, but the values seem duplicate, here is a screenshot of the response:

<img width="1416" alt="screen shot 2019-02-25 at 12 21 15 pm" src="https://user-images.githubusercontent.com/47740408/53326997-ee717000-38f7-11e9-86e1-8919fc525f8a.png">

this is the query data that i am requesting:

```
let activityOptions = {
      startDate: new Date(new Date().getTime() - 1 * 24 * 60 * 60 * 1000),
      endDate: new Date(),
      dataType: 'activity',
      limit: 100
    }
```

Please suggest if something can be done about it?

**Comment by dariosalviwork** [comment]
there is no sleep as such in this plugin, you can either use "activity" and filter sleep out or use Telerik's underlying plugin.

Data duplication: I have no idea why, also because only sleep seems to be duplicated and not the other activities.

**Comment by dariosalviwork** [comment]
actually try to query for sleep using [Telerik's plugin](https://github.com/EddyVerbruggen/HealthKit) (you don't need to install it, this plugin is an extension of that one). If you still get duplicates then we can exclude a bug in this plugin.

**Comment by pankajsdm** [comment]
how to implement sleep health kit query in ionic4?
