### ISSUE TITLE
Read & write UV Index on iOS Health

### ISSUE THREAD

**Issue by AliMonam** [dariosalvi78/cordova-plugin-health#142]
Is there any way to read & write UV Index on iOS Health?

**Comment by dariosalviwork** [comment]
looks like [yes](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier/1615195-uvexposure), but it's not supported yet in this plugin.
You can either extend it (and send me a pull request) or access the underlying Telerik's plugin, which is data type agnostic.
