### ISSUE TITLE
Issue in IOS 12

### ISSUE THREAD

**Issue by hasib2cool** [dariosalvi78/cordova-plugin-health#143]
Dear Team ,
It is not working after i updated my phone to ios 12. It was working fine in ios11.
Please test it in IOS 12 latest update 12.1.4.
Regards,

**Comment by dariosalvi78** [comment]
looks like a duplicate of #135. Have you found any error message? Can you describe what happens?

**Comment by hasib2cool** [comment]
No i am not finding any error message.
Even it is not asking for permissions.

**Comment by dariosalviwork** [comment]
Tested here on ios 12.2 and it works.

It's very likely that you have forgotten to set the HEALTH_READ_PERMISSION and HEALTH_WRITE_PERMISSION, or that those were deleted for some reason.

Check if you get something similar in your xcode console:

> NSHealthUpdateUsageDescription must be set in the app's Info.plist in order to request write authorization for the following types....
