### ISSUE TITLE
Android - User cancelled the dialog

### ISSUE THREAD

**Issue by brainssolutions** [dariosalvi78/cordova-plugin-health#144]
Hi Guys,
I just finished implementing the plugin version @ 1.1.2 in my Android project but I always receive the message as the subject:  "User cancelled the dialog ".

From the official documentation I learned that this error warns that there are problems with the OAuth APIs.

I just checked all the bees and it seems to be all OK.

The project was already created because push notifications for IOS and Android Firebase have already been used to create for me the project by setting the calls via OAuth.

I verified that the names of the application packages coincided and that through the KeyStore the SHA1 token was the same.

On IOS there were no problems.

My test is on a physical and not a virtual device.
I installed the Google Fit app myself.

Details : 
8.1.2 (cordova-lib@8.1.1)
android 7.1.4

Device with Android M503 - Android 7.0

**Comment by MichielJ87** [comment]
Maybe this solves your question https://github.com/dariosalvi78/cordova-plugin-health/issues/100

It solved a similar problem I had when first putting android app online via Google play :) 

Kind regards, Michiel

**Comment by brainssolutions** [comment]
Hi @MichielJ87 
Thank you for your reply, unfortunately it did not help me solve the problem.

I had already verified that the various hashes corresponded. Consider that my firebase for push notifications has already been configured with OAuth so that it has already automatically added information about the Cloud Platform.

**Comment by dariosalvi78** [comment]
it´s about the Google API configuration.
I'd suggest you go over the whole configuration again, and then again, and then maybe again.
We've all been there before, and it's painful.

**Comment by dariosalvi78** [comment]
Have you managed to solve it?

**Comment by brainssolutions** [comment]
Hi @dariosalvi78 ,
The problem seems to be the approval of the "OAuth consensus Screen".

Although The verification status is known to be  "In the process of verification (the last approved consensus screen is still in use) ".

I Think this is the problem, since the default screen was only asking for name and profile data.

I Await approval from Google and I update you. Thank you for your concern.

**Comment by dariosalviwork** [comment]
can we agree this is not a plugin's bug?

**Comment by abowerman** [comment]
Definitely not an issue with this plugin. 

Just a note to anyone else with this issue:

> If Google Play has App signing certificate enabled, then you MUST use SHA-1 certificate fingerprint of this certificate, instead of the Upload certificate

You can find that cert under `App Signing` -> `App signing certificate` on the google play console.
