### ISSUE TITLE
Sleep Analysis data not included in Sample Query from HealthKit

### ISSUE THREAD

**Issue by hparadiz** [dariosalvi78/cordova-plugin-health#146]
I'm with @IncentFit

Just wanted to confirm that #140 is a real bug. 

We have a screenshot from a user showing sleep data but we're getting nothing from them for that date.

Sleep Analysis data is distinctly different from Sleep data and is likely available from another [query](https://developer.apple.com/documentation/healthkit/queries).

It's enough of an issue for us that we're likely to attempt to fix this ourselves in our next sprint.

**Comment by dariosalvi78** [comment]
what is the bug?
the absence of sleep as datatype or duplicates?

**Comment by hparadiz** [comment]
We get this data.
```json
{
      "categoryType.identifier": "HKCategoryTypeIdentifierSleepAnalysis",
      "endDate": "2019-01-02T11:34:00-05:00",
      "startDate": "2019-01-02T11:34:00-05:00",
      "UUID": "FA2E9D17-A60C-4B95-8737-10733A42D957",
      "sourceBundleId": "com.apple.Health",
      "value": 0,
      "sourceName": "Health",
      "metadata": {
        "HKWasUserEntered": 1
      },
      "categoryType.description": "HKCategoryTypeIdentifierSleepAnalysis"
    },
    {
      "categoryType.identifier": "HKCategoryTypeIdentifierSleepAnalysis",
      "endDate": "2019-01-02T07:00:00-05:00",
      "startDate": "2019-01-01T22:00:00-05:00",
      "UUID": "FE866DDF-135E-4B29-91D7-E4302F3FF83F",
      "sourceBundleId": "com.apple.Health",
      "value": 0,
      "sourceName": "Health",
      "metadata": {
        "HKWasUserEntered": 1
      },
      "categoryType.description": "HKCategoryTypeIdentifierSleepAnalysis"
    },
    {
      "categoryType.identifier": "HKCategoryTypeIdentifierSleepAnalysis",
      "endDate": "2019-01-01T09:30:00-05:00",
      "startDate": "2018-12-31T01:30:00-05:00",
      "UUID": "37431B5F-8545-4EE6-8FE8-FBB89F0F0ECE",
      "sourceBundleId": "com.apple.Health",
      "value": 0,
      "sourceName": "Health",
      "metadata": {
        "HKWasUserEntered": 1
      },
      "categoryType.description": "HKCategoryTypeIdentifierSleepAnalysis"
    }
```

Meanwhile they submitted this screenshot on February 11th
![image](https://user-images.githubusercontent.com/195216/54635127-e79ece80-4a59-11e9-942d-4633a61e3c91.png)


I'm trying to get customer support to find out which third party app / tracker they used.

**Comment by hcharania** [comment]
@hparadiz we are facing the same issue where our the Bed Time app is storing the sleep data as "Sleep Analysis" which is not being returned with the query.  Did you manage to figure this out?

**Comment by hparadiz** [comment]
@hcharania is your app available on the App Store? I'm looking for something that can write sleep analysis data to Health which we **can't** query so we can reproduce the problem and fix it.

**Comment by hcharania** [comment]
@hparadiz , no it is not yet.  However we managed to retrieve the "inBed" records by changing our code to use "query" instead of "queryAggregated".  We now massage the data ourselves to bucket the sleep records into hours.  Would have been nice if "queryAggregated" did that for us, but it did not work for "inBed" records.

**Comment by dariosalvi78** [comment]
Guys, I'm following you. It looks like it's a healthier thing, nothing the plugin could fix easily.
Let me know if you find any bug...

**Comment by hcharania** [comment]
It would be nice if queryAggregated returned the data

**Comment by dariosalviwork** [comment]
I have tried to simulate your issue.
I have manually inserted "in bed" time from 10PM to 7AM.
query returns:
```
{
"startDate":"2019-04-01T20:00:00.000Z",
"endDate":"2019-04-02T05:00:00.000Z",
"value":"sleep.inBed",
"unit":"activityType",
"sourceName":"Health",
"sourceBundleId":"com.apple.Health"
}
```
which is correct.

I have tried aggregatedQuery (no buckets) and it returns:

```
{
"startDate":"2019-04-01T20:00:00.000Z",
"endDate":"2019-04-02T05:00:00.000Z",
"value": {
  "sleep.inBed":{"duration":32400000}
 },
"unit":"activitySummary"
}
```

which is also correct.

I have noticed, though, that with 1 day buckets, the information gets lost and I am not sure why, but that would be another type of bug.

In any case, to me it seems that the plugin is working correctly, so I'll close this issue. Feel free to reopen it if you think I'm mistaken.
