### ISSUE TITLE
Steps in decimal

### ISSUE THREAD

**Issue by neilbo** [dariosalvi78/cordova-plugin-health#147]
Steps returns decimal on iPhone8 plus iOS 12.2

Example app images:

![IMG_DFAE713746EF-1](https://user-images.githubusercontent.com/1586394/56008481-b98e7080-5d1f-11e9-9b7f-9ebbad342ec3.jpeg)
![IMG_3C3FE95991F7-1](https://user-images.githubusercontent.com/1586394/56008485-bc896100-5d1f-11e9-95a4-bd7b1b46f18d.jpeg)

similar issue in another project:
https://github.com/terrillo/rn-apple-healthkit/issues/32

**Comment by dariosalviwork** [comment]
it's probably due to approximations done by HealthKit, not a plugin issue.
Just cut the decimals on the UI.
