### ISSUE TITLE
Android queryAggregated() calories.active error

### ISSUE THREAD

**Issue by pnag90** [dariosalvi78/cordova-plugin-health#150]
Error when requesting a _queryAggregated_ of datatype "calories.active".

> Uncaught TypeError: Cannot read property 'getTime' of undefined
    at health.js:100
    at health.js:130
    at Object.callbackFromNative (cordova.js:288)
    at <anonymous>:1:9
(anonymous)	@	health.js:100
(anonymous)	@	health.js:130
callbackFromNative	@	cordova.js:288
(anonymous)	@	VM296:1

**Debug state:**
![image](https://user-images.githubusercontent.com/16003587/57087268-97bd5380-6cf7-11e9-9a0b-b2116a6b9a16.png)

**My parameters are:**
`startDate: startDate,  
endDate: (new Date()),
dataType: 'calories.active',
bucket: 'day',
filtered: true`

**Comment by pnag90** [comment]
After spending some time analizing the code, I see that in the "query" option the function logic is different... and working.
So, I've changed the queryAggregated function, putting the same logic with the for loop. **It's fixed!**

**Comment by afuentesdp90** [comment]
Hi I have the same problem and I can't resolve it. Any idea? Thanks

**Comment by juanico18** [comment]
@pnag90 How did you solve it? Using queryAggregated instead of Query?

**Comment by dariosalvi78** [comment]
there is a bug in the code, particularly in the JS part for Android, see issue https://github.com/dariosalvi78/cordova-plugin-health/issues/296
