### ISSUE TITLE
unknow data type - meditation

### ISSUE THREAD

**Issue by phiasco12** [dariosalvi78/cordova-plugin-health#153]
I'm trying to use this plugin but when I run my code in the app, I get the following error:

`unknow data type - meditation`

is the `mediation` data type not supported in this plugin?

I see it here: https://github.com/dariosalvi78/cordova-plugin-health/blob/HEAD/activities_map.md

Can someone please advice on this issue?

Thanks

**Comment by dariosalvi78** [comment]
no it's supported, see README for supported data types. If you are addressing iOS only you can use Telerik's plugin, which is still exposed in this one.
