### ISSUE TITLE
queryAggregated for Ios not tally with Apple Health App

### ISSUE THREAD

**Issue by ForAppDeveloper** [dariosalvi78/cordova-plugin-health#155]
I am using queryAggregated with filtered: true param in order to get "step" data from Health Kit. Everything is going smoothly and I manage to get the data. However, there is some issue where the user does not have any manual step input but the data pull from queryAggregated is not tally with what Health App Show. 

May I know what scenario or situation will cause this issue to happen?

Attach images on step show in Health App.

![healthAppDetailStep](https://user-images.githubusercontent.com/51786902/59431283-1c32e400-8e17-11e9-9796-72528765e9c1.png)
![HealthAppStep](https://user-images.githubusercontent.com/51786902/59431285-1ccb7a80-8e17-11e9-85ae-28814c8ceb73.png)

**Comment by dariosalvi78** [comment]
The filtered in healthkit does this:

```
BOOL filtered = (args[@"filtered"] != nil && [args[@"filtered"] boolValue]);
    if (filtered) {
        predicate = [NSPredicate predicateWithFormat:@"metadata.%K != YES", HKMetadataKeyWasUserEntered];
    }
```

so, if the flag is true, it seeks for steps that have not the `HKMetadataKeyWasUserEntered` set to true. This is then passed to `HKStatisticsCollectionQuery`.

That's all.

If there are any inconsistencies, I am afraid those are a due to how HealthKit treats the data (maybe a bug?).

**Comment by dariosalvi78** [comment]
any news about this issue? Can we agree that it's not the plugin's fault?

**Comment by dariosalvi78** [comment]
I'll close the issue  as there  were no new developments. Happy to reopen it if more details are provided.
