### ISSUE TITLE
plugin_not_installed error in Android

### ISSUE THREAD

**Issue by juanjoseadan** [dariosalvi78/cordova-plugin-health#156]
Hello! I'm using this plugin in Android (ionic app) and when I try to invoke the function "isAvailable" it returns an error saying: "plugin_not_installed".

I've been reading the documentation and I already have the GoogleFit plugin installed.

These are the plugins I have installed (running cordova plugin list command):

com.telerik.plugins.healthkit 0.5.6 "HealthKit"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-health 1.1.3 "Cordova Health"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.5.0 "cordova-plugin-ionic-webview"
cordova-plugin-pedometer 0.4.1 "Core Motion Pedometer"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
org.velardo.cordova-plugin-googlefit 1.2.0 "GoogleFit"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

**Comment by aerotoad** [comment]
Check if you are waiting for platform.ready before calling the plugin.
I was getting the same message until I figured out I was not waiting for the platform.ready event.

**Comment by juanjoseadan** [comment]
The plugin is running AFTER platform.ready so that is not the case. Now I made a downgrade and i'm getting an empty error when I run the same function. Any suggestion?

**Comment by dariosalvi78** [comment]
I closed the issue because it's most certainly related to your environment rather than the plugin itself.
You can try checking [this](https://stackoverflow.com/questions/48065114/why-am-i-getting-the-error-plugin-not-installed-with-the-ionic-framework-plugin) and [this](https://github.com/ionic-team/ionic-cli/issues/2424).
