### ISSUE TITLE
App crashes after successful store()

### ISSUE THREAD

**Issue by nielsjakob** [dariosalvi78/cordova-plugin-health#158]
Hello :)

I am trying to store a workout in Apple Health (I have granted all the necessary permissions - including calories).

```
var date = Date.now();
navigator.health.store({
    startDate: new Date(date - 10*1000*60),
    endDate: new Date(date),
    dataType: 'workouts',
    value: 'strength_training',
    calories: 200
}, function(success) {
    console.log('SUCCESS');
}, function(error) {
    console.log('ERROR', error);
})
```

This actually works - as in the workout appears in Apple Health. However, this also causes the App to become unresponsive (it doesn't actually close though). Also, the success/error functions are not called, the following error message is the last thing that appears in my XCode console:

```
2019-07-25 19:20:33.865125+0200 MyApp[267:5625] *** Terminating app due to uncaught exception '_HKObjectValidationFailureException', reason: 'HKQuantitySample   (2019-07-25 19:10:34 +0200 - 2019-07-25 19:20:34 +0200) requires unit of type Length. Incompatible unit: (null)'
*** First throw call stack:
(0x1d3e4698c 0x1d301f9f8 0x1d3d50bc0 0x1e60248e4 0x1e602471c 0x1e60245c4 0x1e6027de0 0x1e6029bc4 0x100a45c5c 0x100b4f6f4 0x100b50c78 0x100b58bf4 0x100b598ec 0x100b6377c 0x1d3a66114 0x1d3a68cd4)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

I believe I am running the latest versions of all the relevant components:
Plugin version: 1.1.3
Cordova version: 9.0.0 (cordova-lib@9.0.1)
XCode version: Version 10.3 (10G8)
Phone: iPhone 7 with iOS 12.4
Macbook with macOS Mojave 10.14.5 (18F132)

**Comment by dariosalvi78** [comment]
this is the same as #120 . If you provide calories, you need to provide distance too.
If you want to fix it, I would be very happy to merge a pull request. Issue #120 explains how to do it, it's actually quite simple, it just needs some time...
