### ISSUE TITLE
pounds instead of kg

### ISSUE THREAD

**Issue by desmeit** [dariosalvi78/cordova-plugin-health#159]
weight value (HKQuantityTypeIdentifierBodyMass) is storing kg. how can I store pounds instead of kg?

I know it is possible to change the unit in the health app to lbs. But how should I store the weight in this case? as kg or lbs?

**Comment by dariosalvi78** [comment]
all units are specified in the README, if it says it's Kg, then it's Kg.

**Comment by desmeit** [comment]
this means that it is not possible to define the unit to kg? Because in the readme it says only kg.

**Comment by dariosalvi78** [comment]
The health app is unrelated to how data is stored or retrieved by the plugin.
You can insert lbs in the health app and retrieve Kgs with the plugin, HealthKit does the translation for us.

**Comment by desmeit** [comment]
so I could send the weight "85" to the health app and if I health is set to lbs then it's 85 lbs and if I set health to kg then it's 85 kg?

**Comment by dariosalvi78** [comment]
If the user sets the health app to LBS and stores 85 lbs, when you retrieve the same sample from the plugin you get 38.55 Kg.
