### ISSUE TITLE
build.phonegap.com fail after update

### ISSUE THREAD

**Issue by iAdil** [dariosalvi78/cordova-plugin-health#16]
There is a new error from build.phonegap.com:

> Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-health

Attach all error log
[error-log.txt](https://github.com/dariosalvi78/cordova-plugin-health/files/515906/error-log.txt)

**Comment by dariosalviwork** [comment]
Some activities like HKWorkoutActivityTypeDance were introduced in the latest update of HealthKit (see dd50e9783c8ae228a0bc009a02dd41b61a38df9e ).
You (or better said, phonegap) is using an older version of the xcode which does not support those.
You need to wait until it's updated, or compile the app yourself, or remove those new fields manually.

**Comment by iAdil** [comment]
Ok, till will use 0.6.2 version
