### ISSUE TITLE
Execution failed for task ':app:processDebugResources'. > Failed to execute aapt

### ISSUE THREAD

**Issue by desmeit** [dariosalvi78/cordova-plugin-health#160]
I work with your plugin (version 1.1.0) since last year. It was working properly the whole time.
Now I want to compile my app again and I get the following error:

```
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
```

After deinstalling the health plugin it is compiling successful.
What could be the reason? I changed nothing.

What could be the reason? Is there a way to continue working with 1.1.0 (because I made some changes and everything was working perfect so far.)

Thanks

**Comment by dariosalvi78** [comment]
you probably need to update your environment:

https://stackoverflow.com/questions/20737200/execution-failed-appprocessdebugresources-android-studio

if you want to use an older version of the plugin: https://60devs.com/npm-install-specific-version.html

**Comment by desmeit** [comment]
but then I'm wondering why with the version 1.1.3 it is working.
what did you change in this version?

**Comment by dariosalvi78** [comment]
see the changelog: https://github.com/dariosalvi78/cordova-plugin-health/blob/master/CHANGELOG.md

What is probably affecting you is that the google apis are now fixed to 16.0.1. If you need to use another version see the README under Android requirements, but I'd suggest you update your development environment.

**Comment by dariosalvi78** [comment]
BTW, if anyone has tested the plugin with a more recent version of the APIs I will be very happy to update the dependency here too.
Looks like we are at version 17.0.0 now.

**Comment by desmeit** [comment]
okay thanks
