### ISSUE TITLE
User cancelled the dialog error only in Play Store

### ISSUE THREAD

**Issue by juanjoseadan** [dariosalvi78/cordova-plugin-health#161]
Hello, we are running in a very critical problem with an app we made that integrates this plugin.

We did read the documentation many times, did all the config stuff in Google API's and OAuth, everything is fine so far. Even Google approved our consent screen a few hours ago (it was our last option) but we are not able to use Google Fit data when the app is downloaded from the Play Store.

The error we are getting is "User cancelled the dialog" after the plugin asks to select an account.

If our users install the app from an .apk file it works perfectly.

Can someone help me to figure out if there's any other reason why this is not working in Play Store?

I would like to know if someone already published an app with Google Fit integration.

Thanks!

**Comment by uncedric** [comment]
I'm having the same issue :(

**Comment by juanjoseadan** [comment]
To anyone that might be having this issue in Play Store, here is a link that will help you fix it quickly: https://stackoverflow.com/questions/37289028/google-oauth-2-0-result-canceled-while-using-google-fit-api

**Comment by dariosalvi78** [comment]
I understand you solved this?
Besides, it's not a plugin problem.
