### ISSUE TITLE
Callback not called when distance is not present on IOS

### ISSUE THREAD

**Issue by iBoonz** [dariosalvi78/cordova-plugin-health#164]
Hi, 

For some iOS users the query for distance is never resolving 
```

      let distanceQueryPromise: Promise<HealthData[]> = this.health.query({
            startDate: start, endDate: end, dataType: 'distance', limit: 1000000
          });
```

Then we resolve all the other queries: 

`  Promise.all([activityQueryPromise, heartrateQueryPromise, distanceQueryPromise]).then((values: any) => {});`

But for some users, who only register activities with heartrate and activity, there is no distance. The promise is never resolved. 

Is this intended behaviour? 

Thanks!

**Comment by dariosalvi78** [comment]
I have just tried this on my iPhone with no distance set as of today and the callback is called.
This is my test code:

```
navigator.health.query({
startDate: new Date(new Date().getTime() - 5 * 60 * 1000), // 5 minutes ago
endDate: new Date(),
dataType: 'distance',
limit: 1000000
}, function(data){ console.log(data)}, function (err) { console.error(err)})
```
