### ISSUE TITLE
How to get sleep andoird and ios

### ISSUE THREAD

**Issue by methineeinkan** [dariosalvi78/cordova-plugin-health#165]
navigator.health.query({
            startDate: new Date(new Date().getTime() - 365 * 24 * 60 * 60 * 1000), // three days ago
            endDate: new Date(), // now
            dataType: 'sleep',
        }, function(data) {
            alert(JSON.stringify(data));
        }, function(error) {
            alert(JSON.stringify(error));
        })
but notwork TT

**Comment by dariosalvi78** [comment]
you need to query activity. Check the README.

**Comment by methineeinkan** [comment]
not working

**Comment by methineeinkan** [comment]
dataType: 'activity' 
not data sleep.light sleep.deep sleep.rem
