### ISSUE TITLE
[Android] requestAuthorization() asks for all(?) permissions, not just the ones specified in "datatypes"

### ISSUE THREAD

**Issue by nijakobius** [dariosalvi78/cordova-plugin-health#166]
When I call `navigator.health.requestAuthorization(['weight']);` I would expect the Android dialogue to ask for permission for bodyweight data only.

Instead, I get the following dialogue:
> This app wants permission to see and add your body measurement, such as your:
> - Heart rate (...)
> - Weight (...)
> - Body fat percentage
> - Waist/hip circumference

Is it not possible to ask for only some of the available permissions on Android?

(The same code works as expected on iOS)

**Comment by dariosalvi78** [comment]
that's how permissions used to work in the FIT API, they are grouped in categories (they call them scopes).

I am checking the latest version of [their documentation](https://developers.google.com/fit/android/get-started) and it looks like they have added a more granular approach now, but I don't know if they actually ask access for each one of the datatypes as in HealthKit. Worth trying.

Any volunteer?

**Comment by dariosalvi78** [comment]
I hope I will have some time to try this out, it's more transparent towards the user. I'll update this issue and you'll probably get to know what happened...

**Comment by dariosalvi78** [comment]
scopes have been abandoned quite some time ago, permissions should be now granular
