### ISSUE TITLE
iOS 13 does not seem to be compatible with this plugin.

### ISSUE THREAD

**Issue by abowerman** [dariosalvi78/cordova-plugin-health#168]
I'm struggling to get this plugin to work on iOS 13, iOS 12 works exactly as it should. Is anyone else having this issue?

**Comment by dariosalvi78** [comment]
haven't tried yet on iOS13. Any indication of why it is happening?

**Comment by abowerman** [comment]
Sorry, I can't provide logs at the moment, I'll be able to at the end of the week. 

After updating our app to iOS 13, I get a permissions dialog just as before update. but am not getting any data. Using the same app on iOS 12 works just fine. I'll be able to provide detail soon.

**Comment by Bonoai** [comment]
I don't have any logs either atm, but this plugin just stopped working 1-2 weeks ago. It will ask permissions, but albeit I have set several datatypes, it asks permission only for height. All determined datatypes are however turned on when I go to settings and check them there. 

There are some issues on data fetch also and after few tests, it seems to work randomly. It will fetch data, but only partially. Will test more, but it seems that iOS 13 breaks this for sure.

**Comment by dariosalvi78** [comment]
strangely I am not seeing anything happening on [the original repository](https://github.com/EddyVerbruggen/HealthKit) I based this on, nor on [any fork](https://github.com/EddyVerbruggen/HealthKit/network).
I am not an iOS developer, so I'll probably need help with this.

**Comment by Bonoai** [comment]
I want to clarify that it still works great on Android and fetches all the data like planned. 

What comes to iOS, we have tested it now with 13.1.2 and 13.1.3 versions and neither are working properly. So probably either of those versions or 13.1.1 causes this unstableness. Dunno.

**Comment by ajincentfit** [comment]
I am getting user complaints rolling in too. Anyone have any luck with any of the forks of this that can be a drop-in replacement?

**Comment by Bonoai** [comment]
I dunno. It is still buggy when asking permissions, but after I redid my own parser, all data is fetched now almost as planned; only sleep data is behaving strangely. I don't know if this was a feature/bug in the beginning, but aggregated data fetch won't bucket sleep data. I am taking multiple naps per day and it only fetches the first sleep data point. If I am using normal query, it will fetch everything. 

Now using iOS 13.2.3

**Comment by dariosalvi78** [comment]
are you still having problems with iOS 13? Or can I close this issue?

**Comment by abowerman** [comment]
I'm no longer using this library, I've not tested it in a while.

**Comment by dariosalvi78** [comment]
ok,  it's working on iOS13 as far as I know
