### ISSUE TITLE
Determine device source?

### ISSUE THREAD

**Issue by gotters** [dariosalvi78/cordova-plugin-health#169]
I am capturing Blood Pressure data via Google Fit (and ultimatly health kit also). Is there a way to determine the source of the data. For eg a user can manually just enter blood pressure data into google fit which will then be collected via this plugin. I would like to know if that google fit BP data was entered manually or was recorded by a device?

**Comment by dariosalvi78** [comment]
from the readme:

- sourceBundleId: {type: String} the identifier of the app that produced the data
- sourceName: {type: String} the name of the app that produced the data (as it appears to the user)
