### ISSUE TITLE
Support queries for nutrition (dietary/food) data types in Google Fit

### ISSUE THREAD

**Issue by sgilroy** [dariosalvi78/cordova-plugin-health#17]
We are currently using the Telerik HealthKit plugin to get nutrition data types from HealthKit. The cordova-plugin-health plugin does not (yet) support this.

To get nutrition data from Google Fit, query for `DataType.TYPE_NUTRITION`. For each data point, nutrients can be retrieved via `datapoint.getValue(Field.FIELD_NUTRIENTS)` and then specifiec nutrients can be retrieved via `nutrients.getKeyValue(Field.NUTRIENT_TOTAL_CARBS)`.

Documentation on `Field.FIELD_NUTRIENTS`:
https://developers.google.com/android/reference/com/google/android/gms/fitness/data/Field.html#FIELD_NUTRIENTS

List of nutrients (constants prefixed with `NUTRIENT_`):
https://developers.google.com/android/reference/com/google/android/gms/fitness/data/Field#constant-summary

Tasks:
 - [x] include all nutrient types in `nutritiondatatypes`
 - [x] support retrieving samples for each nutrient type in `query()` with appropriate unit value for each type
 - [x] support aggregated queries for each nutrient type in `queryAggregated()`

Eventually, support should also be added for mapping and querying the equivalent data types in HealthKit (see [this list for reference](https://developer.apple.com/reference/healthkit/1627060-healthkit_constants/1664847-nutrition_identifiers?language=objc)). However, I don't personally need HealthKit support at the moment, so I will start with just the Google Fit side.

**Comment by dariosalviwork** [comment]
Thanks very much for working on this.

I have a question about Telerik's plugin:
I merged their repo with mine on Sept. 27 2016. It may already work with the nutrition quantity samples, or am I missing something?

In the future, it would be nice to have a "nutrition" datatype that returns all the known nutrients of a given sample (or aggregated) in an object (eg { fat.total: 50, cholesterol: 0.03 }), but that would probably be more difficult to implement with HealthKit.

**Comment by dariosalvi78** [comment]
Is this also working on the iOS part?
In that case I can prepare a release.

**Comment by sgilroy** [comment]
@dariosalviwork I suspect that the nutrition samples could be queried via the separate HealthKit API (we are doing this using the Telerik plugin itself) but not via the health plugin API using the platform-agnostic type identifiers.

Telerik healthkit plugin:
```
window.plugins.healthkit.querySampleType(
  {
    'startDate' : new Date(new Date().getTime()-2*24*60*60*1000), // two days ago
    'endDate'   : new Date(), // now
    'sampleType': 'HKQuantityTypeIdentifierDietarySugar',
    'unit'      : 'g'
  },
  onSuccess,
  onError
);
```

cordova-plugin-health
```
window.navigator.health.query(
  {
    'startDate' : new Date(new Date().getTime()-2*24*60*60*1000), // two days ago
    'endDate'   : new Date(), // now
    'dataType': 'nutrition.sugar',
    'unit'      : 'g'
  },
  onSuccess,
  onError
);
```

So there are multiple outstanding issues:
 1. translate from the nutrition data types, such as "nutrition.sugar" to the HealthKit sample types, such as "HKQuantityTypeIdentifierDietarySugar"
 2. correlation queries, including support for a "nutrion" correlation

**Comment by dariosalvi78** [comment]
the health plugin uses the teleriks' plugin. AFAIK they are completely in sync, so there should be no missing features.

1: that's easy enough, I can do that 
2: not sure why we would need this. As far as I have seen, the Android part only queries for specific substances

what about aggregated values, have you tried with Telerik's plugin?

**Comment by sgilroy** [comment]
Yes, we are using the Telerik plugin for aggregated values (by day) via `window.plugins.healthkit.querySampleTypeAggregated()`.

As for the correlation queries, Google Fit does not actually allow individual nutrients (substances) to be queried directly. It only supports queries for `DataType.TYPE_NUTRITION` and returns data points with all of the available nutrient fields. I implemented the query in the plugin to pull out the appropriate field (such as `Field.NUTRIENT_SUGAR`) and return just that one value. A correlation query should be fairly straight forward to implement in Google Fit, and can be done in a way that matches up closely to the `window.plugins.healthkit.queryCorrelationType()` from the Telerik plugin.

**Comment by dariosalviwork** [comment]
I have extended your work, now nutrition is supported with the same interface on both Fit and HK. I have also added the data type "nutrition" that computes a summary of all known nutrients.

Still to be done: store() of nutrients.
