### ISSUE TITLE
Not getting consent popup.

### ISSUE THREAD

**Issue by Green-Robot-Dev-Studios** [dariosalvi78/cordova-plugin-health#172]
**When I launch my app and run the sample code, I get asked what account I want and no consent page. I am building for android.**
I think there is an issue with how I installed this plugin.

- I am using capacitor but [ionic docs ](https://ionicframework.com/docs/native/health) had a tab for it so I think that should be fine.

- I installed google services to android studio.

- I got an API key for fitness and synced it with my keystore

When I actually launch the app in my phone and look at the logs, I get 
`Connection to Fit failed, cause: null`
and then an attempt at reconnecting that also fails.

My code is:
```
  constructor(private health: Health) {}
  printer : string = 'nothing yet...';
  ngOnInit() {
    this.health.isAvailable()
    .then((available:boolean) => {
      console.log(available);
      this.health.requestAuthorization([
        'distance', 'nutrition',  //read and write permissions
        {
          read: ['steps'],       //read only permission
          write: ['height', 'weight']  //write only permission
        }
      ])
      .then(res => console.log(res))
      .catch(e => console.log(e));
    })
    .catch(e => console.log(e));
  }
```

**Comment by dariosalvi78** [comment]
looks like something going wrong with the authorization process. I suggest you re start all the process of getting API key, using your signing SHA key etc. from the scratch. Sometimes it helps.

**Comment by Green-Robot-Dev-Studios** [comment]
What should be put for Authorized domains when making the consent screen?

**Comment by Green-Robot-Dev-Studios** [comment]
Fixed! I just re-did the entire signing process. As for Authorized domains: the default works. And for anyone in the future, capacitor works for this plugin.

**Comment by dariosalvi78** [comment]
thanks.
