### ISSUE TITLE
IOS StartDate problem (any version of ios).

### ISSUE THREAD

**Issue by AlonsoFon** [dariosalvi78/cordova-plugin-health#175]
Hello, im using the example of read me:  "startDate: new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000)" on health.queryAggregated and health.query both got the same problem. When i do the query, promise return with error: "startDate must be a JavaScript Date Object". Android any version works fine, but ios any version return me this error. Im using plugin version 1.1.4 on ionic 4, tried with moment to get date and returns same error.

**Comment by dariosalvi78** [comment]
I am using the plugin regularly and I don't get this error. Maybe there's a bug somewhere in your code?

**Comment by AlonsoFon** [comment]
Im dont see how can be bug on my code, im using read me example and works fine on android.

look the code:

var queryOptions = {
        startDate: new Date(new Date().getTime() - 30 * 24 * 60 * 60 * 1000), 
	endDate: new Date(), // now
	dataType: 'steps',
	bucket: 'day',
	limit: 1000
};
this.health.queryAggregated(queryOptions).then( (resSteps) =>{
       console.log(resSteps);
});

**Comment by dariosalvi78** [comment]
looks like you are using the Ionic wrapper for this plugin. Try executing the query in a console calling the plugin directly "navigator.health". If there are issues in the wrapper I am not responsible for those.

**Comment by AlonsoFon** [comment]
ok i will test, ty for help.

**Comment by dariosalvi78** [comment]
did you solve the issue?

**Comment by dariosalvi78** [comment]
closing this issue for lack of more feedback
