### ISSUE TITLE
Problem accessing mindfulness minutes, need suggestions

### ISSUE THREAD

**Issue by trifroggy** [dariosalvi78/cordova-plugin-health#179]
Hello,
I'm running into a vexing case trying to read the mindfulness minutes. 
+ iOS 13.4.1
+ I am accessing the mindfulness entries BUT they have neither value nor unit
Here is an example:
{"id":"XXXXXXXXXX","startDate":"2020-06-18T14:33:53.000Z","endDate":"2020-06-18T14:44:43.000Z","sourceName":"WHM","sourceBundleId":"mobapp.at.Innerfire"}

Would someone have run into a similar scenario in the past and can give me some debugging suggestions?
The data is stored in Health and the proper phone authorizations are set.  

And it only does this on the "mindfulness minutes" records.

Thanks for any suggestions!
Gregory

**Comment by dariosalvi78** [comment]
No bug here,  you get  the duration from the timestamps. That's all. See [here](https://developer.apple.com/documentation/healthkit/hkcategorytypeidentifiermindfulsession?language=objc).

**Comment by trifroggy** [comment]
Thank you so much, missed that one.  Enjoy the weekend!
