### ISSUE TITLE
error Datatype heart_rate not supported

### ISSUE THREAD

**Issue by anshu300** [dariosalvi78/cordova-plugin-health#182]
navigator.health.queryAggregated({
  startDate: new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000), // three days ago
  endDate: new Date(), // now
  dataType: 'heart_rate',
  bucket: 'day'
}, successCallback, errorCallback)

showing error Datatype heart_rate not supported

**Comment by dariosalvi78** [comment]
as per README, heart_rate is not supported in queryAggregated(), only in query()

**Comment by anshu300** [comment]
this.health.query({
      startDate:new Date('07-01-2020'),
      endDate: new Date(), // now
      dataType: 'heart_rate.resting',
    }).then(data => {
      console.log('heart_rate.resting', data);

      //this.do(data);
    }).catch(e => {
      console.log("error " + e);
    });



    this.health.query({
      startDate:new Date('07-01-2020'),
      endDate: new Date(), // now
      dataType: 'resp_rate',
    }).then(data => {
      console.log('resp_rate', data);

      //this.do(data);
    }).catch(e => {
      console.log("error " + e);
    });
error Datatype resp_rate not supported
error Datatype heart_rate.resting not supported

**Comment by anshu300** [comment]
as per README, heart_rate is not supported in queryAggregated(), only in query()

thank you sir its solve

**Comment by dariosalvi78** [comment]
heart_rate.resting and resp_rate only work on iOS. Please check the README carefully.

**Comment by anshu300** [comment]
thank you a lot of sir
