### ISSUE TITLE
Can not write blood_pressure for Google fit. My android app.

### ISSUE THREAD

**Issue by skyus** [dariosalvi78/cordova-plugin-health#183]
Development
Xcode 11.5
ionic 4
android.

Permissions currently allowed by Fit
Read/write permissions for MY apps include heart_rate and blood_pressure.
Both heart_rate and blood_pressure can be read by query
heart_rate can be written to fit at xxx = 60, but it can not be written for blood_pressure.
The error response at that time is'console.error: err null'

let xxx = JSON.parse(JSON.stringify({
      diastolic: 120 ,
      systolic: 80
 }))

this.health.store({
      startDate: new Date(),
      endDate: new Date(),
      dataType: 'blood_pressure',
      value: xxx,
      sourceName: 'myapp',
      sourceBundleId: 'net.myapp',
    }).then(success => {
      console.log('success ok' + JSON.stringify(success));
     }, err => {
       console.error('err ' + err);
     });

**Comment by dariosalvi78** [comment]
you need to ask permission to Google (the company, not just the API) to store health data

**Comment by skyus** [comment]
Thanks for your replay.

That link write.
---------- 
Note: Google has temporarily stopped taking new requests to write to restricted data types. We are updating our policy and process for reviewing requests and will update this documentation again when we resume.
-----------

Is it better to understand that the current suspension means that we cannot take it now?
Did you mean you could get it in the past?

**Comment by dariosalvi78** [comment]
I have been authorised in the past.
