### ISSUE TITLE
[iOS] Saving workout with calories crashes my app

### ISSUE THREAD

**Issue by nielsjakob** [dariosalvi78/cordova-plugin-health#184]
I am using the following to save a workout to AppleHealth:

```
navigator.health.store({
    startDate: new Date(Date.now() - 1000*60*60),
    endDate: new Date(Date.now()),
    dataType: 'workouts',
    value: 'strength_training',
    calories: 300
});
```

This causes my app to become **unresponsive** with XCode showing the following:

> *** Terminating app due to uncaught exception '_HKObjectValidationFailureException', reason: 'HKCumulativeQuantitySample   (2020-08-07 17:41:11 +0200 - 2020-08-07 18:08:11 +0200) requires unit of type Length. Incompatible unit: (null)'
> *** First throw call stack:
> (0x187265654 0x186f87bcc 0x18715ba58 0x19a8f3b30 0x19a8f3960 0x19a8f382c 0x19a8f679c 0x19a8f76e4 0x100f9a288 0x1013ea338 0x1013eb730 0x1013f2740 0x1013f3314 0x1013fe6c4 0x186f7cb74 0x186f7f740)
> libc++abi.dylib: terminating with uncaught exception of type NSException

The weird thing is that the workout shows up in AppleHealth perfectly, **including the calories**. If I query for the workout, it returns:

```
{
    "id": "22A40DE0-ED22-408A-B695-0C776251E805",
    "startDate": "STARTDATE",
    "endDate": "ENDDATE",
    "value": "strength_training",
    "unit": "activityType",
    "calories": 300,
    "distance": 0,
    "sourceName": "APPNAME",
    "sourceBundleId": "BUNDLEID"
}
```

Adding `"unit":"activityType"`, `"unit":"activitySummary"` or `"unit":"kcal"` to `store()` doesn't help, unfortunely. Also, I am fairly sure that the exact same code was working up until recently.

Any ideas what's going on? 

-------------------------------
cordova-plugin-health 1.1.5 (problem exists with 1.1.3)
iPhone X with iOS 13.6
XCode 11.6 (11E708)
Cordova 10.0.0 (problem exists with 9.0.0)
Cordova ios ^6.1.0 (problem exists with 5.1.1)

**Comment by dariosalvi78** [comment]
it's probably the same as #120. Quite easy to fix it actually, I'd be very happy to receive a PR.
