### ISSUE TITLE
Can't store water, "volume not set"

### ISSUE THREAD

**Issue by MichaelSolati** [dariosalvi78/cordova-plugin-health#185]
Below is an example of a data object that I am trying to pass into the `store` method, 

```JS
{
  startDate: new Date(),
  endDate: new Date(), // I don't use the same dates, just using this as a placeholder
  dataType: 'nutrition.water',
  value: '64',
  sourceName: 'MyAppName',
  sourceBundleId: 'com.app.my',
}
```

Which seems to match the expected data structure. However, I'm getting the error message, `volume not set`.

I'm not sure if I'm missing something here?

**Comment by dariosalvi78** [comment]
hi, there may be a bug, I am not sure. Can you confirm this is still happening?

**Comment by MichaelSolati** [comment]
Hey, sorry for the delay. So I'm running version `1.1.5` of the package and am still getting the same error.
