### ISSUE TITLE
Config.xml breaks with code from readme

### ISSUE THREAD

**Issue by crystalnet** [dariosalvi78/cordova-plugin-health#186]
Hey guys,
the README suggest to include the following lines in ```config.xml```.
```
<!-- Read access -->
<config-file platform="ios" parent="NSHealthShareUsageDescription">
  <string>App needs read access</string>
</config-file>
<!-- Write access -->
<config-file platform="ios" parent="NSHealthUpdateUsageDescription">
  <string>App needs write access</string>
</config-file>
```

However, this code breaks my builds, resulting in the following error for ```ionic cordova build ios/android```:
```
config file undefined requested for changes not fount at /Users/konsti/Projects/MoveIt/platforms/ios/undefined, ignoring
config file undefined requested for changes not fount at /Users/konsti/Projects/MoveIt/platforms/ios/undefined, ignoring
The "path" argument must be of type string, received undefined.
```

The case above is for ios, but his happens for android as well. The problems disappears, if I remove those lines.
I'm using 
- Ionic 6.11.8
- Cordova 10.0.0
- cordova-plugin-health ^1.1.5

Let me know if you need more info.

Thanks for your replies.

**Comment by dariosalvi78** [comment]
I don't use Phonegap so can't help. Have you fixed it anyhow? Is there anything we should write on the README?

**Comment by dariosalvi78** [comment]
I am not experiencing this issue on my latest tests. Can you confirm it has been solved?
