### ISSUE TITLE
TypeError: Object(...) is not a function 

### ISSUE THREAD

**Issue by azzaGarsaa** [dariosalvi78/cordova-plugin-health#187]
hello everyone, i hope you can help me , i'm having this error after installing cordova-plugin-health, in my ionic project
vendor.js:2085 ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
at Health.isAvailable (vendor.js:81074)
at new HomePage (main.js:172)

i did exactly like the doc: 
this.health.isAvailable()
.then((available:boolean) => {
console.log(available);
this.health.requestAuthorization([
'distance', 'nutrition', //read and write permissions
{
read: ['steps'], //read only permission
write: ['height', 'weight'] //write only permission
}
])

**Comment by dariosalvi78** [comment]
Have you found the problem with this? To me it looks like it's not a problem related to the plugin

**Comment by dariosalvi78** [comment]
I'll close this issue as it is probably a bug in your code rather then the plugin
