### ISSUE TITLE
[IOS] - Wrong steps count

### ISSUE THREAD

**Issue by IhorKarpiuk** [dariosalvi78/cordova-plugin-health#189]
Hello, sometimes we get wrong data from HealthKit when call `(window as any).plugins.health.query(options)`
It is only IOS problem (we use IOS 14.0.1). For android it`s work fine.
this problem is reproduced only for certain dates (Differenly on each devices)
![image](https://user-images.githubusercontent.com/61740683/97010841-9d8fa000-154e-11eb-97c4-5e75f2ca96d0.png)

we are using:
Cordova 10.0.0
cordova-plugin-health ^1.1.5

**Comment by dariosalvi78** [comment]
try with the `filtered` flag set to true. Related (and probably the same as) to #155 .

**Comment by dariosalvi78** [comment]
closing because no reply given and suspected duplicate.

**Comment by IhorKarpiuk** [comment]
Hello, thanks for the answer, but it not working. Regardless of value `filtered` we get the wrong result

**Comment by dariosalvi78** [comment]
I don't think I'm able to help, I don't think it's an issue of the plugin, it's probably related to how data is processed in HK. If you are interested in the sum of the steps, you should probably do an aggregated query instead.
Be aware that some developers experienced issues with strange timestamps when their users changed timezone.
