### ISSUE TITLE
separate activity from sleep

### ISSUE THREAD

**Issue by dariosalvi78** [dariosalvi78/cordova-plugin-health#191]
Google Fit [has decided to split sleep from activity](https://developers.google.com/fit/improvements#separate_scopes_and_new_data_type_for_sleep) as it is done in HealthKit. This would allow a better API and remove some of the quirks introduce in this plugin like asking permission for workouts and sleep.
 
This needs some work and I'm busy. Any volunteer?

**Comment by dariosalvi78** [comment]
useful links:

https://developers.google.com/fit/android/releases#october_19_2020

https://developers.google.com/fit/scenarios/read-sleep-data

https://developers.google.com/android/reference/com/google/android/gms/fitness/data/SleepStages

**Comment by mschristo** [comment]
Hello @dariosalvi78!

Maybe this issue relates to my pull request #219?

**Comment by dariosalvi78** [comment]
I haven't closed this yet because I still need to test the code, but the plan is to close it after I have confirmed everything works as expected. I also need to separate sleep from activity in iOS (unless you want to help with that!).

**Comment by mschristo** [comment]
That's ok! 

In case you find out that something is not working as expected, please do not hesitate to contact me! I would be happy to help! 

Sadly I am not familiar with Objective-C to help you with the iOS part...

**Comment by dariosalvi78** [comment]
actually the iOS part only requires work on the JS "glue". If you look at the health.js code you can see that activity now queries both workouts and sleep. This was done because Google Fit had them combined, but now they can be separated. Check the code and see if you feel like you're able to do it, shouldn't be hard ;)

**Comment by mschristo** [comment]
Ok, I will give it a try!

**Comment by dariosalvi78** [comment]
this is now fixed in release 2.1.0
