### ISSUE TITLE
Build failed with version 2.0.0

### ISSUE THREAD

**Issue by mmelnyk-ua** [dariosalvi78/cordova-plugin-health#192]
![Screenshot at Dec 01 14-51-02](https://user-images.githubusercontent.com/71463872/100743411-ee63a580-33e4-11eb-80e2-67bfbf035d1d.png)

/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:906: error: no suitable method found for aggregate(DataType)
            builder.aggregate(DataType.TYPE_DISTANCE_DELTA);
                   ^
    method Builder.aggregate(DataSource,DataType) is not applicable
      (actual and formal argument lists differ in length)
    method Builder.aggregate(DataType,DataType) is not applicable
      (actual and formal argument lists differ in length)
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:908: error: no suitable method found for aggregate(DataType)
            builder.aggregate(DataType.TYPE_CALORIES_EXPENDED);
                   ^
    method Builder.aggregate(DataSource,DataType) is not applicable
      (actual and formal argument lists differ in length)
    method Builder.aggregate(DataType,DataType) is not applicable
      (actual and formal argument lists differ in length)
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:910: error: no suitable method found for aggregate(DataType)
            builder.aggregate(DataType.TYPE_BASAL_METABOLIC_RATE);
                   ^
    method Builder.aggregate(DataSource,DataType) is not applicable
      (actual and formal argument lists differ in length)
    method Builder.aggregate(DataType,DataType) is not applicable
      (actual and formal argument lists differ in length)
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:912: error: no suitable method found for aggregate(DataType)
            builder.aggregate(DataType.TYPE_ACTIVITY_SEGMENT);
                   ^
    method Builder.aggregate(DataSource,DataType) is not applicable
      (actual and formal argument lists differ in length)
    method Builder.aggregate(DataType,DataType) is not applicable
      (actual and formal argument lists differ in length)
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:914: error: no suitable method found for aggregate(DataType)
            builder.aggregate(DataType.TYPE_HYDRATION);
                   ^
    method Builder.aggregate(DataSource,DataType) is not applicable
      (actual and formal argument lists differ in length)
    method Builder.aggregate(DataType,DataType) is not applicable
      (actual and formal argument lists differ in length)
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:916: error: no suitable method found for aggregate(DataType)
            builder.aggregate(DataType.TYPE_NUTRITION);
                   ^
    method Builder.aggregate(DataSource,DataType) is not applicable
      (actual and formal argument lists differ in length)
    method Builder.aggregate(DataType,DataType) is not applicable
      (actual and formal argument lists differ in length)
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:1135: error: no suitable method found for aggregate(DataType)
                .aggregate(DataType.TYPE_DISTANCE_DELTA)
                ^
    method Builder.aggregate(DataSource,DataType) is not applicable
      (actual and formal argument lists differ in length)
    method Builder.aggregate(DataType,DataType) is not applicable
      (actual and formal argument lists differ in length)
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:1195: error: no suitable method found for aggregate(DataType)
        builder.aggregate(DataType.TYPE_BASAL_METABOLIC_RATE);
               ^
    method Builder.aggregate(DataSource,DataType) is not applicable
      (actual and formal argument lists differ in length)
    method Builder.aggregate(DataType,DataType) is not applicable
      (actual and formal argument lists differ in length)
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:1270: error: cannot find symbol
        DataSet.Builder dataSetBuilder = DataSet.builder(datasrc);
               ^
  symbol:   class Builder
  location: class DataSet
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:1270: error: cannot find symbol
        DataSet.Builder dataSetBuilder = DataSet.builder(datasrc);
                                                ^
  symbol:   method builder(DataSource)
  location: class DataSet
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:1271: error: cannot find symbol
        DataPoint.Builder datapointBuilder = DataPoint.builder(datasrc);
                 ^
  symbol:   class Builder
  location: class DataPoint
/Users/michael/Projects/freelance/sivak/wowijs/platforms/android/app/src/main/java/org/apache/cordova/health/HealthPlugin.java:1271: error: cannot find symbol
        DataPoint.Builder datapointBuilder = DataPoint.builder(datasrc);
                                                      ^
  symbol:   method builder(DataSource)
  location: class DataPoint
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
23 actionable tasks: 4 executed, 19 up-to-date
Command failed with exit code 1: /Users/michael/Projects/freelance/sivak/wowijs/platforms/android/gradlew cdvBuildDebug -b /Users/michael/Projects/freelance/sivak/wowijs/platforms/android/build.gradle
Error: Command failed with exit code 1: /Users/michael/Projects/freelance/sivak/wowijs/platforms/android/gradlew cdvBuildDebug -b /Users/michael/Projects/freelance/sivak/wowijs/platforms/android/build.gradle
    at makeError (/Users/michael/Projects/freelance/sivak/wowijs/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/michael/Projects/freelance/sivak/wowijs/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
[ERROR] An error occurred while running subprocess cordova.

**Comment by dariosalvi78** [comment]
some information about the environment would help, like version of the plugin, if it's cordova or phonegap etc.
in any case it looks that the environment is not well setup, you are probably using an old version of the Service APIs

**Comment by mmelnyk-ua** [comment]
> some information about the environment would help, like version of the plugin, if it's cordova or phonegap etc.
> in any case it looks that the environment is not well setup, you are probably using an old version of the Service APIs

@dariosalvi78 thanks for answer
I am using ionic cordova
cordova-android 9.0.0
my packages:
```
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebasex 11.0.3 "Google Firebase Plugin"
cordova-plugin-health 2.0.0 "Cordova Health"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.4.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version
```

**Comment by dariosalvi78** [comment]
I see that you use `cordova-android-play-services-gradle-release`, so it's likely due to using an older version the Google APIs. Version n 2 of this plugin uses the latest APIs and is not compatible with older versions because of breaking changes in the Google APIs.
You can try making sure all plugins use the latest versions of the Google APIs or by using and older versions of this plugin.

**Comment by mmelnyk-ua** [comment]
> I see that you use `cordova-android-play-services-gradle-release`, so it's likely due to using an older version the Google APIs. Version n 2 of this plugin uses the latest APIs and is not compatible with older versions because of breaking changes in the Google APIs.
> You can try making sure all plugins use the latest versions of the Google APIs or by using and older versions of this plugin.

I tried to update cordova-plugin-health to version 2 because my application stop works with previous version and I always see error "User cancelled the dialog". But it worked 2 month ago but 1 month ago it stopped

**Comment by dariosalvi78** [comment]
User cancelled the dialog is likely to happen because you have not setup the keys correctly on the Google developer console. Going to close this issue as probably unrelated to the plugin.

**Comment by mmelnyk-ua** [comment]
> User cancelled the dialog is likely to happen because you have not setup the keys correctly on the Google developer console. Going to close this issue as probably unrelated to the plugin.

Do you mean that it can't be related to library upgrade? only keys issue?

**Comment by mmelnyk-ua** [comment]
@dariosalvi78  ^^

**Comment by dariosalvi78** [comment]
"User cancelled the dialog" is probably due to keys issue.
Compilation problem is due to new version of plugin /  APIs.
Revert to old plugin and fix the keys issue.

**Comment by mmelnyk-ua** [comment]
> "User cancelled the dialog" is probably due to keys issue.
> Compilation problem is due to new version of plugin / APIs.
> Revert to old plugin and fix the keys issue.

How is it possible that it just stopped working in some time?

**Comment by mmelnyk-ua** [comment]
> "User cancelled the dialog" is probably due to keys issue.
> Compilation problem is due to new version of plugin / APIs.
> Revert to old plugin and fix the keys issue.

@dariosalvi78 I just checked and all work with debug version and it is not working with production
I checked SHA keys and all data are correct

DO you have any reasons why it is not working for production?
