### ISSUE TITLE
Null object reference error on Android when authorizing for calories.active

### ISSUE THREAD

**Issue by wongpeiyi** [dariosalvi78/cordova-plugin-health#194]
Getting error message on Android only

```
Attempt to invoke virtual method 'java.lang.String com.google.android.gms.fitness.data.DataType.zzm()' on a null object reference
```

when running:

```js
navigator.health.requestAuthorization(['calories.active'], () => {}, (e) => console.error(e))
```

It doesn't happen when authorizing for just calories or basal:
```js
navigator.health.requestAuthorization(['calories', 'calories.basal'], () => console.log('ok'), (e) => console.error(e))
// ok
```

I suppose I could manually calculate active using the other two, but would be great if anyone knows what is happening here

**Comment by forno** [comment]
I got same error with "birth_of_date" or "gender" on requestAuthorization.
They are invoke this issue too.

**Comment by dariosalvi78** [comment]
I have removed `date_of_birth` and `gender` from Android in the latest version of the plugin because they were not share

**Comment by forno** [comment]
@dariosalvi78 Thank you for your information.
I remove them on my app, then working now.

**Comment by wongpeiyi** [comment]
@dariosalvi78 do you have comments on the original issue or do you require more information?

**Comment by dariosalvi78** [comment]
@wongpeiyi I still need to look into it. There may be a bug somewhere in the java code. Happy to receive pull requests if you manage to spot it before I do!

**Comment by fdmartins** [comment]
Hi, has a little mess and a bug in android/healthy.js

datatype calories.active not exists for android, this is calculed using basal calories and total calories. So, you need request permission for 'calories.basal',  'calories'... and NOT for 'calories.active' (you need use a conditional for ios version..)

for queryAggregated you can use 'calories.active' for both OS versions.

In healthy.js you need insert retval = retval[0]; in line 99, check code below:

`      opts.dataType ='calories';
      navigator.health.queryAggregated(opts, function(retval){
        //and remove the basal
        **retval = retval[0];  //<<<< INSERT THIS LINE**
        
        retval.value -= basal_ms * (retval.endDate.getTime() - retval.startDate.getTime());
        //although it shouldn't happen....
        if(retval.value <0) retval.value = 0;
        onSuccess(retval);
      }, onError);`

@dariosalvi78 thank you for this plugin!

**Comment by juanico18** [comment]
@fdmartins That fix is not valid.
https://github.com/dariosalvi78/cordova-plugin-health/issues/295 
You have an array as result because you added in the params the attribute:
 bucket: 'day' So you need to iterate.
 
 Adittionaly take into account that basal_ms can be 0 if the user have not changed age or height during the last year.

**Comment by dariosalvi78** [comment]
am going to close all Google Fit related issues as this is discontinued
