### ISSUE TITLE
I cannot use sleep data stably

### ISSUE THREAD

**Issue by mozhn** [dariosalvi78/cordova-plugin-health#195]
It sounds incomplete when retrieving sleep data on iOS devices. Also, there is no such problem on Android devices. There is a different problem on Android devices. It takes a long time to get the data. 15 - 20 seconds when taking 1 week of data. I wait 30 seconds while taking 1 month of data. I hope there is someone who can help.

**Comment by dariosalvi78** [comment]
what do you mean "It sounds incomplete when retrieving sleep data on iOS devices." ? 

for what regards time, it looks very strange, it is usually quite fast. May have to do with slow Internet connection maybe?

**Comment by mozhn** [comment]
Sorry for my bad english. I cannot fully get data on iOS devices (This might be my fault.). Unfortunately, it is not caused by an internet connection.
