### ISSUE TITLE
[iOS] isAuthorized() doesn't distinguish properly between read and write

### ISSUE THREAD

**Issue by nielsjakob** [dariosalvi78/cordova-plugin-health#196]
Hi,

`navigator.health.isAuthorized(dataType, authorized => console.log(authorized))` doesn't seem to work properly:

If weight is set to **read and write** in Health App > Profile > Apps > APPNAME
```
dataType = ['weight'] // true
dataType = [{read: ['weight']}] // true
dataType = [{write: ['weight']}] // true
```

If weight is **read-only**
```
dataType = ['weight'] // false
dataType = [{read: ['weight']}] // false (expected: true)
dataType = [{write: ['weight']}] // false
```

If weight is **write-only**
```
dataType = ['weight'] // true (expected: false)
dataType = [{read: ['weight']}] // true (expected: false)
dataType = [{write: ['weight']}] // true
```

...or am I doing something wrong?

Using version 2.0.0

**Comment by dariosalvi78** [comment]
I'm afraid it's [a design decision in HealthKit](https://developer.apple.com/documentation/healthkit/hkhealthstore/1614154-authorizationstatus)
