### ISSUE TITLE
Can not get permission to use google fit after app is installed from play store

### ISSUE THREAD

**Issue by rupalpatel0008** [dariosalvi78/cordova-plugin-health#20]
While testing, I am able to get google fit permission using navigator.health.requestAuthorization(permissions, androidPermissionSuccess, androidPermissionFailed);

But after I have uploaded my app in beta testing on play store, I can not get permission to use google fit in my app downloaded from play store.

**Comment by dariosalvi78** [comment]
you need to use the signing key you used for the APK you submitted to Play Store, not the development one within your Google API console

**Comment by rupalpatel0008** [comment]
Thank you for helping out.
