### ISSUE TITLE
Android steps count during cycling

### ISSUE THREAD

**Issue by maswa** [dariosalvi78/cordova-plugin-health#201]
We use this plugin in both iOS and Android for steps data and cycling distance.  Everything is working fine in iOS but we have a problem in Android when a user has the phone in pants pocket during cycling. In that case the plugin gives us steps during the cycling trip.  On a 2 km cycling distance it adds around 700 steps.   If phone is carried in jacket pocket then it doesn't add steps, so then it goes right. 

Is there any clue of what could cause this behaviour?

**Comment by dariosalvi78** [comment]
sorry, but this is not an issue of the plugin.

You can try the "filtered" steps to see if you get better results though.
