### ISSUE TITLE
Cannot get data for data type activity

### ISSUE THREAD

**Issue by marioshtika** [dariosalvi78/cordova-plugin-health#202]
Hello Dario,
I am having a problem while getting activity data.

I am using ionic and below is the code I am using

```
public async retrieveActivities() {
    try {
        const available: boolean = await this.health.isAvailable();
        if(available) {
            await this.health.requestAuthorization([
                {
                    read : ['activity']
                }
            ]);
            const result = await this.health.query({
                startDate: new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000), // three days ago 
                endDate: new Date(), // now 
                dataType: 'activity'
            });
            console.log(result); 
    } catch (error) {
        console.log(error);
    } 
}
```

With the above code, I am getting this error message:
**"com.google.android.gms.common.api.ApiException: 5000: Application needs OAuth consent from the user"**

I used the same code with dataType 'weight' and it is working fine. 
This error is shown only for the 'activity' dataType.

Is there a problem with the 'activity' dataType or am I doing something wrong?

Thank you in advance.

**Comment by dariosalvi78** [comment]
it must be something related to the oauth authorization process. Please be aware that Google has completely changed their authorization flow recently and you need to go through a lengthy and complex process to get your app authorized by them. I'lll close this issue assuming it's not a problem related to the plugin (I have tested this same use case myself and it's working fine in my app).

**Comment by marioshtika** [comment]
You were right, it was related to the oAuth authorization process, as I mentioned it in [this](https://github.com/dariosalvi78/cordova-plugin-health/issues/203) issue
