### ISSUE TITLE
Google FIT API authorization process

### ISSUE THREAD

**Issue by marioshtika** [dariosalvi78/cordova-plugin-health#203]
Hello Dario.

This is more of a support question rather than reporting an issue.

I want to get the activities from Google Fit from the saved data (not from the device sensor)

What scope should I add to the OAuth consent screen?

Should I add the below **sensitive** scopes

```
.../auth/fitness.activity.read
.../auth/fitness.location.read
```

![sensitive-scopes](https://user-images.githubusercontent.com/3079663/111475982-55a82a00-8736-11eb-967b-9c26a8a77c2d.png)

Or should I add the below **non-sensitive** scopes

```
.../auth/fitness
```

![non-sensitive-scopes](https://user-images.githubusercontent.com/3079663/111476916-44135200-8737-11eb-8da0-4a232e8c1e70.png)

Any information would be helpful.

Thank you in advance.

**Comment by dariosalvi78** [comment]
I'm going through this torture as well, so take my answer with a pinch of salt because I haven't been authorised yet.
As far as I understand it, for activities, you need `fitness.activity.read`. `fitness` is for general access to the API and you don't even need to ask for authorization.

**Comment by dariosalvi78** [comment]
going to close this now because not really a plugin issue

**Comment by marioshtika** [comment]
Just FYI.

I was trying to get Activities from Google Fit so I was asking for `fitness.activity.read`
- the first reviewer told me that the app was requesting also for `fitness. location.read` so I had to add that scope
- the second reviewer told me that you should not add a scope that you are not using
- and third time's the charm it was accepted with both `activity` and `location` scopes, since I needed the distance of each activity anyway.

So after a lot of frustration of getting my app authorised :) I found out that you have to request both scope `activity` and `location` to use the `activity` data type.

Thank you again @dariosalvi78 for this great plugin and for your help.

**Comment by dariosalvi78** [comment]
thanks for the update. The location is added because the plugin also retrieves the distance for each activity. This is done both on Android and iOS.

Thinking about it, I would like to make distance and calories per activity optional because it may be confusing for both the developer and the user.

**Comment by marioshtika** [comment]
I agree. I was thinking the same thing 👍
