### ISSUE TITLE
Selecting a gmail Account not linked to Google fit causes a white box with a spinner to endlessly spin

### ISSUE THREAD

**Issue by MatthewOps** [dariosalvi78/cordova-plugin-health#205]
I'm having an issue with the requestAuthorization() method for Android. It usually works perfectly fine if the user picks a Gmail account that has been linked with google fit, but if they pick an unlinked account, it just spawns a white box that endlessly spins. Has anyone found a way to cause this to instead close out when it detects an unlinked account so that I can just display a message to the user telling them that their account is unlinked?

**Comment by dariosalvi78** [comment]
I have experienced the same issue on Android <10 when testing. Not an plugin issue though.
I'll leave this here for a few days to see if we get more answers but I'll close it later.

**Comment by MatthewOps** [comment]
Turns out the issue with this was was that they weren't added as testers on the Google Cloud Console. No clue why the emails that did work worked without being testers, but as long as its solved I suppose.

For anyone else with this issue, you have to the Google Cloud Console and its on the OAuth Consent Screen page. You have to add the google email to the test user's section. Also worth noting, when you publish your application to the app store, you also have to hit the Publish App button at the top of the same screen or else I assume all of your users will have the same issue listed above.
