### ISSUE TITLE
Some Google accounts that are linked to google fit don't seem to work with the plugin

### ISSUE THREAD

**Issue by MatthewOps** [dariosalvi78/cordova-plugin-health#207]
I haven't found any rhyme or reason for this yet, but some Gmail accounts just bring up a spinning box of death instead of a confirmation screen when authorizing for the plugin. I think it has to be some kind of setting with the account itself though, because the accounts that work seem to always work and those that don't seem to never work. Is there a specific setting that needs to be changed for the plugin to be able to connect to a Gmail account?

**Comment by dariosalvi78** [comment]
have you got approval from Google to use the APIs?
My experience is that the testing mode only works on Android >10.

**Comment by MatthewOps** [comment]
Turns out the issue with this was was that they weren't added as testers on the Google Cloud Console. No clue why the emails that did work worked without being testers, but as long as its solved I suppose.

For anyone else with this issue, you have to the Google Cloud Console and it is on the OAuth Consent Screen page. You have to add the google email to the test user's section. Also worth noting, when you publish your application to the app store, you also have to hit the Publish App button at the top of the same screen or else I assume all of your users will have the same issue listed above.
