### ISSUE TITLE
What will the new changes with the gfit api be like for this plugin (question)

### ISSUE THREAD

**Issue by theVerySharpFlat** [dariosalvi78/cordova-plugin-health#208]
I am developing an app with your plugin and would like to know what I have to do when google enforces their stricter guidelines. My app only needs read access to steps, distance, and calories burned. I have an oauth 2.0 client id set up for my google account for the app, but I didn't put it in the project in any way. My App works currently, but do I need to do anything more when the changes roll around? Could you please explain the authentication process for your plugin better? I am completely new to app development and would really like to know.

**Comment by dariosalvi78** [comment]
I suggest you read the [extensive explanations](https://developers.google.com/fit/policy) Google give. I'm going through the process now and I can only tell you that it's very messy and extremely painful.

May the almighty Google be kind on you.

**Comment by fernandoruaro** [comment]
hey @dariosalvi78, were you able to get your app approved? For some reason the OAuth Consent Screen is not showing when I start the requestAuthorization process from the library. The library is working fine, but google is not approving us because they "can't see the OAuth Consent Screen". Thank you

**Comment by dariosalvi78** [comment]
Yes I got approval but it took a few iterations. When in testing mode, the consent screen works only on Android >=10 in my experience.

**Comment by fernandoruaro** [comment]
@dariosalvi78 thank you for your answer! I'm glad you were able to get your app approved.

In case anyone needs, I had to go to my Google account and remove my app from it, otherwise it wouldn't show me the OAuth Consent Screen (without seeing the OAuth Consent Screen in the video, the reviewers will not approve the app).
