### ISSUE TITLE
isAvailable() is not working on Android 11

### ISSUE THREAD

**Issue by marioshtika** [dariosalvi78/cordova-plugin-health#209]
Hello Dario.

The `isAvailable()` function is not working on Android 11.

It looks like Android 11 introduces changes related to package visibility. As stated in [here](https://developer.android.com/about/versions/11/privacy/package-visibility).

I created a pull request (#210) with a fix about this, as recommended on the Android Developers Guides.

I have tested it and it is working fine.

Let me know if you need anything else.

**Comment by marioshtika** [comment]
Hello Dario,

and thank you for the quick response. 

Do you think is possible to make a release to npm with this change, or do you want to add other features before releasing it?

Thank you in advance.

**Comment by dariosalvi78** [comment]
published!
