### ISSUE TITLE
Real iOS device issue

### ISSUE THREAD

**Issue by itconsulting-live** [dariosalvi78/cordova-plugin-health#21]
Hello, I realize that this comes from the original Health Plugin, so I've opened the issue there, but this plugin depends on it, so it's better to have it here as well I think:

Building/Deploying for the actual iOS device causes a linker error:
Undefined symbols for architecture armv7:
  "_HKCharacteristicTypeIdentifierFitzpatrickSkinType", referenced from:
      -[HealthKit readFitzpatrickSkinType:] in HealthKit-18B10050B69093A6.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dariosalviwork** [comment]
_HKCharacteristicTypeIdentifierFitzpatrickSkinType was introduced recently, you need to update to the latest iOS SDK
