### ISSUE TITLE
Slow query for activities

### ISSUE THREAD

**Issue by WestonN** [dariosalvi78/cordova-plugin-health#212]
I am trying to query for activities for a pretty long range (1-2 months), but the retrieval is taking a long time (~2 min).  I know this can result in a large array, this call for instance had a length of 600, but 2 minutes for an array that size seems quite large. 

 I guess my question is if this seems typical, and therefore I just need to find ways to reduce the range I am retrieving from.  Or, is there something I'm missing that is causing such a delay in the retrieval of the data?  Would queryAggregate be an alternative?  I've read the documentation pretty closely, but did I miss a parameter that I could pass along that might speed things up?  

Additionally, I've tested this on both new and old androids, so I would doubt it is related to the hardware

**Comment by dariosalvi78** [comment]
queryAggregate would definitely be a better choice for this time window, I'd always recommend to use it if you can, even for smaller time windows.

One factor affecting speed is that, currently, querying activities also queries calories and distance (see [here](https://github.com/dariosalvi78/cordova-plugin-health/blob/dc69c364980b6a5f3c43f7e6dba431394abba941/src/android/HealthPlugin.java#L620)). I am thinking of making this optional, but I don't have time right now to work on it. If anyone dares to send a PR I'd be grateful.

**Comment by WestonN** [comment]
Gotcha, I'll give queryAggregated a go and see what comes of that.  Hopefully that is quick enough without removing the calories/distance

Thank you very much for such a quick reply!!
