### ISSUE TITLE
Android seems to be requesting read/write access when using read with requestAuthorization.

### ISSUE THREAD

**Issue by jlongev** [dariosalvi78/cordova-plugin-health#213]
Hi and thanks for the great work.

We are using this plugin currently in a Cordova app.  Looking at the new guidelines for Android located here https://developers.google.com/fit/improvements.  They mention that if you request write access it now only gives you read access to data that your app has written as apposed to all data.  Does this plugin request read and write access when you request access in the default way without specifying read or write (or just write access)?

Also I have just tested our app by changing the permissions to [{read: ['steps', 'weight']}] instead of ['steps', 'weight'] as we only need read access.  The oAuth dialog did not change and still asks for permission to add and view data.  Is this a bug or limitation of the plugin?

Thanks a lot.

**Comment by dariosalvi78** [comment]
as for the first question, the plugin should already support reading from other apps, see https://github.com/dariosalvi78/cordova-plugin-health/commit/cff379fabf8a98dbf19f58247cb8edf1a595a458

As for the second question, if you use the same user that gave write access you will already have read access granted.

**Comment by jlongev** [comment]
Thank you so much for the response.  Makes sense!

**Comment by KevRyan2** [comment]
I'm having an issue figuring out what scopes this plugin is actually requesting.  I got the below response from them during the oauth verification process, but I'm attempting to read steps, and am requesting that during the requestAuthorization process but it's not showing as something I'm requesting. Shouldn't  this.health.requestAuthorization(['distance', 'calories', 'activity', { read: ['steps']} ]); request activity and location read access as well?

My version of the plugin is 1.0.5, and I know the updated versions support the newer APIs, but I am on ionic 3 and cordova-android 6.3.0, and I don't believe the newer versions of this plugin are supported with those versions (the use of the lambda arrow functions in this plugin >=2.0.0 is one of the main issues).

**Scopes Submitted for Review​**
https://www.googleapis.com/auth/fitness.activity.read
https://www.googleapis.com/auth/fitness.activity.write
https://www.googleapis.com/auth/fitness.location.read

**Scopes Requested by your App**
https://www.googleapis.com/auth/fitness.activity.write  
https://www.googleapis.com/auth/fitness.location.write

**Comment by dariosalvi78** [comment]
distance is set as read/write, so maybe that's why?
be careful with older versions of the plugin, Google has requested additional permissions over time that are only updated in more recent versions of the plugin.

**Comment by kenibarwick** [comment]
Hey there, similar issue when dealing with Google scopes. 

We are using 2.0.3 and are also asking for read only access from the scope like this; 

```
            await this.health.requestAuthorization([
                {
                    read: ['steps', 'distance']
                },

```
However we are seeing the following from Google;

> Use Google Fit to see and **_store_** your physical activity data
> See your Google Fit speed and distance data

What do you think we are doing wrong?

thanks in advance!

**Comment by dariosalvi78** [comment]
maybe in your oauth you are asking also for write permissions?
