### ISSUE TITLE
Activity Name in Google Fit

### ISSUE THREAD

**Issue by WestonN** [dariosalvi78/cordova-plugin-health#214]
Is there anyway to have the activity name (the one the user can edit) be given when querying for activities?  I need to distinguish between user-defined activities and passively tracked activities (still, sleep, driving), but as of right now it seems the object doesn't come with that attribute

Essentially i need the journal entries, rather than all activities.  But if I can get the activity's name defined by the user, I could technically filter as needed

**Comment by dariosalvi78** [comment]
Can't you check the sourceBundleId for that?

**Comment by WestonN** [comment]
Doesn't the sourceBundleId just give the source package name?  If so, google fit passively tracks activities so I wouldn't be able to use that to distinguish between 'handmade' activities and 'nonhandmade' activities

**Comment by dariosalvi78** [comment]
yes it gives the package name, if the activity was input manually in Fit then I guess you'd get the same ID. I don't think it's something we can do about it..
