### ISSUE TITLE
Android requestAuthorization dialog issue

### ISSUE THREAD

**Issue by Talal0** [dariosalvi78/cordova-plugin-health#218]
I have installed plugin in android and Google Fit app in the phone I have samsung s6 edge plus having android version 7.0 requestAuthorization shows popup to select google account when user tap on listed account/newly created dialog dismiss and error message shows  "User cancelled the dialog" please help me to resolve this

**Comment by dariosalvi78** [comment]
you need to correctly setup the Fitness API access. See guidelines in README and closed issues.
