### ISSUE TITLE
estimated steps

### ISSUE THREAD

**Issue by zazics** [dariosalvi78/cordova-plugin-health#22]
"queryAggregated" doesn't return estimated steps but "all" steps, even not significant ones. The result is that Google Fit app show me 2300 steps and "queryAggregated" returns me 6900 steps.

As explains here: https://developers.google.com/fit/faq#values-no-match
It should be interesting for "queryAggregated" to return estimated steps.
I tried and it works perfectly. I edited HealthPlugin.java and replaced line 622 by:

DataSource ESTIMATED_STEP_DELTAS = new DataSource.Builder()
		   .setDataType(DataType.TYPE_STEP_COUNT_DELTA)
		   .setType(DataSource.TYPE_DERIVED)
		   .setStreamName("estimated_steps")
		   .setAppPackageName("com.google.android.gms")
		   .build();
builder.aggregate(ESTIMATED_STEP_DELTAS, DataType.AGGREGATE_STEP_COUNT_DELTA);

**Comment by dariosalviwork** [comment]
this was in my TODO list. Thanks for the suggestion, I will add a flag when querying steps, stay tuned!

**Comment by dariosalviwork** [comment]
see also roadmap:

get steps from the "polished" Google Fit data source (see https://plus.google.com/104895513165544578271/posts/a8P62A6ejQy)
