### ISSUE TITLE
Dates of workouts

### ISSUE THREAD

**Issue by carlosa-arellano** [dariosalvi78/cordova-plugin-health#223]
Is it possible to check the start time and the end time of each workout? 
For example something like this: 
[ 
  { 
    "endDate": "2021-08-06T00:24:00-05:00", 
    "startDate": "2021-08-06T00:03:00-05:00", 
    "distance": "5000", 
    "duration": 1260, 
    "activityType": "running" 
  }, 
  { 
    "endDate": "2021-08-06T04:57:00-05:00", 
    "startDate": "2021-08-06T04:03:00-05:00", 
    "distance": "2000", 
    "duration": 3240, 
    "activityType": "running" 
  } 
]

**Comment by dariosalvi78** [comment]
yes
