### ISSUE TITLE
Authorization error "Attempt to invoke virtual method 'java.lang.String com.google.android.gms.fitness.data.DataType.zzk()' on a null object reference"

### ISSUE THREAD

**Issue by martrix78** [dariosalvi78/cordova-plugin-health#227]
Hi i have problems on android 11 and cordova-plugin-health (2.0.2/ 2.0.3)
```
Ionic:
   Ionic CLI                     : 6.15.0 
   Ionic Framework               : @ionic/angular 5.6.5
   @angular-devkit/build-angular : 0.1102.10
   @angular-devkit/schematics    : 11.2.10
   @angular/cli                  : 11.2.10
   @ionic/angular-toolkit        : 3.1.1

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 13 other plugins)

Utility:
   cordova-res                          : 0.15.3
   native-run (update available: 1.4.1) : 0.2.9

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v12.22.5
   npm               : 6.14.14
   OS                : Linux 4.15
```
when i try to call :
      **this.health.requestAuthorization([{ read: ['steps', 'distance', 'appleExerciseTime', 'calories', 'activity'] }])**
i got error
**Attempt to invoke virtual method 'java.lang.String com.google.android.gms.fitness.data.DataType.zzk()' on a null object reference**

Please help me solve the problem

**Comment by dariosalvi78** [comment]
the problem is that you are requesting authorisation for appleExerciseTime on Android. Check what operating system you are running in your application and request authorization of data types that are compatible only.
