### ISSUE TITLE
HealthKit capability is not added automatically in plist on iOS

### ISSUE THREAD

**Issue by marioshtika** [dariosalvi78/cordova-plugin-health#228]
Hello @dariosalvi78.

As mentioned in the title of this issue, the HealthKit capability is not added automatically in the plist file on iOS.

I am adding this capability every time manually. And if we use automation to build and release the app we are going to have a problem.

Is adding this capability, something that is not needed anymore, or is there another reason this is not added automatically?

Thank you in advance.

**Comment by dariosalvi78** [comment]
I am OK to automate this, but I'm not sure how to do it. Happy to receive a PR...

**Comment by marioshtika** [comment]
Thank you @dariosalvi78, I will try to implement it and send you a PR.

**Comment by marioshtika** [comment]
Hello @dariosalvi78, sorry it took me so long to send a pull request for this 😄 

I have added the new configurations that are needed in the `Entitlements-Debug.plist` and `Entitlements-Release.plist` files to automatically enable Health capability during the plugin installation.

I have tested it and it is working fine.

This is a screenshot of the result in Xcode

<img width="633" alt="healthkit" src="https://user-images.githubusercontent.com/3079663/170949517-a8f49060-a904-4f45-a24f-514121df1181.png">

Let me know if you need anything else from me.

**Comment by dariosalvi78** [comment]
Hi,

Thanks for your contribution.

I would love to have the healtkit capability but NOT the health record or background delivery one. The health records capabiilty is not supported by this plugin and thus pointless to be added.

Is it possible to have healthkit alone?

**Comment by marioshtika** [comment]
Oh sorry, I thought the plugin needed those options.

Let me check and I will get back at you.

**Comment by marioshtika** [comment]
@dariosalvi78 I have removed the background delivery configuration and I have added an empty array for the clinical Health Records, as it is needed to enable the HealthKit capability.

And this is the result

<img width="636" alt="health-default" src="https://user-images.githubusercontent.com/3079663/170954278-c64e0365-3bd5-4304-b0e5-52a95e2ddfea.png">

**Comment by marioshtika** [comment]
Can you release it also on npm? Thank you in advance.
