### ISSUE TITLE
 🔁 Can't get OAuth verification without showing consent screen, which requires verification 🔁

### ISSUE THREAD

**Issue by boost-app** [dariosalvi78/cordova-plugin-health#229]
My App is currently stuck in a loop in the OAuth verification process with Google:

Google requires from me a YouTube Video showing the OAuth Screen requiring Google fit scopes.
This screen however can't be shown unless i have passed the verification...

When i request google fit read/write the plugin consent screen is stuck like this indefinitely:

[Consent screen stuck](https://imgur.com/a/INd5z5d)

I checked the following prerequisites: 
- My Fingerprints work: Google login with Same client API keys works flawlessly
- The plugin works: Apple Health uses the exact same code and works perfectly

How should i proceed with this issue? Has anyone successfully got the google verification recently?
Thanks for any help and thanks for the great plugin!

**Comment by dariosalvi78** [comment]
check the process again and again, it's a Google cloud related thing.
In my experience, older phones (Android <10) got stuck but newer ones did not. Not sure why.

**Comment by boost-app** [comment]
That's a good hint! My testing device is on Android 8. Will check with newer Android and report back.

Does that mean the plugin won't work with Android < 10 at all?

**Comment by dariosalvi78** [comment]
once approved, it works on older Androids as well.
i'll close the issue because not due to the plugin.
You can join us in the chat on gitter, other people had your same problem.

**Comment by boost-app** [comment]
Thanks for your help!
