### ISSUE TITLE
cannot find symbol method hasPermission

### ISSUE THREAD

**Issue by array-addu** [dariosalvi78/cordova-plugin-health#23]
Got following error on running the application:
`Error:(165, 29) error: cannot find symbol method hasPermission(String)
Error:(172, 24) error: cannot find symbol method requestPermissions(HealthPlugin,int,String[])
Error:Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
`
```
public void requestDynamicPermissions() {
        if (dynPerms.isEmpty()) {
            authReqCallbackCtx.success();
        } else {
            LinkedList<String> perms = new LinkedList<String>();
            for (String p : dynPerms) {
                if (!cordova.hasPermission(p)) {
                    perms.add(p);
                }
            }
            if (perms.isEmpty()) {
                authReqCallbackCtx.success();
            } else {
                cordova.requestPermissions(this, REQUEST_DYN_PERMS, perms.toArray(new String[perms.size()]));
            }
        }
    }
```

**Comment by dariosalviwork** [comment]
this plugin works with a recent Android SDK, please update cordova.
