### ISSUE TITLE
Ionic Cordova Health is not working

### ISSUE THREAD

**Issue by VeeRHunter** [dariosalvi78/cordova-plugin-health#231]
The isAvailable function is returning false.
Also when I try to use the plugin, it is showing me the select accounts(like the google signin), but when I select(add) account, it is always showing loading, what is the error on this please?

![Screenshot_21](https://user-images.githubusercontent.com/30534578/137768772-d740ffb8-6f6a-4ad4-9ff4-155c6ece83d3.png)

Best regards

**Comment by VeeRHunter** [comment]
Okay, thanks

**Comment by dariosalvi78** [comment]
my recommendation is to go and check the Google cloud configuration over and over, sometimes you are just missing something...

**Comment by dariosalvi78** [comment]
I'm sorry but I cannot be of more help. Check your Google cloud configuration again and maybe try on a recent Android phone. I would recommend to contact Google if you still can't solve it.

**Comment by VeeRHunter** [comment]
I have create new project, and tried to generate debug.keystore for this own health project.
But after I build the apk, I can find the SHA1 is different between keystore and apk.
How to make same between them?
