### ISSUE TITLE
iOS OxygenSaturation

### ISSUE THREAD

**Issue by seijichishiki** [dariosalvi78/cordova-plugin-health#233]
I got "unknown read data type - oxygen_saturation" on Xcode console.

Is this only Android ?
How can I get the IOS oxygen saturation ?

Thank you.

**Comment by dlandtaa** [comment]
I think something is wrong here. I'm getting the error originally mentioned. And yes, the latest code in this repo contains the line

```
dataTypes['oxygen_saturation'] = 'HKQuantityTypeIdentifierOxygenSaturation'; 
```

that @dariosalvi78 references but when I actually add the plugin to my cordova project that line is not there. Same if I just run

```
npm i cordova-plugin-health
```

Is it possible the latest version of the package has not been published?

**Comment by dariosalvi78** [comment]
I need to publish the latest version. I'll do it today.
