### ISSUE TITLE
Google Fitness oAuth consent screen not showing URL bar

### ISSUE THREAD

**Issue by it4e** [dariosalvi78/cordova-plugin-health#236]
Hi,

As a requirement from Google to be able to use the Fitness API a video demonstration of the oAuth consent screen process needs to be provided. Google specifically asks to see the URL bar of the consent screen to verify the application.  However, the URL bar is not displayed in the current consent screen provided by the plugin. 

Any ideas on how to fix this?

**Comment by dariosalvi78** [comment]
it's an app, you cannot show any URL

**Comment by it4e** [comment]
> it's an app, you cannot show an URL bar. Or am I misunderstanding this? Are you sure you are reading the guidelines for apps and not for the HTTP APIs?

Yes, sadly the guidelines are for apps as well. 

To cite Google:

Every OAuth project that requests sensitive scopes must provide a YouTube video of their app that follows these requirements: 

- Video is publicly accessible.
- OAuth Consent Screen is in English.
- OAuth Consent Screen shows the App Name.
- URL bar of the OAuth Consent Screen fully displays the Client ID in your project which contains the project_number xxxxx
- Video shows the OAuth grant process that users will go through.
- Video shows how the data will be used by showing functionality for each sensitive and restricted scope you've requested.
- Video shows how data is accessed on each OAuth client.

**Comment by dnbo** [comment]
Just for future reference, this is not required for native apps (Android / iOS).

Quote from an email during the verification process

> Enlarge the OAuth Consent Screen to show the URL including the Client ID (This is not required for native Android and iOS apps).
