### ISSUE TITLE
Deny using google fit in popup

### ISSUE THREAD

**Issue by gareskiv96** [dariosalvi78/cordova-plugin-health#238]
When i tap Deny on"Allow your app to access this device's location?" and  "Allow your app to access your physical activity? popup and switch screen in my app then when i return back i see the same pop for permissions. This is showed when i call navigator.requestAuthorization(); 
Please help.

**Comment by dariosalvi78** [comment]
the pop up messages are just regular Android permission dialogs that are created when calling requestAuthorization(). I don't understand what the issue is. Can you explain better?

**Comment by gareskiv96** [comment]
I am requesting authorization on a particular screen in my app (home screen). Also i have swiper in my app and when i tap on deny for authorization then swipe on another screen and return back to home screen i get the authorization popup again. When i tap on deny again and i repeat the same with swiping on another screen and back on home for the second time it's working fine and not showing the popup.

**Comment by dariosalvi78** [comment]
I have no idea :)
looks like something outside the control of this plugin. As said, the plugin uses the regular permissions mechanisms offered by Android.

You can check with logcat if you see anything strange happening.
