### ISSUE TITLE
Unable to store data type activity in android

### ISSUE THREAD

**Issue by jseverywhere15** [dariosalvi78/cordova-plugin-health#239]
I am trying to store activity in android using the following sample snippet:

 navigator.health.store({
   startDate: new Date(),
   endDate: new Date(),
   dataType: 'activity',
   value: 'running',
   sourceName: 'newapp',
   sourceBundleId: 'newapp'
}, function () {}, function() {})

it throws the following error: 'Attempting to set a string value to a field that is not in STRING format. Please check the data type definition and use the right format.' 

I am able to store other dataType like steps and calories successfully.

Any help is much appreciated!

**Comment by jseverywhere15** [comment]
anyone run into similar experience? I tried downgrading to previous few versions and still seeing this error message in Android while attempting to store dataType activity. thanks!

**Comment by dariosalvi78** [comment]
last time I checked it worked, but it was some time ago. Can you try with some other activity as well?

**Comment by jseverywhere15** [comment]
I tried the following activity 'running', 'walking', 'sleep' and 'strength_training' and they all gave the same error message. thanks

**Comment by dariosalvi78** [comment]
Ok, problem identified, see chat in gitter.
The method to set the activity should use this function: https://android-doc.github.io/reference/com/google/android/gms/fitness/data/Value.html

I can fix this when I have time but I am very happy to receive PRs to fix it if someone is so brave to try it.

**Comment by jseverywhere15** [comment]
thanks much for the reply. super appreciative if someone can help fix this whenever they have time. big thanks again!

**Comment by MaxwellGrant1** [comment]
Was this ever fixed?

**Comment by dariosalvi78** [comment]
it hasn't been fixed, but the fix is actually simple, see comments above.
Can anybody try to fix it?

**Comment by dariosalvi78** [comment]
fixed in v 2.1.0
