### ISSUE TITLE
store nutrients

### ISSUE THREAD

**Issue by dariosalviwork** [dariosalvi78/cordova-plugin-health#24]
store() needs to be extended to support nutrients

**Comment by rupalpatel0008** [comment]
HeyI have worked on this and the updated plugin I am using can store nutritions in android.

**Comment by dariosalvi78** [comment]
Can you prepare a pull request or send me a snippet?

**Comment by rupalpatel0008** [comment]
**I only needed to add fat, carbs and protein so I have only added those in my code.**

**In health.js**
Health.prototype.storeNutrition = function(data, onSuccess, onError) {
  exec(onSuccess, onError, "health", "storeNutrition", [data]);
};

**In HealthPlugin.java**
private void storeNutrition(final JSONArray args, final CallbackContext callbackContext) throws JSONException {
        
        if (!args.getJSONObject(0).has("foodName")) {
            callbackContext.error("Missing argument foodName");
            return;
        }
        if(!args.getJSONObject(0).has("mealType")) {
            callbackContext.error("Missing argument mealType");
            return;
        }
        if(!args.getJSONObject(0).has("protein")) {
            callbackContext.error("Missing argument protein");
            return;
        }
        if(!args.getJSONObject(0).has("carbs")) {
            callbackContext.error("Missing argument carbs");
            return;
        }
        if(!args.getJSONObject(0).has("totalfat")) {
            callbackContext.error("Missing argument totalfat");
            return;
        }
        if (!args.getJSONObject(0).has("source")) {
            callbackContext.error("Missing argument source");
            return;
        }

        String mealType = args.getJSONObject(0).getString("mealType");
        String foodName = args.getJSONObject(0).getString("foodName");
        float protein = Float.parseFloat(args.getJSONObject(0).getString("protein"));
        float carbs = Float.parseFloat(args.getJSONObject(0).getString("carbs"));
        float totalfat = Float.parseFloat(args.getJSONObject(0).getString("totalfat"));
        String source = args.getJSONObject(0).getString("source");

        if ((mClient == null) || (!mClient.isConnected())){
            if(!lightConnect()){
                callbackContext.error("Cannot connect to Google Fit");
                return;
            }
        }

        String packageName = cordova.getActivity().getApplicationContext().getPackageName();

        DataSource nutritionDataSource = new DataSource.Builder()
            .setAppPackageName(packageName)
            .setType(DataSource.TYPE_RAW)
            .setDataType(DataType.TYPE_NUTRITION)
            .build();

        DataPoint nutritionPoint = DataPoint.create(nutritionDataSource);
        nutritionPoint.setTimestamp(System.currentTimeMillis(), TimeUnit.MILLISECONDS);
        nutritionPoint.getValue(Field.FIELD_FOOD_ITEM).setString(foodName);
        if(mealType.equalsIgnoreCase("snack")){
            nutritionPoint.getValue(Field.FIELD_MEAL_TYPE).setInt(Field.MEAL_TYPE_SNACK);        
        } else if(mealType.equalsIgnoreCase("breakfast")){
            nutritionPoint.getValue(Field.FIELD_MEAL_TYPE).setInt(Field.MEAL_TYPE_BREAKFAST);        
        } else if(mealType.equalsIgnoreCase("lunch")){
            nutritionPoint.getValue(Field.FIELD_MEAL_TYPE).setInt(Field.MEAL_TYPE_LUNCH);        
        } else if(mealType.equalsIgnoreCase("dinner")){
            nutritionPoint.getValue(Field.FIELD_MEAL_TYPE).setInt(Field.MEAL_TYPE_DINNER);        
        } else {
            nutritionPoint.getValue(Field.FIELD_MEAL_TYPE).setInt(Field.MEAL_TYPE_UNKNOWN);
        }
        // Total Fat
        nutritionPoint.getValue(Field.FIELD_NUTRIENTS).setKeyValue(Field.NUTRIENT_TOTAL_FAT, totalfat*1f);
        // nutritionPoint.getValue(Field.FIELD_NUTRIENTS).setKeyValue(Field.NUTRIENT_TOTAL_FAT, 0.04f);
        // Protein
        nutritionPoint.getValue(Field.FIELD_NUTRIENTS).setKeyValue(Field.NUTRIENT_PROTEIN, protein*1f);
        // nutritionPoint.getValue(Field.FIELD_NUTRIENTS).setKeyValue(Field.NUTRIENT_PROTEIN, 0.056f);
        // Total carabohydrates
        nutritionPoint.getValue(Field.FIELD_NUTRIENTS).setKeyValue(Field.NUTRIENT_TOTAL_CARBS, carbs*1f);
        // nutritionPoint.getValue(Field.FIELD_NUTRIENTS).setKeyValue(Field.NUTRIENT_TOTAL_CARBS, 12f);

        DataSet nutritionDataSet = DataSet.create(nutritionDataSource);
        nutritionDataSet.add(nutritionPoint);

        Status insertStatus = Fitness.HistoryApi.insertData(mClient, nutritionDataSet).await();

        // Status insertStatus = Fitness.HistoryApi.insertData(mClient, dataSet)
        //         .await(1, TimeUnit.MINUTES);

        if (!insertStatus.isSuccess()) {
            callbackContext.error(insertStatus.getStatusMessage());
        } else {
            callbackContext.success();
        }
    }

**Comment by dariosalviwork** [comment]
thanks for the snippet. I will try to use the generic store() function and be compatible with all nutrients. It's in the TODO list, but it won't be ready soon, I'm quite busy now.

**Comment by dariosalviwork** [comment]
support now added for iOS

**Comment by rupalpatel0008** [comment]
Hey, your plugin now stores nutritions in ios but its giving error "nutrients not set" in android for same code.

Here is my **ionic info**
global packages:
    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.0.0

local packages:
    @ionic/cli-plugin-cordova : 1.0.0
    @ionic/cli-plugin-ionic1  : 1.0.0
    Ionic Framework           : ionic1 1.3.1

System:
    Node       : v7.2.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 

Function to store nutritions in both ios and android
`navigator.health.store({
      "dataType": "nutrition",
      "startDate": new Date(new Date().getTime() - 3 * 60 * 1000),//3 mins ago
      "endDate": new Date(),
      "value": {
        "nutrients": {
          "nutrition.protein": protein,
          "nutrition.carbs.total": carbs,
          "nutrition.fat.total": fat
        },
        "item": "unknown",
        "meal_type":mealname,
			},
      "sourceName": "HealthApp",
		},
		successSaveMealMacro1,
		errorSaveMealMacro1);`


Can you please explain the reason behind this error?

**Comment by dariosalviwork** [comment]
this issue is still open, storing nutrition on Android is not supported yet as now.

The code needed to add support in Android is quite simple, if you you want to try developing it yourself I'll be happy to get a pull request.

**Comment by dariosalviwork** [comment]
I haven't integrated your code as yet, this is why the issue is still open.

Let me see if I can solve it quickly...

**Comment by dariosalviwork** [comment]
nutrition should be supported on Android too now.
