### ISSUE TITLE
Request for a datatype

### ISSUE THREAD

**Issue by rafaellop** [dariosalvi78/cordova-plugin-health#240]
Please add the waistCircumference data type to the supported data types.

**Comment by dariosalvi78** [comment]
do you feel brave enough to try to add it and send a PR 😀?

**Comment by rafaellop** [comment]
I can give it a try, but first I want to grasp how this HealthKit thing even works, because I get stumped at every turn ;)

**Comment by rafaellop** [comment]
I forked the sources and it should be pretty straightforward. I'll try tommorow.

**Comment by rafaellop** [comment]
OK, done, tested and PR send :-)

**Comment by dariosalvi78** [comment]
thanks

**Comment by rafaellop** [comment]
Thanks for approving. I've done a mistake in the commit description though. It should be 'waistCircumference' not 'weight...' :/
