### ISSUE TITLE
Height unit and value

### ISSUE THREAD

**Issue by rafaellop** [dariosalvi78/cordova-plugin-health#241]
The readme states that the `height` unit is `m` and the example values shows `185.9` for the `height` datatype as example. So I tried to store data in the Healthkit using this hints like this:

```
navigator.health.store({
	startDate:  new Date(new Date().getTime() - 3 * 60 * 1000), // three minutes ago
	endDate: new Date(),
	dataType: 'height',
	value: 180,
	sourceBundleId: 'com.example.my_app'
}, successCallback, errorCallback)
```

and the Health app on iPhone shows the height in feet as 590'6.614".

Is this a mistake in the example or in the code which converts the values when communicating to Healthkit?

**Comment by rafaellop** [comment]
I'm pretty sure the problem is with the example not the code. At least when using Apple HealthKit the value returned is fractional like `1.859` than `185.9`. However I'm not sure what is returned for Android and have no option to check so please confirm if possible.

**Comment by dariosalvi78** [comment]
yes, the example is wrong, 189m is quite tall indeed.
