### ISSUE TITLE
isAuthorized() calls successCallback even if there's no authorization (HealthKit)

### ISSUE THREAD

**Issue by rafaellop** [dariosalvi78/cordova-plugin-health#242]
The case is:

1. App started and permission given by the `requestAuthorization()` call. 
2. I can read/write from the app to the HealthKit
3. App close and all permissions revoked in the iOS Settings for the app (turn all off)
4. App started again. The startup call for `requestAuthorization()` doesn't ask for permissions but it's expected as discussed here #126 
5. However, what is a bug I think, calling `isAuthorized()` for the revoked permissions calls successCallback as if there was authorization given to the app in the Health Settings. Querying the HealthKit in that case obviously doesn't work, but I would like to present a user with a message asking for turning on back the permissions.

So, is there a way to find out if HealthKit is available and permissions are given and there's green light to go and operate it?

**Comment by dariosalvi78** [comment]
not a bug, HealthKit won't tell you if the authorization was given or not. It'a a design choice taken by Apple.

**Comment by rafaellop** [comment]
So what is the reason of this function (`isAuthorized()`)? Google Health supports it?
The iOS quirks for the function should state that it simply doesn't work on iOS.

**Comment by dariosalvi78** [comment]
please check the README, it says clearly:

> This method will only check authorization status for writeable data. Read-only data will always be considered as not authorized. This is an intended behaviour of HealthKit.

**Comment by dariosalvi78** [comment]
here is the original Apple's documentation: https://developer.apple.com/documentation/healthkit/hkhealthstore/1614154-authorizationstatusfortype?language=objc

**Comment by rafaellop** [comment]
> This method will only check authorization status for writeable data.

It just doesn't give any information. For an authorized app it calls success callback and the same for non-authorized. 
Regarding the docs you linked calling the function should return a status code rather than true/false values.
https://developer.apple.com/documentation/healthkit/hkauthorizationstatus?language=objc
