### ISSUE TITLE
fat_percentage values different on iOS/Android

### ISSUE THREAD

**Issue by rafaellop** [dariosalvi78/cordova-plugin-health#246]
The readme example shows that `fat_percentage` query returns percentage as fractional value e.g. `0.312` for `31.2%`. It's true on iOS, but on Android it doesn't returns standard percentage which in that case would be `31.2` for '31.2%` instead of `0.312` as in the docs. What way is correct? I'd prefer to avoid _ifdef's_. I could send a PR, but where? To the Android repo or iOS? This also should be covered in the update information so that people upgrading the plugin would be aware.

**Comment by rafaellop** [comment]
If you `store()` the `fat_percentage` data type it expects to be fractional on Android which is different from what `query()` returns. 

Additionally what I've found by incident is that the `store()` call on Android requires the `sourceName` value while on iOS it is not needed `sourceBundleId` is enough. If `sourceName` is not given the `store()` call returns error 'Missing argument sourceName`.

**Comment by dariosalvi78** [comment]
hi, thanks for identifying this issue!
We should make the format the same on both platforms, I really don't care where it is done (Android or iOS) as long as it is consistent and well documented.
Would you dare sending a PR?

About the sourceName needed in store(): I have never incurred into it, but it's been a while since I tested it, maybe they have changed the API. Can you please confirm it?

**Comment by rafaellop** [comment]
I can try to fix the divergence between these two issues reported recently, but this fix may cause issues for apps which use the plugin and would be updated without reading the changelog. I think it should be explicitly highlighted somewhere.

**Comment by dariosalvi78** [comment]
thanks. Yes I will create a new release, the problem affects those who update the version.

**Comment by dariosalvi78** [comment]
FYI: the sourceName has been removed from store(), it was added at some point, but never used.
