### ISSUE TITLE
ApiException 5000: : Application needs OAuth consent from the user

### ISSUE THREAD

**Issue by ChristophSchmid05** [dariosalvi78/cordova-plugin-health#247]
I am getting this error: **Error in Health Plugin: Error getting activities: com.google.android.gms.common.api.ApiException: 5000: Application needs OAuth consent from the user](https://stackoverflow.com/questions/71050431/error-in-health-plugin-error-getting-activities-com-google-android-gms-common)**

when I want to access "activity" data for android. 

This is my code: 

`this.health.isAvailable().
      .then((available: boolean) => {
      if (available) {
        this.health.isAuthorized([{read: ['activity']}]).then(() => {
          this.health.requestAuthorization([{
            read: ['activity']       // read only permission
          }]).then(() => {
                  this.health.query({
                    startDate: moment(new Date()).add(-2, 'months').toDate(),
                    endDate: new Date(), dataType: 'activity'
                  }).then((healthAPIActivities: any) => {
                    this.analyseHealthAPIActivities(healthAPIActivities);
                  }).catch((error: string) => {
                    this.handleExternalHealthDataError('Error getting activities: ' + error);
                  });`

Any ideas?

**Comment by ChristophSchmid05** [comment]
Nevermind found the issue. 
For future problems: The problem was that if you want to fetch activities you also have to request permission for 'calories' and 'distance'.

**Comment by rafaellop** [comment]
This should be in the readme! Thanks @ChristophSchmid05
