### ISSUE TITLE
blood_glucose values different on iOS / Android

### ISSUE THREAD

**Issue by rafaellop** [dariosalvi78/cordova-plugin-health#248]
The same kind of issue like https://github.com/dariosalvi78/cordova-plugin-health/issues/246

The readme example shows that blood_glucose query returns value as mmol/L value e.g. 5.5. It's true only on iOS, but on Android it doesn't return mmol/L. It returns mg/dL. It should be the same on both systems.

**Comment by dariosalvi78** [comment]
Hi,

would you feel so brave to send a PR with the conversion done?
I don't care which format we choose, but it would be good to have one single format for both. Conversion [is simple](https://www.bbraun.co.uk/en/patients/diabetes-care-for-patients/blood-glucose-measurement/conversion-tables.html) and could be done in the JS frontend code.

**Comment by dariosalvi78** [comment]
according to the documentation, blood glucose is in mmol/L.
https://developers.google.com/android/reference/com/google/android/gms/fitness/data/HealthDataTypes#public-static-final-datatype-type_blood_glucose
