### ISSUE TITLE
use standard metadata keys for nutrient

### ISSUE THREAD

**Issue by dariosalviwork** [dariosalvi78/cordova-plugin-health#25]
see http://fitnowdev.com/2014/10/16/food-healthkit-lose-it.html

use "HKFoodType" for item and "HKFoodMeal" for meal_type

**Comment by JulianLaval** [comment]
Hey!

Per the link, Lose It also supports a few other metadata keys which might be useful, namely `HKFoodBrandName`. What are your thoughts regarding its inclusion? Happy to submit a PR.

**Comment by dariosalvi78** [comment]
I wouldn't mind having an extra key, although I guess it will only be present in iOS.
Please, go ahead with the PR.
Thanks.
