### ISSUE TITLE
Add duration for activity in iOS

### ISSUE THREAD

**Issue by bmanderscheid** [dariosalvi78/cordova-plugin-health#251]
Hi,
I'm trying to get **duration** of an activity w/o doing a date diff (which works fine but there are some Apple Watch quirks we're running into).  Duration seems to be a more relabel property but it just isn't coming back.  This is an example returned result.  Thanks for any help!

{
    "id": "085A1908-8A08-4FED-8624-E10889EB74EB",
    "startDate": "2022-01-14T20:16:10.000Z",
    "endDate": "2022-01-14T20:36:10.000Z",
    "value": "biking",
    "unit": "activityType",
    "calories": 344,
    "distance": 9366,
    "sourceName": "Peloton",
    "sourceBundleId": "com.Peloton.PelotonApp"
  }

**Comment by dariosalvi78** [comment]
can you check if it is given back by the underlying HealthKit plugin?

**Comment by bmanderscheid** [comment]
Hi, thanks for the quick response:

Yes it appears it does (or at least what I've been able to stumble across with my limited ObjC skills.
I log **entry** in the **findWorkouts** method (in loop that's creating each entry to add to **finalResults**.

I get the following log for each entry in XCode (one entry):

{
    UUID = "B9EDF21E-28AF-4F93-9572-C3522ABB7B07";
    activityType = walking;
    distance = 1861;
    duration = 1200;
    endDate = "2022-03-14T15:47:56-05:00";
    energy = "243.791 G";
    sourceBundleId = "com.strava.stravaride";
    sourceName = Strava;
    startDate = "2022-03-14T15:27:56-05:00";
}

The log I posted in the original post is what I log when it comes back from PlugIn

**Comment by dariosalvi78** [comment]
If you say that it differs from the endTS-startTS then I wouldn't mind adding it. Would you feel brave enough to send a PR with that property added? all it needs is someting like `if (data[i].duration) res.duration = parseInt(data[i].duration);` after line 241 in health.js (or similar).

**Comment by bmanderscheid** [comment]
It can definitely be different. Not a lot but there's an Apple Watch case.  If the user forgets to END workout, the watch is smart enough to pause and ask if they want to end it.  If they dont see it till later (or MUCH later), it'll stamp the endDate when they accept to end it (not when it was paused). We've had it be off by hours.  In this case, the duration data is legit and we'd like to use that.  
It's in your documentation as a returned value too so I think it should be added.  I'll give it a shot!
