### ISSUE TITLE
How to set activity to "walking indoor" on iOS?

### ISSUE THREAD

**Issue by kitzler-walli** [dariosalvi78/cordova-plugin-health#253]
As iOS doesn't have an enumeration value for walking indoor - is it possible to set the activity to "walking indoor"?
The apple activity app is able to do so - but there seems to be an enum value missing in the API.

**Comment by dariosalvi78** [comment]
[doesn't look](https://developer.apple.com/documentation/healthkit/hkworkoutactivitytype?language=objc) like it's possible
