### ISSUE TITLE
Sleep data does not come if manually add it to google fit.

### ISSUE THREAD

**Issue by devqube** [dariosalvi78/cordova-plugin-health#254]
Hi, I'm trying to create a program that monitors sleep, but I had a problem that data comes from wearable devices, but if you add it directly to google fit, then it doesn't come.

**Comment by dariosalvi78** [comment]
that's weird... maybe it's because the API is now sort of split between a proper "sleep" data type and "activity". This is something in the TODO list, but help is welcome

**Comment by dariosalvi78** [comment]
probably related to #191

**Comment by dariosalvi78** [comment]
this may probably be solved now in release 2.1.0. @devqube please re-open if the bug is still there.
