### ISSUE TITLE
Application crashes when accessing data types that are not authorized on Android 12

### ISSUE THREAD

**Issue by randnetdd** [dariosalvi78/cordova-plugin-health#255]
We have confirmed the operation on Android 12 @ Pixel 6.

The application crashes when accessing an unauthorized data type on Android 12.

No problem with authorized data types.

The following error is output to logcat

```
AndroidRuntime: Shutting down VM
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: test, PID: 5201
AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace()' on a null object reference
AndroidRuntime:        at org.apache.cordova.health.HealthPlugin.lambda$store$3(HealthPlugin.java:1495)
AndroidRuntime:        at org.apache.cordova.health.-$$Lambda$HealthPlugin$AHgRCyIDCS8GLKbjV-2izt61rxE.onFailure(Unknown Source:2)
AndroidRuntime:        at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

I added the following code to the store / delete / disconnect and checked it, and I can see that err.getCause () is returning null.

    Fitness.getHistoryClient(this.cordova.getContext(), this.account)
      .insertData(dataSetBuilder.build())
      .addOnSuccessListener(r -> {
        callbackContext.success();
      })
      .addOnFailureListener(err -> {
        if (err == null) {
          Log.d(TAG, "err is null");
        } else if (err.getCause() == null) {
          Log.d(TAG, "err.getCause() is null");
        }
        err.getCause().printStackTrace();
        callbackContext.error(err.getMessage());
      });

`cordova-plugin-health: err.getCause() is null
`

**Environment information**

- Cordova CLI version 
	- 11.0.0
- Cordova platform version
	- android 10.1.1
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-health 2.0.3 "Cordova Health"

        
_Runtime issue_
- Device details
    - Pixel 6
- OS details
    - Android 12
	
_Android build issue:_	
- Node JS version
    - v14.17.4
- Gradle version
	- 7.1.1
- Target Android SDK version
	- 30
- Android SDK details
	- build-tools;30.0.3 | 30.0.3 | Android SDK Build-Tools 30.0.3
	- platforms;android-30 | 3 | Android SDK Platform 30

**Comment by dariosalvi78** [comment]
can you fix it and send a PR?

**Comment by dariosalvi78** [comment]
should be as simple as doing:

```java
if (err != null && err.getCause()) {
   err.getCause().printStackTrace();
}
```

**Comment by randnetdd** [comment]
Please check
