### ISSUE TITLE
cannot access AbstractSafeParcelable

### ISSUE THREAD

**Issue by fatihjoe** [dariosalvi78/cordova-plugin-health#26]
After I updated Andoid SDK the fallowing error showed up

Error : C:\...\android\src\org\apache\cordova\health\HealthPlugin.java:70: error: cannot access AbstractSafeParcelable
Error : public static Map<String, DataType> activitydatatypes = new HashMap<String, DataType>();
Error : class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found

**Comment by dariosalvi78** [comment]
It seems to me that you ahve a problem in your environment. It's not a plugin issue. Check the gradles, Google around, or simply restart the project from the scratch.

**Comment by array-addu** [comment]
Hi @dariosalvi78 
I want to know is it necessary to call promptInstallFit().As this install the Google fit App.

**Comment by dariosalvi78** [comment]
the whole idea of the plugin is to abstract Google Fit on Android (and HealthKit on iOS).
If you don't want to use Google Fit you don't want to use this plugin.

**Comment by array-addu** [comment]
@dariosalvi78 
Thanks for your reply.
So that means we need to install the app to get data like "STEP" count etc.
Actually i don't want to install any app to use fitness API.Is it possible without installing Google fit App

**Comment by dariosalvi78** [comment]
you can use the Google Fitness API even if the user doesn't have Google Fit installed, but there has to be some other fitness app putting data into the Fitness API otherwise your queries will always be empty.
Here's what [the original documentation](https://developers.google.com/fit/overview) says:

> The Google Fit app uses the Google Fit platform, which is included in Google Play services. Your fitness or wellness app can use the Google Fit platform without requiring users to install the Google Fit app.

**Comment by array-addu** [comment]
@dariosalvi78
can i use native andorid code for getting the step count if i don't use "fit App".I am not sure that this might be possible or not  but if you have any idea about this then, please let me know.
