### ISSUE TITLE
Samsung health connection

### ISSUE THREAD

**Issue by vinhcp** [dariosalvi78/cordova-plugin-health#260]
Hi guys, there's any support for samsung health connection at the moment?

**Comment by dariosalvi78** [comment]
there is not.
By the way, Google is launching a new API which will probably be used by all major vendors, including Samsung, but currently is not used by anybody, not even Google itself 😀

We may switch to the new API at some point, if and when it becomes established.

**Comment by vinhcp** [comment]
thanks fyi @dariosalvi78
