### ISSUE TITLE
health.isAvilable() return false when used with targetSDK 30 

### ISSUE THREAD

**Issue by Eslam2011** [dariosalvi78/cordova-plugin-health#262]
I tried used this plugin with targetSDK 29 thats works fine, but in targetSDK 30 not work, what the solution

**Comment by dariosalvi78** [comment]
unfortunately Android has changed and you need to add this permission in the manifest, see [this example](https://proandroiddev.com/how-to-get-users-installed-apps-in-android-11-b4a4d2754286)

**Comment by dariosalvi78** [comment]
we could add the change in the manifest xml programmatically [via config file](https://stackoverflow.com/questions/40446058/cordova-change-androidmanifest-using-config-xml-file).
Anyone up to the task?

**Comment by dariosalvi78** [comment]
am going to close all Google Fit related issues as this is discontinued
