### ISSUE TITLE
Distance data not matching from Apple Health App

### ISSUE THREAD

**Issue by jaiprakashmishrajipl** [dariosalvi78/cordova-plugin-health#263]
Hi,

I am using queryAggregated for distance, and for some day data is not matching with what I see in Apple Health App. Attached is the JSON response I am getting from queryAggregated, and also a screenshot what I see in Apple Health App.

Can someone help to figure out reason behind this? 

Note: Apple Health is capturing data from my Watch and from Phone also.

Thanks
Jai
![Apple Health Screenshot](https://user-images.githubusercontent.com/83004423/187392742-604b8b8c-1a4d-4e64-b71a-4f418cdb9f82.jpeg)
[Response.txt](https://github.com/dariosalvi78/cordova-plugin-health/files/9451311/Response.txt)

**Comment by dariosalvi78** [comment]
I think the issue is related to time, all your queries start at 6PM. Any idea why?

**Comment by jaiprakashmishrajipl** [comment]
I can't see starting at 6PM, 

e.g. for this data
`"startDate": "2022-08-14T18:30:00.000Z",
"endDate": "2022-08-15T18:30:00.000Z",
"value": 11526.77638256389,
"unit": "m"`

When I am converting to local time (IST) its showing start for the day
Mon Aug 15 2022 00:00:00 GMT+0530 (India Standard Time)

**Comment by dariosalvi78** [comment]
OK, sorry I have overlooked that it's in a different time zone. In this case I can't really say why this is happening, maybe the distance is computed from different sources and the plugin is combining them all, whereas the Health app does some clever merging? You could go and look at every distance contribution in a single day on the Health app and see if any combination matches what you get from the plugin. Let me know what you discover...

**Comment by dariosalvi78** [comment]
@jaiprakashmishrajipl  do you have any news about this issue?
