### ISSUE TITLE
[Question] Do Google Fit write permissions only need read permissions?

### ISSUE THREAD

**Issue by randnetdd** [dariosalvi78/cordova-plugin-health#267]
If requestAuthorization in Android specifies write-only permission, read permission is automatically added

Read permission is granted automatically with below code
https://github.com/dariosalvi78/cordova-plugin-health/blob/master/src/android/HealthPlugin.java#L458-L463
https://github.com/dariosalvi78/cordova-plugin-health/blob/master/src/android/HealthPlugin.java#L394-L399

Google Fit requires read permission to delete data, but read permission is not required for pure write only

Do you know why read permission is required?

**Environment information**

- Cordova CLI version 
	- 11.0.0
- Cordova platform version
	- android@10.1.2
- Plugins & versions installed in project (including this plugin)
     cordova-plugin-health 2.0.3 "Cordova Health"
        
_Runtime issue_
- Device details
    - Pixel 6
- OS details
    - Android 12	
	
_Android  build issue:_
- Node JS version
    - 14.17.4
- Gradle version
    - 7.1.1
- Target Android SDK version
    - 30

**Related code:**
```
navigator.health.requestAuthorization([
    {
        write : ['weight']
    }
], () => {
}, error => {
});
```

**Comment by dariosalvi78** [comment]
not sure what the question is, but we add read when write is requested because otherwise one cannot read data from other apps (see note in the code)
