### ISSUE TITLE
[Feature Request] Add identifier to data returned by Google Fit query

### ISSUE THREAD

**Issue by randnetdd** [dariosalvi78/cordova-plugin-health#268]
The reason why the identifier is necessary is that there is no AppPackageName in the Step Counter automatically generated by the Android device.
This is because it is not possible to know what generated the number of steps.

identifier can be obtained by getStreamIdentifier
https://developers.google.com/android/reference/com/google/android/gms/fitness/data/DataSource#public-string-getstreamidentifier

The identifier returned by each data is as follows

- Pixel 3a
raw:com.google.step_count.cumulative:Google:Pixel 3a:uid:Step Counter

- Pixel 6
raw:com.google.step_count.cumulative:Google:Pixel 6:uid:Step Counter

- Data manually entered from the Google Fit app
raw:com.google.step_count.delta:com.google.android.apps.fitness:user_input

- Data registered from individual applications
raw:com.google.step_count.delta:packageName:

You can get the data by adding the code in the line below
https://github.com/dariosalvi78/cordova-plugin-health/blob/master/src/android/HealthPlugin.java#L546-L549

          String identifier = dataSource.getStreamIdentifier();
          if (identifier != null) obj.put("identifier", identifier);

**Environment information**

- Cordova CLI version 
	- 11.0.0
- Cordova platform version
	- android@10.1.2
- Plugins & versions installed in project (including this plugin)
     cordova-plugin-health 2.0.3 "Cordova Health"
        
_Runtime issue_
- Device details
    - Pixel 3a / Pixel 6
- OS details
    - Android 10 / Android 13
	
_Android  build issue:_
- Node JS version
    - 14.17.4
- Gradle version
    - 7.1.1
- Target Android SDK version
    - 30

**Comment by dariosalvi78** [comment]
hi thanks for the suggestion. Doesn't `sourceBundleId` already give you this information?

**Comment by randnetdd** [comment]
This code sets the sourceBundleId to dataSource.getAppPackageName
sourceBundleId(getAppPackageName) returns null in Step Counter

**Comment by dariosalvi78** [comment]
can you add the following below line 548 and send a PR?

```java
else {
   String streamIdentifier = dataSource.getStreamIdentifier();
   if (streamIdentifier != null) obj.put("sourceBundleId", streamIdentifier);
}
```

**Comment by randnetdd** [comment]
Since the sourceBundleId is already set to the package name, it would be better to add it as a separate identifier to avoid confusion.
There may be a user who senses undefined and allocates it as a Step Counter

        DataSource dataSource = datapoint.getOriginalDataSource();
        if (dataSource != null) {
          String sourceBundleId = dataSource.getAppPackageName();
          if (sourceBundleId != null) obj.put("sourceBundleId", sourceBundleId);
          String identifier = dataSource.getStreamIdentifier();
          if (identifier != null) obj.put("identifier", identifier);
        }

If you like this content, I will send a PR

**Comment by dariosalvi78** [comment]
given that this is done as a backup in case the AppPackageName is not available, I would use it as a replacement for that instead of introducing a new property. Or do you see any reason why having both would be desirable?

**Comment by randnetdd** [comment]
sourceBundleId is the package name on iOS, such as com.apple.health.iPhone,
While manual input on Android returns a package name like com.google.android.apps.fitness

I was wondering if it is correct to return something other than the package name like raw:com.google.step_count.cumulative:Google:Pixel 6:uid:Step Counter

If you don't mind receiving a response other than the package name, I think there is no problem setting it to sourceBundleId

**Comment by dariosalvi78** [comment]
I think that it's OK to keep it as sourceBundleId even though it's a bit more than that. The idea is to give the application an indication of where this data comes from, and the stream identifier is perfect for that. Maybe we can specify this in the README just to make it clear

**Comment by randnetdd** [comment]
OK, I'll submit a PR.
My English is inaccurate, so I would like the README to be written by someone who can speak English.
