### ISSUE TITLE
How to query for sleep on Android

### ISSUE THREAD

**Issue by dlandtaa** [dariosalvi78/cordova-plugin-health#270]
How do we query for sleep information on Android? Do we use the `activity` type or the `sleep` type?

 Using `activity` works fine on iOS but for Android I get the error

```
5000: Application needs OAuth consent from the user
```

I have added the Fitness API in the developer console and I have added the

```
.../auth/fitness.activity.read
.../auth/fitness.sleep.read
```
scopes to the OAuth consent screen.

If I use `sleep` I don't get any errors on Android but the array returned is empty. I have manually entered some sleep data into the Fit app on my phone.

**Comment by dariosalvi78** [comment]
at the moment sleep works only on iOS, use activity on Android. This is going to change soon because the Fit API has now separated sleep from activity.

**Comment by dlandtaa** [comment]
Okay, this still isn't clear to me. I finally got past the `Application needs OAuth consent from the user` by including the the `calories` and `distance` types along with `activity` in the request for authorization. I have no idea why we are required to ask for calories and distance data in order get unrelated activities but whatever, googles be crazy.

Anyway, I can now successfully pull activity data from my phone (as entered into the Fit app), however sleep is not one of the activities listed. I can do walking, swimming, mixed martial arts, all kinds of things, but not sleep. So if I'm supposed to use `activity` to get the sleep data, how do I enter it into my phone?

![Screenshot_20221120-135405](https://user-images.githubusercontent.com/89596857/202923402-c0eb2330-b916-487f-9a06-a939faab3119.png)

The Fit app lets me record sleep data outside of the activity data but when I do that, my queries are empty.

![Screenshot_20221120-135346](https://user-images.githubusercontent.com/89596857/202923490-27e82b9b-a25d-4314-8583-257578d56f80.png)

Note that when I query for 'sleep' I do get an oAuth consent screen telling the user the app wants access to their sleep data.

![Screenshot_20221120-141411](https://user-images.githubusercontent.com/89596857/202924110-6cbd32a7-ee12-415c-b231-680a142fca32.png)

So, somebody, anybody, please help me understand this. How can I query sleep data??

This is my code:

```
import { createApp } from 'vue'
import App from './App.vue'

document.addEventListener('deviceready', go, false);

function go() {
    navigator.health.requestAuthorization(
        [{ read: ['calories', 'distance', activity, 'sleep'] }],
        () => {
            navigator.health.query(
                {
                    startDate: new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000),
                    endDate: new Date(),
                    // 'sleep' gives empty array, 'activity' works but apparently sleep is not a valid activity
                    dataType: 'sleep',
                    limit: 1000
                },
                data => {
                    console.log(data);
                },
                err2 => {
                    console.error(err2);
                }
            );
        },
        err => {
            console.error(err);
        }
    );

    createApp(App).mount('#app');
}
```

**Comment by dariosalvi78** [comment]
1. calories and distance are added because on iOS they are returned associated to each activity. This was done to make both APIs equal, but I want to change it in the future and make this optional.
2. the Fit API has been changing in the last year or so and now "sleep" has been made into a separate quantity, so, depending on the app, you may find it within acivity still or in its own sleep data type. It's likely that the Fit app uses the new sleep data type, but this plugin does not suport the separate sleep data yet, which is why you don't get it within activity.

I am working on updating the plugin but I am very busy and it's being slow. If anybody here with Android programming experience wants to help I would be grateful.

**Comment by dlandtaa** [comment]
Aha, okay, now I see how it works. So I should be able to create my own cordova app that writes sleep data as an activity and use another app to read that data, correct? Just so I can see what the data looks when a query actually works?

**Comment by dariosalvi78** [comment]
to test it you can use the same app to read and write, no need to create another app. The way I do it is to open up the debugger (crhome://inspect) and issue the commands directly on the JS console. No need to develop any UI at all.

**Comment by dlandtaa** [comment]
Hey @dariosalvi78 all my android devices use the newer style where sleep is no longer an activity. Do you have any suggestions on ways to test it with the older activity style? I tried downloading an old version of the Google Fit from apkmirror.com but no luck. It still returns sleep as its own metric rather than an activity.

**Comment by dlandtaa** [comment]
FYI, I got this to work by doing a factory reset on the phone.

**Comment by dariosalvi78** [comment]
I am not sure I understand it. If you want to use an older version of the plugin, just install it in your source code with the @ version (see [npm i](https://docs.npmjs.com/cli/v6/commands/npm-install)).

If you want to test a version of Android where sleep was included in activity then I guess you need to find an Android version old enough. See [Google Play Services versions](https://developers.google.com/android/guides/releases), the sleep activity was deprecated already in October 2020.

**Comment by dlandtaa** [comment]
Sorry for not clarifying, I was interested in installing and older version of Android not the plugin. I have a fairly old phone so just doing a factory reset was enough to get it to work.

**Comment by dariosalvi78** [comment]
interesting to see that older Android versions still send sleep data through activity, it may be worth mentioning it in the README. Feel free to send a PR for that!

**Comment by dlandtaa** [comment]
I'd be glad to update the README.

Does the plugin have a way of reporting which version of the Fit API it's currently working with? It would be nice if the client code could know whether or not to use the old or new style for querying sleep information. Right now I'm putting a `try/catch` block around the query for the new sleep metric and falling back to the activity query if it throws an error.

**Comment by dariosalvi78** [comment]
yeah, that sounds like a great idea. There are [ways to do it](https://stackoverflow.com/questions/18737632/how-to-check-google-play-services-version). Maybe you want to send a PR for that too ? 😄

**Comment by dariosalvi78** [comment]
yes, it would be ideal form the programmer's perspective but very hard in practice. It would mean requesting authorization for different data types depending on the API version, which may be confusing for the user. Considering that the Fit API is going to be phase out, I would not invest too much on it TBH, knowing the API version would probably be enough.
