### ISSUE TITLE
Google Fit Authorization is failing when app is uploaded in play store but working on debug mode

### ISSUE THREAD

**Issue by fugeneral** [dariosalvi78/cordova-plugin-health#271]
Unable to get Health steps when APK downloaded from PlayStore
Capacitor 2.0
ionic 4
health plugin 2.0.5
OAuth Consent screen is verified already

this.health.isAuthorized([
  'steps', //read and write permissions
    {
      read: ['steps'],       //read only permission
      write: []  //write only permission
    }        
])
.then((auth:any) => {
  console.log('isAuthorizedCheck_fit_for_Android =',auth);
  if(!auth) { //alert('if') 
    //this.getHealthData_check();//alert('else')
   if(this.watchyourhealth.oneTimePOPupGFIT){
        this.watchyourhealth.oneTimePOPupGFIT = false;
    this.signInGoogleDialog = true;
   }
  }
   else{this.getHealthData_check();//alert('else')
  }
})

**Comment by dariosalvi78** [comment]
development app and release app have a different SSH identifier. Make sure the Google APIs have both.

**Comment by jomihepo** [comment]
Cordova 8.1
ionic 3
Healh plugin 2.0.5


 this.health.query({
                startDate: new Date(new Date().getTime() - 365 * 24 * 60 * 60 * 1000),
                endDate: new Date(),
                dataType: 'distance'
            }).then(res => {
                console.log(res);
            }).catch(e => console.log(e));

Application needs OAuth consent from the user

**Comment by fugeneral** [comment]
Hi, Thanks for your reply.
attaching below Screenshots for reference.
we added both SHA in the OAuth client.
Still unable to access Steps.  below is some code snipet added with output
---------------------------------------------------
**_this.health.isAuthorized([
  'steps', //read and write permissions
    {
      read: ['steps'],       //read only permission
      write: []  //write only permission
    }        
])
.then((auth:any) => {
  console.log('isAuthorizedCheck_fit_for_Android =',auth);_**
--------------------------------------------------
**isAuthorizedCheck_fit_for_Android = false**


<img width="198" alt="image" src="https://user-images.githubusercontent.com/118807766/205624827-f10316bb-d013-4f56-8f6f-a9626419e322.png">

<img width="741" alt="image" src="https://user-images.githubusercontent.com/118807766/205625001-b86d101d-f22a-47f2-a301-2348267ca16e.png">

**Comment by fugeneral** [comment]
can you provide setup document for same.
i think something is missing?

**Comment by dariosalvi78** [comment]
I cannot provide documentation for Google Fit cloud, there is enough documentation provided by Google
