### ISSUE TITLE
HealthConnect Android

### ISSUE THREAD

**Issue by MrJustreborn** [dariosalvi78/cordova-plugin-health#273]
Are there any attempts to implement the new HealthConnect API on Android?

**Comment by dariosalvi78** [comment]
not yet, but the Google Fit API is going to be deprecate next year and this plugin will need to migrate to HealthConnect. My understanding is that the new API is more similar to HealthKit, which removes the need for the absurd verification of the app by Google and makes everything more sane and coherent, so I am very happy about it. The issue is that very few apps use the new API still.

**Comment by MrJustreborn** [comment]
I'm currently creating an app which uses (more wants to use) it. 
I haven't yet decided what framework to use (nativescript/ionic/etc), since no framework supports it.

And you're right, it's very similar to apple healthkit, you just have to request permission and can read/write health data. (The neat part is, every app can potentially write to it, so it's not limited to GoogleFit)

**Comment by dariosalvi78** [comment]
From what I've seen, the API is also similar to Fit, at least the data types, which means that the transition shouldn't be too painful.

If you go for an hybrid app and want to try extending this plugin to support HealthConnect, I would definitely your PRs  😉..

**Comment by MrJustreborn** [comment]
I would at least try 😅
I'm not very experienced in native android code and plugin development.

**Comment by nijakobius** [comment]
This would be so great to see! :)

**Comment by MrJustreborn** [comment]
I tried it, but it's currently not possible. Google HealthConnect needs at least API-Level 33 but this seams not to work in my current setup (I use ionic with capacitor, the current API-Level supported is 32)

**Comment by dariosalvi78** [comment]
@MrJustreborn if you have some native code to look at, maybe you can post it somewhere?

**Comment by MrJustreborn** [comment]
I used your project as base and added the Google Health Connect dependency. I did not write much code except to check if it's available (https://developer.android.com/guide/health-and-fitness/health-connect/get-started).

But the project did not even compile because of the api-level.

**Comment by cgtarmenta** [comment]
👀

Is there any progress on this?

**Comment by dariosalvi78** [comment]
I wish I had time to work on this!

**Comment by rvcarlig** [comment]
Is there any progress on this?

**Comment by MrJustreborn** [comment]
No progress on my side, but thanks for the info! - I have to finish my project first (currently using google fit). But I have to update to the latest cordover version anyways, then I can look into it again.

**Comment by dariosalvi78** [comment]
hello, you may be happy to know that I am working on this, see branch "healthconnect". A big warning: Google Fit wil be discontinued after this.

**Comment by yonatancohen** [comment]
any news about health connect?

**Comment by dariosalvi78** [comment]
@yonatancohen  have you bothered checking this repo in the last month? 😃

**Comment by yonatancohen** [comment]
hi @dariosalvi78 , I just realized that you added support.
However I'm having issue while trying to connect on ios I'm getting "plugin_not_installed".

I installed:
"cordova-plugin-health": "^3.0.1"  AND
"@awesome-cordova-plugins/health": "^6.6.0"

**Comment by dariosalvi78** [comment]
avoid using awesome-cordova-plugins/health, it's not updated

**Comment by yonatancohen** [comment]
So how can I use it in Ionic project?

**Comment by dariosalvi78** [comment]
just use it directly without any wrapper. Install it, as you would install any other cordova plugin, and call the API directly using the cordova.plugins.health object.

Make sure you go through the configuration steps described in the README.

**Comment by rengadevigg** [comment]
hyyy you gyz have any idea that health connect permission request cancelled multiple times, it gets locked out so can you have any and android does not return any denied state it just's returns permission granted list or empty thats it.
do you have any idea to conclude that user has denied permission?

**Comment by dariosalvi78** [comment]
@rengadevigg I am not sure what you mean, can you elaborate?
Permissions are dealt in: https://github.com/dariosalvi78/cordova-plugin-health/blob/24834c4b721b832a8c29c0316a0ce605e8884b00/src/android/HealthPlugin.java#L111-L127

if no permissions are set, the result should be empty AFAIK.

**Comment by rengadevigg** [comment]
what if permissions denied how do i know permission denied count and also health connect permission request screen gets locked out if we cancelled more than two times. how do you handled?
for reference scenario refer below link please
https://issuetracker.google.com/issues/236299803#comment6
https://issuetracker.google.com/issues/233239418?pli=1

**Comment by dariosalvi78** [comment]
I wasn't aware of this issue on Android. It's definitely a problem and, as you can see from the discussion, not something we can fix ourselves. The only solution I can think of is to check if permissions are granted, and, if not, launch the HealthConnect app and ask the user to give permissions manually, which is pretty bad from the user experience perspective.

I will add a note on README about this.

**Comment by rengadevigg** [comment]
Sure. Please let me know if you found any work around on this.
