### ISSUE TITLE
Property 'disconnect' does not exist in type 'HealthOriginal'

### ISSUE THREAD

**Issue by blazekyo** [dariosalvi78/cordova-plugin-health#274]
running npm install @awesome-cordova-plugins/health in a capacitor-react project.
coudn't find any disconnect method even for android use.

**Comment by blazekyo** [comment]
Even in ios, how do I allow users to switch into different google accounts for health data analysis.
Say switching into a different google fit account?
I've tried recall requestAuthorization again it doesnt word,
I've tried export the HealthOriginal class, and create a new Health object then call requestAuthorization, also doesn't work,
The only way that works is to clear app data.
Any workaround?

**Comment by dariosalvi78** [comment]
this plugin connects to HealthKit in iOS not Google Fit, and Healthkit is linked to the Apple account only, there is no way to switch account

**Comment by blazekyo** [comment]
How about accessing different google accounts in android?  The user can't switch their google account after first time authorized in the health plugin?

**Comment by dariosalvi78** [comment]
one has to disconnect and then re-connect (re-request authorization).
Please be aware that there may be an issue related to this, see https://github.com/dariosalvi78/cordova-plugin-health/issues/141

**Comment by blazekyo** [comment]
please not that 'disconnect' method does not exist in HealthOriginal when I tries to call 'disconnect' method in my ionic - capacitor - react project.
