### ISSUE TITLE
Capacitor Health Plugin not able to connect to Google Fit

### ISSUE THREAD

**Issue by ChandraKAV** [dariosalvi78/cordova-plugin-health#276]
Capacitor Health plugin not able to connect to Google Fit. Initially it did work and we could fetch data from Google Fit. Later it started throwing the following error.

**com.google.android.gms.common.api.ApiException: 4: The user must be signed in to make this API call**

I am connected through a real device (Redmi 11 Prime - Android 12) and am already signed in.
Could any one shed some light on what could be going wrong? Tried all solutions that members suggested on stackoverflow, without any luck.

Here is my Ionic info:

**Ionic**:

Ionic CLI : 6.20.8 (/Users/iosdev/.nvm/versions/node/v16.17.0/lib/node_modules/@ionic/cli)
Ionic Framework : @ionic/angular 6.3.3
@angular-devkit/build-angular : 14.2.7
@angular-devkit/schematics : 14.2.7
@angular/cli : 14.2.7
@ionic/angular-toolkit : 6.1.0

**Capacitor**:

Capacitor CLI : 4.4.0
@capacitor/android : 4.4.0
@capacitor/core : 4.4.0
@capacitor/ios : 4.4.0

**Utility**:

cordova-res : 0.15.4
native-run : 1.7.1

**System**:

NodeJS : v16.17.0 (/Users/iosdev/.nvm/versions/node/v16.17.0/bin/node)
npm : 8.15.0
OS : macOS

Please help. Ionic support suggested that I raise this issue on the plugin.

**Comment by dariosalvi78** [comment]
the error message is quite explanatory?

**Comment by ChandraKAV** [comment]
Yes. it is explanatory. But I am already signed in, but plugin says am not.

**Comment by dariosalvi78** [comment]
make sure you call requestAuthorization() before doing any query. This is needed every time you start the app, even if the authorization was already received in the past. Hope this solves it.

**Comment by ChandraKAV** [comment]
Nope. Still have the same problem. 😔

Sent with Spark

**Comment by dariosalvi78** [comment]
my suggestion is to debug opening chrome://inspect or whatever capacitor gives you as an option and run the queries inside a console. Also, make sure there is no incompatibility with other plugins. I am not aware of any, but if you notice something let me know and I will document it.

**Comment by ChandraKAV** [comment]
> my suggestion is to debug opening chrome://inspect or whatever capacitor gives you as an option and run the queries inside a console. Also, make sure there is no incompatibility with other plugins. I am not aware of any, but if you notice something let me know and I will document it.

okay .. will try it out!

**Comment by derciesto** [comment]
yes, it works in the console as expected. but not in the application 

`health.isAuthorized` return always false in the application 

so is issue with any app configuration or anything we missed?

**Comment by derciesto** [comment]
@dariosalviwork but when I run the code of the application to get data after that  using the console not able to get data 
again throw the same error 
`com.google.android.gms.common.api.ApiException: 4: The user must be signed in to make this API call.
`

**Comment by derciesto** [comment]
@dariosalvi78 hi I found the bug related to the permission

when we ask any below permission

`activity,blood_pressure,heart_rate,blood_glucose,oxygen_saturation`
`health.isAuthorized` is return **false** also same is in console.

**Comment by ChandraKAV** [comment]
@dariosalvi78 @derciesto  thank you for your help in this regard. We are now getting data from Google fit successfully in the app also. I removed the _isAuthorized_ call and added write permissions for couple of data types. Also, calling _requestAuthorization_ call every time a call to Google Fit API.
