### ISSUE TITLE
Paging on query

### ISSUE THREAD

**Issue by dested** [dariosalvi78/cordova-plugin-health#28]
I am having an issue getting all the data back from the query method on iOS. It only returns me the first handful of results for a day rather than the whole payload. Is there a way to "page" the data to retreive the rest of it?

**Comment by dariosalvi78** [comment]
the only way to page the request is to make multiple requests with different dates.

**Comment by alx-andru** [comment]
I actually have the same issue. Even though I query the entire day I receive only the last 100 datapoints.

**Comment by dariosalviwork** [comment]
well spotted!

I'll try to get rid of this at the next iteration.
