### ISSUE TITLE
disconnect possibly not working

### ISSUE THREAD

**Issue by dlandtaa** [dariosalvi78/cordova-plugin-health#282]
I am attempting to disconnect my app from Google Fit by calling the `disconnect()` method but afterward I am still able to successfully query for data. The result of the call to `disconnect` is `true` but queries still work. Is this expected?

The only way I am able to actually disconnect my app from google fit is by opening the app settings and up and turning off the "body sensors" permission, if that's available.

<img width="400px" src="https://user-images.githubusercontent.com/89596857/229604707-dd26851e-e7aa-4d94-8602-b3dcc0d63c12.png">

When I do this, the app reboots and I have to reconnect before getting access to data again.

It seems like some data types heart_rate show up in the OS permission dialog for the app and some like steps do not. If I do steps alone I basically cannot disconnect the app from google fit at all because there's no OS button to do it the plugin doesn't seem to want to.

As a side note, I also noticed that if I request read access to one metric I get access to others. For example, I can ask for access to steps but get access to heart_rate. Not sure if that's expected but just FYI.

I created a [repo that shows these behaviors](https://github.com/dlandtaa/health-plugin-disconnect-issue.git) if you want to check it out.

**Comment by dariosalvi78** [comment]
the disconnect calls [this](https://developers.google.com/fit/android/disconnect). This should, according to documentation, remove OAuth access to the API. If that's not the case I would blame the Fit API, because the plugin just follows the documentation.

The screenshot you show here is not the right place where to revoke permissions. Those are OS-levek permissions, NOT Fitness API permissions. You should look at the Google Play Services configuration.

This also explains why you don't see steps there and why you can query heartrate.

**Comment by dariosalvi78** [comment]
this is I get to the Google Fit API permissions on my phone:

![image](https://user-images.githubusercontent.com/5367037/230887534-49854c7a-c108-4b10-a49d-de650493dc32.png)

![image](https://user-images.githubusercontent.com/5367037/230887562-9d1d199d-3b40-4a61-bde1-dd0fd19fe765.png)

![image](https://user-images.githubusercontent.com/5367037/230887580-2bb67c7b-9a45-4185-a47d-a4a93948da3c.png)

![image](https://user-images.githubusercontent.com/5367037/230887596-ea090bd0-5fcf-4620-b57f-83b50258b5de.png)

![image](https://user-images.githubusercontent.com/5367037/230887641-f4f7eac7-9c21-4a79-bdb3-472ba352ca29.png)

![image](https://user-images.githubusercontent.com/5367037/230887657-7d40c2a0-e51e-4b11-9368-afab307685f4.png)

**Comment by dlandtaa** [comment]
Okay, thank you for the pointers, I appreciate it. The behavior I'm seeing is still pretty odd though. Even if I go into the google settings and explicitly remove my app from the list of Google Fit connected apps I can still access the health data through this plugin. I'm curious if anyone else has observed that behavior.

**Comment by BenLaKnet** [comment]
Hi,

I tried to remove access in Google Fit properties, but It meens that authorizations are not deleted.

After when I tried to "disconnect", I obtain disconnected==false.

**Comment by dariosalvi78** [comment]
you can try to disconnect the app using the Google Account on Android, you can disconnect apps there too.
