### ISSUE TITLE
Bug inputs type file do not process files

### ISSUE THREAD

**Issue by LushoKratz** [dariosalvi78/cordova-plugin-health#284]
when i run  requestAuthorization function, in my ionic angular app works well, but when i select inputs type file, and i choose a file in one of them i dont get the file, but when i delete requestAuthorization from my typescript component file, i can select files in my inputs type file, in the same component or in other components happens the same!

My question is, if requestAuthorization keeps running in background? or how can i avoid this issue or destroy the running background process when i navigate to other component

**Comment by dariosalvi78** [comment]
there is no "run in background" in javascript, as everything runs on one thread. Please check your code carefully, there may be a bug somewhere?

**Comment by LushoKratz** [comment]
it works in ios, but in android it also works but after running any query or request of this plugin, i cant get files of an input type file.

in html 

<input type="file" (change)="handleFileInput($event)">
#########################################################

in .ts file 

handleFileInput(event: any) {
    const file = event.target.files[0];
    console.log(file);
  }
#########################################################

this is one of the requests function im using, after executing this one it wotks, i can receive data of google fit, and i also can request activity permission and get datatype of activity and steps from user.

this.health.requestAuthorization(['activity', {
      read: ['steps', 'calories']
    }]);
 #########################################################
 
but after executing any query of this plugin if i want to get files from input type file i don't get file loaded in function and input type file doesn't get file
 
 Do you have any idea whats happening? 
 
I am using a capacitor and im using next:

 Ionic 6
Angular 15
Android 12

 Plugins: 
health"@ionic-native/health": "^5.36.0",
health"cordova-plugin-health": "^2.1.0",

**Comment by dariosalvi78** [comment]
I think you have an issue with scope. Callbacks called from Cordova plugins come within a strange scope, make sure you have access to all the variables you need.

**Comment by LushoKratz** [comment]
I'm not getting the idea of the strange scope, do you mean the way cordova works? 
I'm using @awesome-cordova-plugins/core v6.3. to integrate cordova plugins in my capacitor project.

If we requestAuthorization since start and user sign in with plugin pop-up google sign in window, user can obtain data and file inputs works correctly.
But when i kill the app and i enter the app again, inputs type file gets this same error.

Another problem is that if we signin users with 'capacitor-google-auth' plugin, and after we requestAuthorization, user can allow activity permissions and get data from google fit, but inputs doesnt work correctly cause when i select a file, input file never obtain file and android file manager crash.

Do you think we have to send any scope in this plugin to sign in users?
Why do you consider I present this error?

**Comment by dariosalvi78** [comment]
from what you tell here it may be related to Capacitor? I really have no idea.
My suggestion is always try to remove as much complexity as possible. Start from an empty app and add _only_ those parts that don't work and see if you can reproduce the problem. When I say _only_ , I mean *ONLY*, that is, no JS framework, no fancy CSS, just pure HTML and as little JS as possible.
