### ISSUE TITLE
Exception during ios execution (hk_isValidPurposeString: unrecognized selector sent to instance)

### ISSUE THREAD

**Issue by bnemani** [dariosalvi78/cordova-plugin-health#285]
I am getting the following exception while running in ios simulator. please let me know if anyone ran into this:

023-05-23 02:01:46.293640+0530 App[19652:216373] Requesting write permission for HKQuantityTypeIdentifierHeight
2023-05-23 02:01:46.293708+0530 App[19652:216373] Requesting write permission for HKQuantityTypeIdentifierBodyMass
2023-05-23 02:01:46.295247+0530 App[19652:216373] -[__NSCFBoolean hk_isValidPurposeString]: unrecognized selector sent to instance 0x1bbd878b8
2023-05-23 02:01:46.298851+0530 App[19652:216373] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean hk_isValidPurposeString]: unrecognized selector sent to instance 0x1bbd878b8'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180437330 __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180051274 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000180445e3c +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x000000018043b224 ___forwarding___ + 1308
	4   CoreFoundation                      0x000000018043d50c _CF_forwarding_prep_0 + 92
	5   HealthKit                           0x000000018edb8b74 -[HKHealthStore _validateHealthDataPurposeStringsForSharingTypes:readingTypes:isResearchStudy:] + 376
	6   HealthKit                           0x000000018edb87c8 -[HKHealthStore _validatePurposeStringsForSharingTypes:readingTypes:] + 284
	7   HealthKit                           0x000000018edb819c -[HKHealthStore requestAuthorizationToShareTypes:readTypes:shouldPrompt:completion:] + 308
	8   CordovaPlugins                      0x00000001052b9a04 -[HealthKit requestAuthorization:] + 1728
	9   Capacitor                           0x000000010544a378 $s9Capacitor0A6BridgeC19handleCordovaJSCall4callyAA0E0V_tF + 2452
	10  Capacitor                           0x00000001054bd81c $s9Capacitor24WebViewDelegationHandlerC21userContentController_10didReceiveySo06WKUsergH0C_So15WKScriptMessageCtF + 5272
	11  Capacitor                           0x00000001054bd988 $s9Capacitor24WebViewDelegationHandlerC21userContentController_10didReceiveySo06WKUsergH0C_So15WKScriptMessageCtFTo + 68
	12  WebKit                              0x00000001085e1658 _ZN28ScriptMessageHandlerDelegate14didPostMessageERN6WebKit12WebPageProxyEONS0_13FrameInfoDataERN3API12ContentWorldERN7WebCore21SerializedScriptValueE + 220
	13  WebKit                              0x000000010890490c _ZN6WebKit29WebUserContentControllerProxy14didPostMessageEN3WTF16ObjectIdentifierINS_26WebPageProxyIdentifierTypeEEEONS_13FrameInfoDataEyRKNS1_4SpanIKhLm18446744073709551615EEEONS1_17CompletionHandlerIFvOS9_RKNS1_6StringEEEE + 552
	14  WebKit                              0x0000000108bdefcc _ZN3IPC18handleMessageAsyncIN8Messages29WebUserContentControllerProxy14DidPostMessageEN6WebKit29WebUserContentControllerProxyES5_FvN3WTF16ObjectIdentifierINS4_26WebPageProxyIdentifierTypeEEEONS4_13FrameInfoDataEyRKNS6_4SpanIKhLm18446744073709551615EEEONS6_17CompletionHandlerIFvOSE_RKNS6_6StringEEEEEEEvRNS_10ConnectionERNS_7DecoderEPT0_MT1_T2_ + 616
	15  WebKit                              0x0000000108bded50 _ZN6WebKit29WebUserContentControllerProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 76
	16  WebKit                              0x0000000108c2bfe4 _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 224
	17  WebKit                              0x000000010888ce70 _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 36
	18  WebKit                              0x0000000108c28210 _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 640
	19  WebKit                              0x0000000108c28570 _ZN3IPC10Connection24dispatchIncomingMessagesEv + 460
	20  JavaScriptCore                      0x0000000106420958 _ZN3WTF7RunLoop11performWorkEv + 172
	21  JavaScriptCore                      0x0000000106421570 _ZN3WTF7RunLoop11performWorkEPv + 32
	22  CoreFoundation                      0x000000018039ac6c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
	23  CoreFoundation                      0x000000018039abb4 __CFRunLoopDoSource0 + 172
	24  CoreFoundation                      0x000000018039a324 __CFRunLoopDoSources0 + 232
	25  CoreFoundation                      0x0000000180394958 __CFRunLoopRun + 748
	26  CoreFoundation                      0x0000000180394254 CFRunLoopRunSpecific + 584
	27  GraphicsServices                    0x0000000188eb7c9c GSEventRunModal + 160
	28  UIKitCore                           0x0000000116caeff0 -[UIApplication _run] + 868
	29  UIKitCore                           0x0000000116cb2f3c UIApplicationMain + 124
	30  App                                 0x0000000104d17d1c main + 64
	31  dyld                                0x0000000105039514 start_sim + 20
	32  ???                                 0x0000000104e0df28 0x0 + 4376813352
	33  ???                                 0x6741000000000000 0x0 + 7440228059392770048
)
libc++abi: terminating due to uncaught exception of type NSException

**Comment by dariosalvi78** [comment]
what was the query?

**Comment by dariosalvi78** [comment]
have you added the reason for using HealthKit? see README. Closing for lack of feedback but let me know if the issue is still around.
