### ISSUE TITLE
disconnect not available?

### ISSUE THREAD

**Issue by ChandraKAV** [dariosalvi78/cordova-plugin-health#286]
health.disconnect() does not seem to be available anymore! When I try to use it Visual Studio Code gives the following error:

`Property "disconnect" does not exist on type "Health".`

What seems to be the issue here? Is there an alternative?

**Comment by dariosalvi78** [comment]
it's [there](https://github.com/dariosalvi78/cordova-plugin-health/blob/afb28bdb6e9f4d45686fd0727ecb112a28cd4bdb/www/android/health.js#L11) but [only for Android](https://github.com/dariosalvi78/cordova-plugin-health/blob/master/README.md#disconnect---android-only).

**Comment by ChandraKAV** [comment]
I am trying to use the Cordova plugin with Ionic framework, like below. 

`import { Health, HealthQueryOptions } from '@awesome-cordova-plugins/health/ngx';`

This seems to the referencing a HealthOriginal class that does not contain disconnect property.

> it's [there](https://github.com/dariosalvi78/cordova-plugin-health/blob/afb28bdb6e9f4d45686fd0727ecb112a28cd4bdb/www/android/health.js#L11) but [only for Android](https://github.com/dariosalvi78/cordova-plugin-health/blob/master/README.md#disconnect---android-only).
