### ISSUE TITLE
[iOS] requestAuthorization won't bring up the permission modal on a device 

### ISSUE THREAD

**Issue by jindrichgorner** [dariosalvi78/cordova-plugin-health#288]
When trying to run an app on a device, calling requestAuthorization won't do anything. This all works fine on simulator but once I put it on the device, calling requestAuthorization has no effect, none of the callbacks are firing. 

"2023-06-19 18:28:46.189262.... Requesting read permissions for HKQuantityTypeIdentifierStepCount"

I can see these logs popping out in the console window. 

iOS that I use on my device is 16.5. 

Any idea?

**Comment by dariosalvi78** [comment]
have you enabled Healthkit on your app? See https://support.spotme.com/hc/en-us/articles/360043827513-How-to-enable-HealthKit-on-your-app

**Comment by jindrichgorner** [comment]
all that was done... it turned out I just had to turn off my phone and turn it back on. Sorry for this! Closing this thread
