### ISSUE TITLE
Error : The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#289]
Hi,

I obtain error when installing plugin : 

Installing "cordova-plugin-health" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-health" for electron
Adding cordova-plugin-health to package.json
config file undefined requested for changes not found at Developpement\PhoneGap\Glucko\platforms\android\undefined, ignoring
config file undefined requested for changes not found at Developpement\PhoneGap\Glucko\platforms\android\undefined, ignoring
The "path" argument must be of type string. Received undefined

Could you please help me ?
Is this possible to not install plugin for electron if that is the problem ?

When compiling project : 

cordova run android --debug -- --buildConfig build.json
config file undefined requested for changes not found at Developpement\PhoneGap\Glucko\platforms\android\undefined, ignoring
config file undefined requested for changes not found at Developpement\PhoneGap\Glucko\platforms\android\undefined, ignoring
The "path" argument must be of type string. Received undefined

**Comment by dariosalvi78** [comment]
this plugin is for Android and iOS, no support for electron

**Comment by BenLaKnet** [comment]
Is this possible to install plugin or compile project without removing electron ?

**Comment by dariosalvi78** [comment]
I really have no idea, I don't use PhoneGap and I have never run into this issue. To me this looks like some problem with your file system or with PhoneGap rather than an issue with the plugin, see the `\platforms\android\undefined`.

**Comment by BenLaKnet** [comment]
I use cordova.

Ok, When I removed "electron", the message is just a warning, no problem to compile,

Thanks.

**Comment by BenLaKnet** [comment]
I use cordova for android in PC and ios on a mac.
Now when I try to deploy plugin in Mac I have this message :

```
cordova build ios           
config file undefined requested for changes not found at /Users/ben/Documents/phonegap/Glucko/platforms/ios/undefined, ignoring
config file undefined requested for changes not found at /Users/ben/Documents/phonegap/Glucko/platforms/ios/undefined, ignoring
The "path" argument must be of type string. Received undefined
```

**Comment by BenLaKnet** [comment]
I have to delete that in config.xml to deploy in iOS : 

> ```
<config-file platform="ios" parent="NSHealthShareUsageDescription">
  <string>App needs read access</string>
</config-file>

<config-file platform="ios" parent="NSHealthUpdateUsageDescription">
  <string>App needs write access</string>
</config-file>
```
