### ISSUE TITLE
Disconnect and Reconnect

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#290]
I tried disconnect method, 

But when I tried to reconnect, it is not possible, I obtain this message :  

cannot disconnect,4: The user must be signed in to make this API call.
or
com.google.android.gms.common.api.ApiException: 4: The user must be signed in to make this API call.

or a cancelled message if I want to stop process and no possibility to reconnect after.

I want to make video fo Google API Authorization.

There is a "flush" authorization process in Google API ?

**Comment by dariosalvi78** [comment]
I don't understand this issue, can you describe the sequence of actions so that one can reproduce them?
My understanding is that you (successfully?) called the disconnect() function and after that you called the requestAuthorization() function and you got an error message about disconnect?

**Comment by BenLaKnet** [comment]
Yes, it is that.

**Comment by BenLaKnet** [comment]
OK, I had to uninstall and reinstall the app.

Sorry to bother you.
