### ISSUE TITLE
Android version 12 : Permission denied: android.permission.ACCESS_FINE_LOCATION

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#291]
Hi,

I have this error message when I try to authorize app to connect to google fit : 
Permission denied: android.permission.ACCESS_FINE_LOCATION

It is a problem in app/plugin or in the phone rules ?

May I add this code : 

```
cordova.plugins.diagnostic.isLocationAuthorized(function(authorized){        
					if (authorized) {
						navigator.health.isAuthorized(datatypes, successisAuthCB, errorCB);
					}
				});
```

**Comment by dariosalvi78** [comment]
location is needed with some data types, the rquestAuthorization() should take care of that. What data types are you trying to access?

**Comment by BenLaKnet** [comment]
Ok, I tried with datatype "distances", I delete that and it is running.
I only used steps and calories, now.

I have message : android.permission.ACTIVITY_RECOGNITION.



Thanks to help me.

**Comment by dariosalvi78** [comment]
the plugin should automatically ask for permissions to the operating system (and the user) depending on the datatype when requesting authorization. Please make sure that you are calling requestAuthorization() before running any query.

**Comment by BenLaKnet** [comment]
Yes I am sure : 

`function onDeviceReady() {
    	
	checkSecurity();
	
	showMenu();
	
	if (cordova.platformId == "electron") {
		addMyContenu("Synchronisation bluetooth impossible sur cet appareil !");
	}
	else {
		addMyContenu("Synchronisation de vos informations avec l'appli.");
		navigator.health.isAvailable(successisAvailableCB, errorCB);
	}
}

function messageBeforeSync() {
	
	strtitle = "Synchronisation de vos données de santé";
	strmessage = "Dans le but de collecter vos données de santé, l'Application Mon Glucko va se connecter à votre compte Google Fit et demander l'autorsation d'accéder à votre position.\n";
	strmessage += "La position n'est pas conservée par Mon Glucko.\n";
	strmessage += "Merci d'autoriser l'accès pour effectuer la synchronisation.";
	
	navigator.notification.confirm(
		strmessage,          // message
		function (buttonIndex) {
			if (buttonIndex==1) {
				
				navigator.health.isAuthorized(datatypes, successisAuthCB, errorCB);
				
			}
			else {
				if (cordova.platformId == "android") {
					navigator.health.disconnect(successDisconnectCB(), errorCB)
				}
				else {
					errorCB("La déconnexion n'est pas disponible sur cet appareil ! Merci de vous rendre dans vos paramètres iOS.");
				}
			}
		},
		strtitle,           // title
		['Autoriser','Non']   // buttonName
	);

}

function successDisconnectCB(disconnected) {
	
	if (disconnected) {
		addMyContenu("L'application n'est plus autorisée.", 1);
	}
	else {
		errorCB("La déconnexion n'a pas fonctionné. Merci de vous rendre dans vos paramètres de compte Google pour retirer les autorisations.");
	}
	
}


function successisAvailableCB(available) {

	if (available) {		
		messageBeforeSync() ;
	}
	else {
		addMyContenu("L'application ne trouve pas vos données, vous n'avez pas installé : Google Fit pour Android ou HealthFit pour iOS !", 1);
	}
}

function successrequestAuthCB() {
	
	addMyContenu("Autorisation approuvée, lancer la synchro !<br />", 1);
	
	getSyncDatas();
	
}


function successisAuthCB(authorized) {
	
	if (authorized) {
		addMyContenu("Lancer la synchro !<br />", 1);
		
		getSyncDatas();

	}
	else {	
		navigator.health.requestAuthorization(datatypes, successrequestAuthCB, errorCB);
		
	}
}


function getSyncDatas() {
	
	getSyncDatasSteps();
	getSyncDatasCalories();
	 
}`

**Comment by BenLaKnet** [comment]
Ok thanks. The code is good, but I added : 


`var permissions = cordova.plugins.permissions;
					var list = [
						//permissions.ACCESS_FINE_LOCATION, seulement si datatypes contient 'distances'
						permissions.ACTIVITY_RECOGNITION,
					];
					
					permissions.checkPermission(list, function( status ){
						if ( status.hasPermission ) {
							navigator.health.isAuthorized(datatypes, successisAuthCB, errorCB);
						}
						else {
							permissions.requestPermissions(
							  list,
							  function(status) {
								if( status.hasPermission ) {
									navigator.health.isAuthorized(datatypes, successisAuthCB, errorCB);
								}
								else {
									errorCB("Vous n'avez pas autorisé l'application. Merci de recommencer.");
								}	
							  });
						}
					});`

**Comment by dariosalvi78** [comment]
One note: you should **always** request authorization, do not make it dependent on the result of isAuthorized().

**Comment by BenLaKnet** [comment]
I modify my source code and it is in fact an android 13 / HONOR 70 for this test.
I add this code and it is not running : 


```

var permissions = cordova.plugins.permissions;
				var list = [
					//permissions.ACCESS_FINE_LOCATION, seulement si datatypes contient 'distances'
					permissions.ACTIVITY_RECOGNITION,
				];
				
				permissions.requestPermissions(
				  list,
				  function(status2) {
					  
					console.log(JSON.stringify(status2));
					  
					if( status2.hasPermission ) {
						navigator.health.requestAuthorization(datatypes, successrequestAuthCB, errorCB);
					}
					else {
						errorCB("Vous n'avez pas autorisé l'application. Merci de recommencer.");
					}	
				});
```

**Comment by BenLaKnet** [comment]
I update my dev platform to compileSdkVersion 34 and it is running correctly in my HONOR 70.
Many thanks for you helps.
