### ISSUE TITLE
User cancelled the dialog

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#299]
Hi,

I'm in the process of getting my app validated by Google but I'm having an issue, they get this error message:

`User cancelled the dialog`

I do not understand why.
I tried many times with 2 android phones and I do not obtain this error.

May I add the 2 test emails in the Google console?

**Comment by dariosalvi78** [comment]
this has been commented in several issues, please check the closed ones. "user cancelled dialog" is a bad description of "you haven't set the oauth consent process correctly on Google console.

Get back to the console and fix it there. You will have to use test accounts if you don't have approval.

**Comment by BenLaKnet** [comment]
Many thanks @dariosalvi78.

I generated the key with keytool, but now what to do with the file created by OAuth google console?

**Comment by BenLaKnet** [comment]
Just go to the Google Play console and copy the SHA1 value into configuration / application signature
