### ISSUE TITLE
Upgrading to Capacitor 5 causing dataType issue

### ISSUE THREAD

**Issue by ChandraKAV** [dariosalvi78/cordova-plugin-health#300]
@dariosalvi78 I upgraded the Capacitor version to 5 (from 4.1.3), on suggestion from Ionic support team to fix another problem in my app, and started facing this error below when connecting to Google Fit. 

ERROR Error: Uncaught (in promise): Attempt to invoke virtual method 'java.lang.String com.google.android.gms.fitness.data.DataType.zza()' on a null object reference

I have seen this error before but not sure in relation to which specific data type or how to fix it. 

Any suggestions?

**Comment by dariosalvi78** [comment]
when does this happen? when requestig authorization?

**Comment by dariosalvi78** [comment]
am going to close all Google Fit related issues as this is discontinued
