### ISSUE TITLE
Updating a Package from Old version to New Version getting error 'ionic cordova plugin add cordova-plugin-health'

### ISSUE THREAD

**Issue by ajaykumarchamarthi** [dariosalvi78/cordova-plugin-health#302]
Hi Dario,

When I updated the package to "cordova-plugin-health": "^3.0.1", It am getting [warn] - Native: tried calling Health.isAuthorized, but the Health plugin is not installed. [warn] - Install the Health plugin: 'ionic cordova plugin add cordova-plugin-health'. , though the package is installed.I am able to retrieve the sleep data on older version "cordova-plugin-health": "^2.1.0" .I am doing with import { Health } from "@awesome-cordova-plugins/health"; from Health variable I am able to access all the methods. I am using Ionic React Framework.

Thank You

**Comment by dariosalvi78** [comment]
@awesome-cordova-plugins/health [is not updated](https://github.com/danielsogl/awesome-cordova-plugins/blob/master/src/%40awesome-cordova-plugins/plugins/health/index.ts) with the latest version. Not a bug of this plugin in any case, I have tested it with capacitor and it works (see also notes about how to fix dependencies on Android). 

Raise an issue there or use this plugin without wrappers.

**Comment by camillavk** [comment]
Hi Dario,

I'm not sure what I'm doing wrong but I'm unable to get this to work in Capacitor Ionic React app. I have installed "cordova-plugin-health": "^3.1.1" and "@ionic-native/health": "^5.36.0",
I am trying to import it but when I try 
import { Health } from 'cordova-plugin-health' it says "Cannot find module 'cordova-plugin-health' or its corresponding type declarations."
And if I try
import { Health } from '@ionic-native/health'

but I am getting:
Msg: Native: tried calling Health.isAvailable, but the Health plugin is not installed.
Msg: Install the Health plugin: 'ionic cordova plugin add cordova-plugin-health'
Msg: Health is not available plugin_not_installed

I've added the bits into AndroidManifest.xml mentioned in the README but I just can't seem to import it. I've tried with and without the ionic-native/health but I think I'm missing something obvious?

**Comment by dariosalvi78** [comment]
I would suggest to not use ionic-native/health and use the cordova plugin alone, which also means that you access it using its original interface: `cordova.plugins.health` so nothing like `import { Health } from '@ionic-native/health'`

**Comment by camillavk** [comment]
Sorry, just to double check, as I am using Capacitor in my project, it's still not working. I have this code:
```
if(isPlatform('hybrid')) {
        try {
          const isAvailable = await cordova.plugins.health.isAvailable();
          console.log('is available: ', isAvailable)
          if (isAvailable) {
            try {
              const authResult = await cordova.plugins.health.requestAuthorization([
                'distance',
                {
                  read: ['steps']
                }
              ]);
              console.log('Authorization granted', authResult);
              await setHealthAuthorized(authResult);
            } catch (authError) {
              console.error('Authorization denied', authError);
            }
          }
        } catch (availabilityError) {
          console.error('Health is not available', availabilityError);
        }
      } else {
        console.warn('Health plugin only available on native platforms')
      }
 ```
   
But that gives the error `Property 'health' does not exist on type 'CordovaPlugins'` is there some other configuration I'm missing to make it work with Capacitor?

**Comment by camillavk** [comment]
Sorry, ignore me, I've figured it out and got it working now!

**Comment by AlessandroFBK** [comment]
How do you import the plugin when you use it in a Capacitor plugin?

**Comment by dariosalvi78** [comment]
don't import anything, just call cordova.plugins.health, it should be exposed globally

**Comment by AlessandroFBK** [comment]
I'm afraid it is not… 
Cordova seems not to be available, even in a fresh project created using Ionic CLI (which by default enables Capacitor support). You can have a look at this [simple project](https://github.com/AlessandroFBK/starter) in which - according to your and also to the official doc, I've just installed the plugin using NPM. 
Am I missing something? Thank you for your support.
