### ISSUE TITLE
datatype blood_glucose not supported on Google Fit, version 2.1.0

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#306]
I tried to read blood_glucose values, but it returns "not supported" on Android.
What I am wrong ?

**Comment by dariosalvi78** [comment]
hi, the new version does not support blood glucose on Android yet (please see README carefully). If blood glucose is what you need, let me know and I can prioritise it for the next version.

**Comment by dariosalvi78** [comment]
oh, wait, I was missing the version in the title!

Blood glucose should be supported both on iOS and Google Fit on v 2. Try updating to the latest v2, that is v 2.1.1 and see if that solves it. If not, the bug should be an easy one, the code includes support for blood glucose for both operating systems.

To be clear: I am not going to provide support for Google Fit any longer: it doesn't make any sense to continue investing on an API that will disappear this year, so if there is a bug you (or someone else) will have to fix it. Happy to receive pull requests of course.

**Comment by BenLaKnet** [comment]
Hi @dariosalvi78 ,

I had the same issue with 2.1.1.

Could you please tell me if it is needed a specific permissions or is it possible to upgrade and add code for blood_glucose in v3 ?

**Comment by dariosalvi78** [comment]
a permission is needed yes, but that's not the error you are reporting. I don't know why you are getting that message, the data type is supported by the plugin on Android.

The new version does not support blood glucose yet, but I can prioritise it.

**Comment by BenLaKnet** [comment]
@dariosalvi78: 

I do not understand the problem too.


> 'The new version does not support blood glucose yet, but I can prioritise it.'

Yes, if it is possible I migrate to v3.
How should I install it when version was updated with blood_glucose ?

**Comment by dariosalvi78** [comment]
> How should I install it when version was updated with blood_glucose ?

keep en eye on this repository, when blood glucose is added, you install the plugin following the instructions (it's all in the readme).

I'll close this issue and create a new one for the blood glucose on heatlhconnect.

**Comment by BenLaKnet** [comment]
I understood my problem, queryAggregate does not support "blood_glucose".
