### ISSUE TITLE
Is there anyone who has used the plugin to record blood_glucose datas?

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#309]
Hi,

I want to synchronise datas between a Bluetooth reader (Accu Chek Mobile), database and Google Fit / HealthKit.

with `store method`, what value should I use? value or an Object formed with:

`{ glucose: 5.5, meal: 'breakfast', sleep: 'fully_awake', source: 'capillary_blood' }`

**Comment by dariosalvi78** [comment]
see [readme](https://github.com/dariosalvi78/cordova-plugin-health/tree/2.1.1)

the `value` in the store method should be an obejct like the one you mention
