### ISSUE TITLE
Empty array for active calories

### ISSUE THREAD

**Issue by MrJustreborn** [dariosalvi78/cordova-plugin-health#310]
I try to get my active calories with:

```
cordova.plugins.health.query({  
                startDate: new Date(new Date().getTime() - 30 * 24 * 60 * 60 * 1000),  
                endDate: new Date(),  
                dataType: 'calories.active'  
              }, (s:any) => {
                console.info("Success", s)
              }, (s:any) => {
                console.info("Error", s)
              })
```

but the array is empty, Log output : `Success > []`

I do have active data. Getting '`calories.basal`' works, I get the entry of the day on which I changed my weight. (About a month ago) Querying for '`steps`' also works.

_MAYBE it's a issue with my specific setup, I'm using a Xiaomi fitness tracker with the ZeppLife-App. This App does not support HealthConnect but GoogleFit. So it syncs with GoogleFir and GoogleFit is configured to sync with HealthConnect.
(But on the other hand, my weight also was updated in ZeppLife-App and synced to Fit, I did not change any data in Fit directly)_

**Comment by dariosalvi78** [comment]
yes, it's probably that the 2 are incompatible. HealthConnect treats calories differently than Fit. In Fit you can access either basal or total calories, not active one. In HC you can access active or basal (more similar to HealthKit, which is good). So my guess is that the Zepp life app does not store active calories and there is no easy way to map those total calories to the active ones?

Try storing active calories with the plugin and see if you can read them back. If that's the case, I'd probably close this issue.

**Comment by MrJustreborn** [comment]
I can write `calories.active` and read them back, so it must be my specific setup.

_Good excuse to get a new tracker from company money :laughing:_
