### ISSUE TITLE
Querying cycling distances in Health Connect

### ISSUE THREAD

**Issue by maswa** [dariosalvi78/cordova-plugin-health#312]
We are  using plugin version 2.01 in our live Android and iOS app and all works well , except Google wants oAuth verification for Fit API  and that is a long process for something that will be deprecated. 

So now we are trying to migrate from Google Fit to Health connect and encountering an issue with fetching biking distances. 
We're using Plugin version 3.0.2 , Android  SDK34  and Cordova latest version.  

Here is an example of the output when querying (non-aggregated) biking activity data:

```
{
  "id": "b36b924e-8a25-3a8f-b231-d89b0c9ade48",
  "sourceBundleId": "com.google.android.apps.fitness",
  "entryMethod": "manual_entry",
  "startDate": "2024-01-25T09:58:57.407Z",
  "endDate": "2024-01-25T10:28:57.407Z",
  "value": "biking",
  "unit": "activityType"
}
```

In this output, the value field is "biking", and the unit is "activityType". There doesn't seem to be a direct representation of distance, which is what I expected.

Here is the non-aggregated query we use: 

```
cordova.plugins.health.query(
    {
        startDate: start_date,
        endDate: end_date,
        dataType: localStorage.health_op_type, //is set to activity
        ascending: true,
        limit: 1000,
        filtered: true,
    },
    health_read_success,
    function (err) {
        show_alert("Query Data Error", err, "OK");
    }
);
```

And here is the output of the aggregated query:

```
{
  "recordDate": "2024-01-25",
  "cdate": "2024-01-25",
  "record": {
    "startDate": "2024-01-24T23:00:00.000Z",
    "endDate": "2024-01-25T12:34:02.587Z",
    "value": 1800000,
    "unit": "ms"
  }
}
```
In this output, the value field is  a number of milliseconds and the unit is "ms".  
Also no representation of distance, which is what I expected.

And this is our aggregated query:

```
cordova.plugins.health.queryAggregated(
    {
        startDate: start_date,
        endDate: end_date,
        dataType: dataType, //is set to activity
        bucket: "day",
        includeDistance: true
    },
    health_read_success_aggregated,
    function (err) {
        show_alert("Error", err, "OK");
    }
);
```

- How should the biking activity data be interpreted in terms of distance covered?

- Is there a specific structure or format that the plugin uses to represent the distance of cycling activities?

- Are there any additional parameters or methods in the plugin that need to be used to correctly retrieve or calculate the distance data for cycling activities?

Any insights or guidance would be greatly appreciated.

Thank you for your assistance.

**Comment by dariosalvi78** [comment]
I am not sure why you expect the activity to give you a distance, that's not what it's meant for, and it's clearly documented.

Anyway, in the previous version of the plugin we had `distance`. This is still available in iOS, but I need to add it to Android. If  you need it let me know and I can prioritize it. Alternatively, as also documented on the README, you can add `includeDistance: true` to query for the activity and it will return any distance run or cycled within the activity object.
