### ISSUE TITLE
Add support for TotalCaloriesBurnedRecord

### ISSUE THREAD

**Issue by MrJustreborn** [dariosalvi78/cordova-plugin-health#314]
As in #310 mentioned, I have a weird setup. I updated to a FitBit (which is from google) with HealthConnect support. Unfortunately the FitBit app write "total calories burned" to HealthConnect, so query for `calories.active `is still empty.

In order to get these, the old `calories` dataType to get `TotalCaloriesBurnedRecord` should be supported.

**Comment by BenLaKnet** [comment]
it is necessary to add in AndroidManifest.xml:
```

    <uses-permission android:name="android.permission.health.READ_TOTAL_CALORIES_BURNED" />
    <uses-permission android:name="android.permission.health.WRITE_TOTAL_CALORIES_BURNED" />
```

**Comment by BenLaKnet** [comment]
In AndroidManifest.xml, if I do not want all authorizations, I have to delete them, right?
But they come back when I compile cordova project.

Maybe it could be a problem for Google Auth Form?
