### ISSUE TITLE
Datatype not supported heart_rate & Datatype not supported sleep

### ISSUE THREAD

**Issue by mohamednagy** [dariosalvi78/cordova-plugin-health#318]
I was trying to query heart_rate and sleep but i got error  `Datatype not supported heart_rate` and  `Datatype not supported sleep`

version: 3.0.4

**Comment by dariosalvi78** [comment]
not yet supported, no, but I can prioritize them for the next release

**Comment by mohamednagy** [comment]
@dariosalvi78 this would be much appreciated, my app development is blocked by those already

**Comment by mohamednagy** [comment]
@dariosalvi78 i see the sleep already added to v3.1.0, really thanks, will the heart rate will be released soon? 
also i can't find v3.1.0 on npm

**Comment by dariosalvi78** [comment]
both are now included in v 3.1.1

**Comment by mohamednagy** [comment]
@dariosalvi78 thank you very much
is v3.1.1 has been published, i can only see v3.1.0 in npm https://www.npmjs.com/package/cordova-plugin-health

**Comment by dariosalvi78** [comment]
my bad, should be published now. Leave an issue if you find bugs. Thanks.
