### ISSUE TITLE
[iOS] unknown data type distanace

### ISSUE THREAD

**Issue by chanphillip** [dariosalvi78/cordova-plugin-health#32]
When I was calling requestAuthorization to authorize "distance" on iOS, it returns with this error message.

> unknown data type distanace

It is working on Android though.
I've tried "calories" and "activity", and they are working on iOS.

**Comment by dariosalviwork** [comment]
I've tried it right now and it works like a charm.

`navigator.health.requestAuthorization(['distance'], (d) => console.log('OK'), (e)=> console.log('ERROR', e) )`

**Comment by chanphillip** [comment]
OMG...what a mistake 👎
