### ISSUE TITLE
Open healthConnect / HealthKit programmatically to see app authorizations

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#320]
Hi,

I do not know how is it possible to open health connect to see authorization of my app and change options of read/write.

Many thanks.

**Comment by dariosalvi78** [comment]
It's either a separate app or as part of the settings

**Comment by BenLaKnet** [comment]
Please, could you add this possibility in this plugin ?

**Comment by BenLaKnet** [comment]
I found `[com.lampa.startapp](https://github.com/lampaa/com.lampa.startapp)`

**Comment by dariosalvi78** [comment]
ahh I didn't get the question, you mean how do I **programmatically** open the HealthConnect settings?

I have no idea, as said, it's either buried in the settings or is installed as a separate app. You will need to send an Intent, but I don't know which one exactly. If you find out, let me know and I can try to add this functionality to the plugin.

**Comment by dariosalvi78** [comment]
I suspect it has something to do with this: https://developer.android.com/reference/android/health/connect/HealthConnectManager

**Comment by BenLaKnet** [comment]
Hi,

I tried this plugin and it is running:


```
function openHealthSettings() {
	
	if (cordova.platformId == "android") {
		
		var pkgName = "com.google.android.apps.healthdata"
		
		var sApp = startApp.set({
			"package": pkgName,
			"application": pkgName
		});
				
		sApp.check(
			function (values) {
				
				//console.log(JSON.stringify(values));
				if (values.versionName) {
					sApp.start();
				}
				else {
					cordova.InAppBrowser.open('https://play.google.com/store/apps/details?id=' + pkgName, '_system', 'location=yes');
				}
				
			},
			function (error) {
			
				console.log(error);
				
			}		
		);	

	}
	else if (cordova.platformId == "ios") {
		
		var sApp = startApp.set("x-apple-health://").start();
		
	}
	
}
```

**Comment by dariosalvi78** [comment]
so that starts an Android Intent with "com.google.android.apps.healthdata". 
Have you tried it on Android 14 ? I was wondering if this is the same on all versions of the OS

**Comment by BenLaKnet** [comment]
No I just have Android 10 and 13.

**Comment by BenLaKnet** [comment]
After updating on Android 13, it does not work.
I will try to see what happens.

**Comment by BenLaKnet** [comment]
It triggers an error when Health Connect is not installed.
It is running now.

What could you do to use Intent with your plugin and open settings or install health ?

**Comment by dariosalvi78** [comment]
launching an Intent in Android [is trivial](https://www.vogella.com/tutorials/AndroidIntent/article.html), but you need to identify which intent to launch (is it com.google.android.apps.healthdata ?). If you have time, mabe you can try adding a function that does that?

**Comment by rengadevigg** [comment]
fun openHealthConnect() {
        if(healthConnectHandler.isInstalled()) {
            val intent = Intent(HealthConnectClient.ACTION_HEALTH_CONNECT_SETTINGS)
            bridge.activity.startActivity(intent)
        }
        else {
                val providerPackageName = "com.google.android.apps.healthdata";
                val uriString =
                    "market://details?id=$providerPackageName&url=healthconnect%3A%2F%2Fonboarding"

                bridge.activity.startActivity(
                    Intent(Intent.ACTION_VIEW).apply {
                        setPackage("com.android.vending")
                        data = Uri.parse(uriString)
                    }
                )
        }
        
        it works in all versions. 
        that version compatibilit android itself takes care does this help?

**Comment by dariosalvi78** [comment]
yes it does!
Weirdly, I have it as HealthConnectClient.ACTION_HEALTH_CONNECT_SETTINGS_LEGACY, but it's using androidx.
The string corresponds to: "androidx.health.ACTION_HEALTH_CONNECT_SETTINGS". I can add it to the plugin, but I'd need to check if it works on Android 14 too, because there HealthConnect becomes embedded into the OS and is treated slightly differently. In fact, HealthConnectManager.ACTION_MANAGE_HEALTH_PERMISSIONS (which is NOT within androidx, but available from Android 14) corresponds to the string "android.health.connect.action.MANAGE_HEALTH_PERMISSIONS" , which is different.

**Comment by BenLaKnet** [comment]
When you will publish the new version?

**Comment by BenLaKnet** [comment]
Help me, please, I am waiting the new version to publish updates on my app.
Many thanks.

**Comment by dariosalvi78** [comment]
Hi, I am a bit overworked these days, can you maybe test the latest code and confirm that it works on both Android and iOS?
Particularly, I would need to check that the openHealthSettings() function works on both.
If you tell me it's working for you I can publish it.

**Comment by BenLaKnet** [comment]
OK many thanks for your answer.

I will see that.

**Comment by dariosalvi78** [comment]
I have tested it and released it, v 3.2.0

**Comment by BenLaKnet** [comment]
OK, it is running for me.

Many thanks @dariosalvi78

**Comment by BenLaKnet** [comment]
I have a strange problem with an HONOR phone.
Google Health Connect is not installed, but HONOR Health is added. Since then, the function which detects the presence of the Google Health Connect plugin has not responded correctly.

**Comment by dariosalvi78** [comment]
what do you mean with "has not responded correctly"?

**Comment by BenLaKnet** [comment]
disconnect is no longer available in the plugin?

On HONOR, Health Connect is not installed but isAvailable returns true?


In my code, I check if Health Connect isAvailable and after determines if I have to go to install plugins or to Parameters.
Now with HONOR HEALTH/Santé app, with no Google Health Connect, the plugins returns that Google plugin is installed.

Have you this same issue with HONOR or Android 13?

**Comment by dariosalvi78** [comment]
> disconnect is no longer available in the plugin?

no, there is no call for this in the API, you can disconnect the app using the settings in HealthConnect

> On HONOR, Health Connect is not installed (as indicated in Play Store) but isAvailable returns true?

This is correct, since Android 14 HealthConnect is a system service, not an app

**Comment by BenLaKnet** [comment]
Ok, I open a new issue.
