### ISSUE TITLE
Using targetSdkVersion 34 is not supported in Capacitor 5

### ISSUE THREAD

**Issue by YadrovSergey** [dariosalvi78/cordova-plugin-health#325]
In [Manual setup in Capacitor (Ionic)](https://github.com/dariosalvi78/cordova-plugin-health?tab=readme-ov-file#manual-setup-in-capacitor-ionic) you advice set targetSdkVersion 34. But using targetSdkVersion 34 is not supported in Capacitor 5

See [bug(@capacitor/share)](https://github.com/ionic-team/capacitor-plugins/issues/2057)

**Comment by dariosalvi78** [comment]
I have the following and ti works fine:

dependencies in packjage.json
```json
    "@capacitor/android": "5.6.0",
    "@capacitor/app": "5.0.6",
    "@capacitor/core": "5.6.0",
    "@capacitor/haptics": "5.0.6",
    "@capacitor/keyboard": "5.0.7",
    "@capacitor/status-bar": "5.0.6",
    "@ionic/vue": "^7.0.0",
    "@ionic/vue-router": "^7.0.0",
    "cordova-plugin-health": "file:../cordova-plugin-health",
    "ionicons": "^7.0.0",
    "vue": "^3.3.0",
    "vue-router": "^4.2.0"
```

versions in /android/variables.gradle
```
    minSdkVersion = 26
    targetSdkVersion = 34
    compileSdkVersion = 34
```

**Comment by dariosalvi78** [comment]
I know of at least one company that is using this plugin with capacitor without issues, so I suspect that what they told you about "targetSdkVersion 34 is not supported in Capacitor 5," is false. Capacitor 6 introduces sdk compile version to 34 as _default_, but that doesn't mean that capacitor 5 is not able to handle it. It's a problem of their plugin, not of capacitor.

**Comment by YadrovSergey** [comment]
> I have the following and ti works fine:

> ```
 Try add plugin @capacitor/share and you app will crash on start.

**Comment by dariosalvi78** [comment]
Ok but that's an issue of the share plugin, I don't have any role in that.
