### ISSUE TITLE
NPM package is not updated 

### ISSUE THREAD

**Issue by mohamednagy** [dariosalvi78/cordova-plugin-health#327]
Latest version in NPM is 3.1.1 https://www.npmjs.com/package/cordova-plugin-health
but i can see the latest here is 3.2.0 which methods like openHealthSettings is not available. 
Could you please update the package version in NPM ?

**Comment by BenLaKnet** [comment]
You have to do:

`
cordova plugin add https://github.com/dariosalvi78/cordova-plugin-health.git#3.2.0
`

**Comment by mohamednagy** [comment]
@BenLaKnet i'm using Capacitor with ionic vue
