### ISSUE TITLE
Health connect android - android 14 delete records crashes.

### ISSUE THREAD

**Issue by rengadevigg** [dariosalvi78/cordova-plugin-health#328]
<img width="1841" alt="Screenshot 2024-06-19 at 4 52 55 PM" src="https://github.com/dariosalvi78/cordova-plugin-health/assets/96510881/8dcaf795-a3df-4d6c-b53c-29a6ca0dfe10">

app crashes then above log shows in logcat.

**Comment by dariosalvi78** [comment]
umm, there is no trace that brings to the plugin code, maybe you have stumbled on a bug in Health Connect?
Can you describe how to reproduce it?

**Comment by dariosalvi78** [comment]
if there are no news on this I am going to close it

**Comment by rengadevigg** [comment]
It is fixed already by updating updated version of dependencies in build gradle file.
