### ISSUE TITLE
Update documentation for limit and ascending

### ISSUE THREAD

**Issue by alx-andru** [dariosalvi78/cordova-plugin-health#33]
Healthkit.m
 ```
(void)querySampleType:(CDVInvokedUrlCommand *)command {
    NSDictionary *args = command.arguments[0];
    NSDate *startDate = [NSDate dateWithTimeIntervalSince1970:[args[HKPluginKeyStartDate] longValue]];
    NSDate *endDate = [NSDate dateWithTimeIntervalSince1970:[args[HKPluginKeyEndDate] longValue]];
    NSString *sampleTypeString = args[HKPluginKeySampleType];
    NSString *unitString = args[HKPluginKeyUnit];
    NSUInteger limit = ((args[@"limit"] != nil) ? [args[@"limit"] unsignedIntegerValue] : 100);
    BOOL ascending = (args[@"ascending"] != nil && [args[@"ascending"] boolValue]);
```

is accepting `limit` as an int and `ascending` as a boolean value. 

Would be great to update the documentation and examples. Otherwise the default is set to 100 and reverse order.

**Comment by dariosalviwork** [comment]
well spotted.

I think I'll try to get rid of the limit if possible, or extend it to something big so that APIs are consistent between HK and GF.

**Comment by alx-andru** [comment]
In my case, the maximum I query is one full day so I just set the value to 10k. I would do both, increase the value and document it. Some crazy person might need/want it and then he or she stumbles above a hardcoded value.
