### ISSUE TITLE
Installing with Capacitor

### ISSUE THREAD

**Issue by asivaneswaran** [dariosalvi78/cordova-plugin-health#334]
Hi,

Is there an example of how to use this plugin with Capacitor?

I did the manual installation for Android, but I am not sure how to call the plugin in my ionic app.

Thanks,

**Comment by dariosalvi78** [comment]
this? https://github.com/dariosalvi78/cordova-plugin-health?tab=readme-ov-file#manual-setup-in-capacitor-ionic
