### ISSUE TITLE
Android 15 - What changing

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#335]
What should we change with Android 15 ?
Anyone tests plugin with this version of Android ?

```
Dans Android 15, l'espace privé pourrait avoir un impact sur votre application
Mon Glucko Mon Glucko
23 août 2024 14:00
En raison des restrictions concernant les applications dans les espaces privés, il est possible que les applis médicales ne fonctionnent pas correctement si elles sont ajoutées à un espace privé. Consultez nos conseils et pensez à informer vos utilisateurs afin d'éviter toute interruption.
```

**Comment by dariosalvi78** [comment]
source:
https://developer.android.com/about/versions/15/behavior-changes-all#private-space-medical-apps

good point, but I guess there's not much to do, except to warn the user about this. In the end, it's the user's decision to run an app in this "private space" or not.
