### ISSUE TITLE
Nutrition

### ISSUE THREAD

**Issue by asivaneswaran** [dariosalvi78/cordova-plugin-health#336]
Hi,

I would like to know if any work is ongoing for nutrition (calories, protein, carbs, fat)? I believe it's a very priority data no in the current time

I know it was there before but was removed with Health Connect. 

Thanks,

**Comment by dariosalvi78** [comment]
not being done at the moment, but can be prioritized.
API details are here: https://developer.android.com/reference/kotlin/androidx/health/connect/client/records/NutritionRecord

**Comment by asivaneswaran** [comment]
It would be great if we can prioritize this. I can help if needed if you can show me examples of commits that was done to add previous data to android.

thanks

**Comment by dariosalvi78** [comment]
it's not hard! if you look at the Android code for any other data type, the structure is always the same. It's important to keep the interface with the JS world coherent between iOS and Android, that's the only, sometimes, tricky bit.

**Comment by asivaneswaran** [comment]
@dariosalvi78 https://github.com/dariosalvi78/cordova-plugin-health/pull/339

Let me know if it seems ok with you!

**Comment by asivaneswaran** [comment]
@dariosalvi78 You haven't tagged a new release after the MR.

Thanks,

**Comment by dariosalvi78** [comment]
published now
