### ISSUE TITLE
i can't compile ionic capacitor project if i try to use  cordova.plugins.health

### ISSUE THREAD

**Issue by jammie27** [dariosalvi78/cordova-plugin-health#340]
ionic --version
7.2.0
npx cap --version
6.1.2
cordova-plugin-health installed via npm.
In the component, i try to use
`const res = await cordova.plugins.health.isAvailable();`

i'd suppose that the object cordova.plugins.health is available globally, but i can't compile project, get error message:
 error TS2304: Cannot find name 'cordova'.
 
 Then, i deinstalled plugin and installed it again, tried simply with console.log(cordova.plugins.health) and the tried to compile.
 The result is the same.
 
 Next step. Fresh App without any plugins. I install cordova-plugin-health (via npm too) and try to make output 
 ` console.log(cordova.plugins.health);`
  the result is the same.
 
 
@dariosalvi78  What can be wrong? (maybe i do something wrong)

**Comment by dariosalvi78** [comment]
I don't usually work with capacitor, but I have tested the plugin there and the cordova object was exposed globally. Maybe it has to do with Angular if you use it? See #341  for possible suggestions.
Closing because it's likely not a plugin issue.
