### ISSUE TITLE
requestAuthorization Error

### ISSUE THREAD

**Issue by hamjad-centenum** [dariosalvi78/cordova-plugin-health#341]
I could use your help. requestAuthorization returning `Cannot read request objectValue ["steps","distance","calories"] at 0 of type org.json.JSONArray cannot be converted to JSONObject` . Do you have an idea why this could be happening ? @dariosalvi78 

Here is my implementation

```
  function onSuccess(authResult) {
      console.log("Authorization granted", authResult);
   }

    function onErr(error) {
      console.error("Authorization denied", error);
    }

    await cordova.plugins.health.requestAuthorization(
      ['steps', 'distance', 'calories'],
      onSuccess,
      onErr
    );
```

**Comment by jammie27** [comment]
May i ask,  do you build cordova project or capacitor project?
Because i can't compile capacitor project at all.

**Comment by hamjad-centenum** [comment]
> May i ask, do you build cordova project or capacitor project? Because i can't compile capacitor project at all.

Capacitor

**Comment by jammie27** [comment]
I added plugin via npm as usual, try to use cordova.plugins.health (should be available globally), then ionic build , and get error, cordova is not defined.
What can i miss?
If i understand it, i can maybe come near to your case.

**Comment by hamjad-centenum** [comment]
> I added plugin via npm as usual, try to use cordova.plugins.health (should be available globally), then ionic build , and get error, cordova is not defined. What can i miss? If i understand it, i can maybe come near to your case.

can you share your code?

**Comment by jammie27** [comment]
Very simply, in component
`const res = await cordova.plugins.health.isAvailable();`

And it causes compiling error
error TS2304: Cannot find name 'cordova'.

Have i to import anything in component?

**Comment by hamjad-centenum** [comment]
> Very simply, in component `const res = await cordova.plugins.health.isAvailable();`
> 
> And it causes compiling error error TS2304: Cannot find name 'cordova'.
> 
> Have i to import anything in component?

No you do not have to import anything, `cordova.plugins.health` is exposed globally at build time. what framework are you working with

**Comment by jammie27** [comment]
i work with ionic / angular (standalone components).

**Comment by hamjad-centenum** [comment]
> i work with ionic / angular (standalone components).

oh i typically do not use angular but maybe you should create a `private` function in a service then import that into your component

**Comment by jammie27** [comment]
> > i work with ionic / angular (standalone components).
> 
> oh i typically do not use angular but maybe you should create a `private` function in a service then import that into your component

I'd suppose i understood it. There is no stub for web in plugin, that's why cordova.plugins.health can be recognized on platforms only.
I'll try to get it running.

**Comment by dariosalvi78** [comment]
@hamjad-centenum  please check the documentation more carefully: https://github.com/dariosalvi78/cordova-plugin-health?tab=readme-ov-file#requestauthorization
