### ISSUE TITLE
sourceBundleId with Android 10.

### ISSUE THREAD

**Issue by BenLaKnet** [dariosalvi78/cordova-plugin-health#345]
Hi @dariosalvi78 ,

I will try to use this to manage synchronization, but it returns `undefined` or package name of my app.

```
sourceBundleId: the identifier of the app that produced the data
sourceName: (only on iOS) the name of the app that produced the data (as it appears to the user)
sourceDevice: (only on Android) the device where the data came from manufacturer and model
```

I do not understand why because I synchronize with "Samsung Health" (health datas activities) and blood_glucose with my app (bluetooth).

With iOS, sourceBundleId seems to be correctly implemeted and sourceName too.

Is there a cordova plugin to show logo of a BundleId app? 

Many thanks.

**Comment by dariosalvi78** [comment]
do you get a sourceBundleId for any of those apps on Android?

**Comment by BenLaKnet** [comment]
Undefined for all apps with Android.
It is running only for my app with my bundleId.

**Comment by BenLaKnet** [comment]
It is not running... 

id is undefined too for the other values.

**Comment by BenLaKnet** [comment]
I tried with Honor 70 / Android 14 and it is not unning too.
id and other values source are "undefined".

**Comment by BenLaKnet** [comment]
I do not find a solution. Have you?

**Comment by dariosalvi78** [comment]
I don't know why it is not working for you, the code is pretty straightforward:

```java
        DataOrigin origin = meta.getDataOrigin();
        if (origin != null) {
            obj.put("sourceBundleId", origin.getPackageName());
        }
```
According to the docs, in theory, neither [getDataOrigin](https://developer.android.com/reference/androidx/health/connect/client/records/metadata/Metadata#getDataOrigin())(), nor [getPackageName](https://developer.android.com/reference/androidx/health/connect/client/records/metadata/DataOrigin#getPackageName())() can return null, thus the sourceBundleId should always be populated.

**Comment by dariosalvi78** [comment]
tested on my phone (OnePlus A5010, Android 10). 

Steps:
<img width="914" alt="image" src="https://github.com/user-attachments/assets/6ecc8ee8-a876-401c-9859-0b39dcbe949e">
and sleep:
<img width="884" alt="image" src="https://github.com/user-attachments/assets/0e66b9f7-2172-4214-a56b-d76eb7e499aa">

no issues here as you can see.

I don't think there is any bug in the plugin, so I am going to close this issue, but if you find out what's happening on your side, please document it here.

**Comment by BenLaKnet** [comment]
Hi @dariosalvi78 ,
I do not see that update, I tried to change:
```
<preference name="GradleVersion" value="8.7" />
<preference name="AndroidGradlePluginVersion" value="8.6.0" />
```
And it is not running too. I have to investigate.

```
2 mmol/L > com.monglucko.app
id: 7d60ce35-2b46-4bf5-8264-1204acfcdef9 PkgName: com.monglucko.app Dev: undefined Name: undefined
id: f1d49627-32d1-45e7-945e-4347dea06a6a PkgName: com.monglucko.app Dev: undefined Name: undefined
bpm > undefined
```

**Comment by dariosalvi78** [comment]
I am starting to suspect that you have a bug in the javascript code

**Comment by BenLaKnet** [comment]
I do 5 requests: 2 aggregated and 3 query, in the same page.
All values are correctly obtained, but I have problem with "metadata".
If I isolate one query to check "metadata" and values, I obtained the same problem: values are ok, but no "metadata".

example of function:

```
function getSyncDatasFreqCard(nbjours) {
	
	cordova.plugins.health.query({
	  startDate: new Date(new Date().getTime() - (nbjours * 24 * 60 * 60 * 1000)),
	  endDate: new Date(), // now
	  dataType: 'heart_rate',
	  limit: 1000
	}, function(data) {
		
		successSyncDatasCB(data);	
				
	}, errorCB);
	
	
}
```

**Comment by dariosalvi78** [comment]
if logcat prints out the package name when you do `Log.d(TAG, origin.getPackageName());`, then the package name should be returned in the object, I don't see any reason why this is not done. I suspect that you have a bug in the `successSyncDatasCB()` callback, where you try to access the sourceBundleId property. Make sure the case is correct, for example. Sometimes silly bugs take days to be discovered!

**Comment by dariosalvi78** [comment]
there may be a bug in the Samsung app, not yours. There's not much you can do in that case I guess, but you can try contacting Samsung about it. Good luck!

**Comment by BenLaKnet** [comment]
Many thanks.
