### ISSUE TITLE
Latest release on NPM is 3.2.1, not 3.2.2

### ISSUE THREAD

**Issue by samtate** [dariosalvi78/cordova-plugin-health#347]
I need version 3.2.2 for the nutrition tracking but while it's been committed here it doesn't seem to be on NPM. Please can it be uploaded there? Cheers

**Comment by BenLaKnet** [comment]
You can install plugin with:

` cordova plugin add https://github.com/dariosalvi78/cordova-plugin-health.git`

But I have an error with nutrition

**Comment by samtate** [comment]
I fixed the issues with Nutrition too and added a PR, looks like we did it at the same time! Good to see we came to pretty much the same solutions.

**Comment by BenLaKnet** [comment]
I have different solution for "Aggregate functions". Please see and tell me if it is not wrong.

**Comment by samtate** [comment]
I don't know as I've not used that function yet. I'm not entirely sure how that side of the logic is supposed to work. Your solution looks better in that it keeps calories by using the ? Type, if this works.

I've tested the main store function and that works great now which was my main objective but yeah if there's anything not working then by all means submit a fix!

**Comment by dariosalvi78** [comment]
hi, thanks to you all for the contributions. There is a bit of a chaos right now and I am cleaning up stuff. I will publish the new version as soon as I am happy with what we have.
