### ISSUE TITLE
Is it possible to pass in NSHealthShareUsageDescription and NSHealthUpdateUsageDescription strings using Phonegap Build?

### ISSUE THREAD

**Issue by benmcmaster** [dariosalvi78/cordova-plugin-health#35]
Is it possible to pass in `NSHealthShareUsageDescription` and `NSHealthUpdateUsageDescription` strings using Phonegap Build? 

For example the cordova-plugin-media-capture uses variables to add strings to the info.plist:

```
<plugin name="cordova-plugin-media-capture" source="npm" version="1.4.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value="App would like to access the camera." />
        <variable name="MICROPHONE_USAGE_DESCRIPTION" value="App would like to access the microphone." />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="App would like to access the library." />
    </plugin>
```

**Comment by benmcmaster** [comment]
Even though this plugin adds keys and empty strings for `NSHealthShareUsageDescription` and `NSHealthUpdateUsageDescription`, I am still getting errors when trying to upload my .ipa with Application Loader... (I am still trying to figure out which plugin is trying to use health data)

ERROR ITMS-90683: "This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSHealthShareUsageDescription key with a string value explaining to the user how the app uses this data."

ERROR ITMS-90683: "This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSHealthUpdateUsageDescription key with a string value explaining to the user how the app uses this data."

**Comment by dariosalvi78** [comment]
Probably the empty string is not enough. I'll add some text, but now I'm on holidays. Meanwhile you try adding those strings yourself in the .plist file.

**Comment by benmcmaster** [comment]
Here is the work around for Phonegap Build users:

It looks like you can't add elements to the root of the Info.plist using the `config-file`, but once you have a parent note you can. So I used this plugin to create the keys `NSHealthShareUsageDescription` and `NSHealthUpdateUsageDescription` and then added the code below to my `config.xml`:
```
<config-file platform="ios" target="*-Info.plist" parent="NSHealthShareUsageDescription" mode="replace">
        <string>App would like to access some of your health data.</string>
</config-file>

<config-file platform="ios" target="*-Info.plist" parent="NSHealthUpdateUsageDescription" mode="replace">
        <string>App would like to update some of your health data.</string>
</config-file>
```

And the Application Loader no longer complains.

**Comment by benmcmaster** [comment]
It turns out you don't need this plugin to just to create the create the keys `NSHealthShareUsageDescription` and `NSHealthUpdateUsageDescription`. Just adding:
```
<config-file platform="ios" target="*-Info.plist" parent="NSHealthShareUsageDescription" mode="replace">
        <string>App would like to access some of your health data.</string>
</config-file>

<config-file platform="ios" target="*-Info.plist" parent="NSHealthUpdateUsageDescription" mode="replace">
        <string>App would like to update some of your health data.</string>
</config-file>
```
to the config.xml file will add the keys and strings to the Info.plist.
