### ISSUE TITLE
Add HRV

### ISSUE THREAD

**Issue by remstone7** [dariosalvi78/cordova-plugin-health#355]
Would we be able to add heartRateVariabilitySDNN and on connect - HeartRateVariabilityRmssdRecord?

**Comment by dariosalvi78** [comment]
wanna try it yourself? I'd be happy to merge a PR

**Comment by kelchm** [comment]
@remstone7 -- I happen to have a PR (#356) which I just opened that implements `HKQuantityTypeIdentifierHeartRateVariabilitySDNN` support for aggregated queries on iOS :)

**Comment by remstone7** [comment]
@kelchm 🙏 thanks, was going to try to get to it this week!
