### ISSUE TITLE
Doesn't do anything on Android

### ISSUE THREAD

**Issue by koenoe** [dariosalvi78/cordova-plugin-health#37]
I'm using this plugin with success on iOS, but Android is still not working for me.
I followed the documentation for setting up the Google Project with the proper oAuth keys.

I get no errors or what so ever when I try to authorize or retrieve data, even in `adb logcat` I don't see any errors with the tag `cordova-plugin-health`.  When I use the method `promptInstallFit` and I don't have Google Fit installed it does redirect to the Play Store.

I do see this in `adb logcat`, but I don't know if it has anything to do with this plugin:
```
01-23 13:26:37.265 17072 17174 W CordovaPlugin: Attempted to send a second callback for ID: health1911832199
01-23 13:26:37.265 17072 17174 W CordovaPlugin: Result was: false
```

My system information:
```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: OS X El Capitan
Node Version: v4.6.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by dariosalvi78** [comment]
I don't get it, what does it mean "doesn't do anything" ?
Could you please debug your app with chrome://inspect ?

**Comment by koenoe** [comment]
@dariosalvi78 I'm not sure how chrome://inspect works for a Cordova app. But I use the https://github.com/apache/cordova-plugin-console to see my Javascript logs in my native logs (adb logcat). Works for every Cordova plugin I used so far. However it's not showing anything for example when I do this:
```
window.navigator.health.requestAuthorization(['steps'], function(r) {
    console.log(r);
}, function(e) {
    console.log(e);
});
```

Like I said, it's working fine on iOS and it's also showing me the logs in Xcode.

**Comment by dariosalvi78** [comment]
I'm afraid I can't help without more information.

I very warmly suggest you to use chrome inspect to debug the app. Just google it if you need more information.

Please make sure that you use the latest release of the plugin (0.8.3) and that you have set up the OAuth stuff correctly on the Google developers console. Even without the OAuth well set-up you should at least see a request to select the user on the screen. Remid that, if the app was already authorised in the past, nothing will be shown.

Also it would help to know what version of Android you are running it on.

**Comment by koenoe** [comment]
@dariosalvi78 I've updated my post with the Android information, but maybe that was after you replied. I'm using a Samsung Galaxy S5 with Android version 6.0.1 and Google Play Services 10.0.84.

I don't see how chrome inspect will solve this problem, but thanks.

I'm using 0.8.3 and as far as I can see I've setup the oAuth stuff correctly. How can I verify this? Push notifications for example are working perfectly.

**Comment by dariosalvi78** [comment]
maybe because it's navigator.X not window.navigator.X ?

and, YES, chrome inspect would have highlighted you the mistake

**Comment by koenoe** [comment]
How would chrome inspect show me something that logcat won't show me?
I'll try the navigator without window. Thanks.

**Comment by dariosalvi78** [comment]
because it's a complete HTML / CSS / JS development and debuggin environment.

Try it, you don't know what you're missing :)
