### ISSUE TITLE
Ionic2 Support

### ISSUE THREAD

**Issue by alx-andru** [dariosalvi78/cordova-plugin-health#39]
Hey there!

Is there any update on supporting Ionic2 and creating an IonicNative wrapper?

**Comment by dariosalvi78** [comment]
Not my interest, but you're more than welcome to develop one.

**Comment by alx-andru** [comment]
Hey @dariosalvi78 thanks for the prompt response. I'd actually like to have a look at it! Keep you updated as I go.

**Comment by dariosalvi78** [comment]
Thanks, surely appreciated.
Meanwhile I will close this issue, as it is not strictly related to this project.
Keep me updated!

**Comment by alx-andru** [comment]
Hey @dariosalvi78 Just opened a pull request at ionic-native. As far as my testing went it worked well. 
https://github.com/driftyco/ionic-native/pull/1039

**Comment by dariosalviwork** [comment]
well done! thanks very much for it.

**Comment by alx-andru** [comment]
You're welcome, hope there are not too many issues with it, but I'd be happy to look into things as they come up. I'm just now starting to use it with ionic2 myself.
