### ISSUE TITLE
datatype Activity: Calories not included in returned object (Android)

### ISSUE THREAD

**Issue by FPeters84** [dariosalvi78/cordova-plugin-health#41]
Hi,

First of all: thanks for you awesome plugin.

Currently I notice (with version 0.8.3 of the plugin) that the returned object for Activity Datatype, does not include calories. 
Not 100% sure, but I think it should be returned in this case?

If I do this query:

navigator.health.queryAggregated({
startDate: new Date(year, month, day, 0, 0, 0).getTime() - 4 * 24 * 60 * 60 * 1000,
endDate: new Date(year, month, day, 23, 59, 59).getTime() - 4 * 24 * 60 * 60 * 1000, 
dataType: 'activity',
}, function (msg) {
var str4 = JSON.stringify(msg);
console.log('day4 object is' + str4);
 }, function (e) {
console.log(e);
});

The returned object is (which I log in the console as a string for test purpose):

{
\"startDate\":\"2017-02-06T23:00:00.000Z\",
\"endDate\":\"2017-02-07T22:59:59.000Z\",
\"value\":{\"still\":{\"duration\":70888730},
\"in_vehicle\":{\"duration\":6331334},
\"walking\":{\"duration\":5074437},
\"swimming.pool\":{\"duration\":1800000},
\"running\":{\"duration\":194074}},
\"unit\":\"activitySummary\"
}

If I look up this data in Google Fit, the calories for all these activities are available.

Kind regards, and thanks in advance
Frank

**Comment by dariosalvi78** [comment]
the plugin does not return calories fora ctivities in Google Fit. It does it in HealthKit though, as said explicitly in the documentation. The reason why it doesn't is that the query would need to be different than the one there is now.
I am not planning to change it at the moment, but you are very welcome to propose a pull request.

Meanwhile, to get the calories, you will need to get all instances of the activities and query for calories separately using the same time windows as the ones specified in the activities.

I will keep this issue opened until either a solution is found or a decision is taken to not implement it.

**Comment by dariosalvi78** [comment]
as a side note: I think that by just adding an aggregate by [AGGREGATE_CALORIES_EXPENDED](https://developers.google.com/android/reference/com/google/android/gms/fitness/data/DataType.html#AGGREGATE_CALORIES_EXPENDED) to the current may work. I need to try it though.

**Comment by dariosalviwork** [comment]
OK I've checked and I could bucket by activity type and ask for calories, but I cannot bucket also by time, which is needed when querying with buckets.
The solution would be running different queries, bucketed per activity type, each query with a different time window corresponding to each time bucket, which would need to be computed manually.

When no time-based buckets are specified, I should be able to bucket by activity type, which might work in your case. Let me try that.

**Comment by dariosalviwork** [comment]
OK now you can get calories when querying for aggregated activity. Please bear in mind that this only works if you don't specify a bucket.

**Comment by FPeters84** [comment]
Thank you so much for this adjustment, it is very much appreciated!

**Comment by FPeters84** [comment]
Hi @dariosalvi78,

Sorry to bother you again with this, but I still don't seem to receive calories when doing this query? 
If have no bucket specified also. 
In fact I am doing the same query as mentioned above, but maybe I am doing something wrong?

I am using the latest version of your plugin (0.8.3) for this.

Thanks so much for your feedback!

Kind regards
Frank

**Comment by dariosalviwork** [comment]
I haven't released a new version yet. You'll need to use the latest version on github for the moment:

`cordova plugin add https://github.com/dariosalvi78/cordova-plugin-health`

**Comment by FPeters84** [comment]
@dariosalvi78 
Aha, so if I understand correctly in the future you will release a new version and than this query will return calories? :)

**Comment by dariosalviwork** [comment]
I usually try to put together few changes in each release, but if I haven't much more to work on for the moment I'll make a new release with just this change probably...

**Comment by FPeters84** [comment]
You sir, are awesome :)

**Comment by dariosalvi78** [comment]
Ahah thanks!

**Comment by dariosalviwork** [comment]
I am afraid I had to remove this feature as it was introducing a problem on the duration (see issue #47 ).

I have an idea of how to fix it, but it will need to execute more than query.

**Comment by FPeters84** [comment]
Hi Dariosalvi,

First of all, I am able to make a really cool physical activity app for Android, and this is all thanks to your plugin. So just want to express my gratitude again for all the work you did for this awesome plugin to be available for the community. Really nice :)

I would like to some kind of a 'stacked line chart' in my graph which shows calories burned, with sublayers for each activity type. However this would be dependent on this enhancement.

Since my coding skill are only quite novice, I am not able to try this enhancement myself. 
So just to know for myself: is it still on your planning to re-introduce this feature?  I of course completely understand if this is not possible. Just for myself to have an idea, otherwise I will try to work out a different graph for my app :)

Kind regards and all the best
Frank

**Comment by dariosalvi78** [comment]
Hello Frank,

the change needed in the code is doable, but requires maybe a day of work for developing and testing it.
It is my intention to introduce this change, and I'll put it on top of my TODO list, but I don't know exactly when I'm going to work on it.
I'll keep you updated.

**Comment by FPeters84** [comment]
@dariosalvi78 

Wow really cool :) thanks in advance for all your efforts!

**Comment by FPeters84** [comment]
@dariosalvi78 

Just for me to know, is this still on your list?
Of course I understand if you are busy. In which case I will do some manual query per hour in my application to get the hourly calories.

Sorry for asking again.
Whether you do it or not, I still extreemly like your plugin ;)

Kind regards,
Michiel

**Comment by dariosalviwork** [comment]
@petemcwilliams seems to have solved it. Thanks Pete!

I'll close it now.
