### ISSUE TITLE
Logging weight twice in one day in health kit returns the values added together when queried on iOS

### ISSUE THREAD

**Issue by anthonyvespoli** [dariosalvi78/cordova-plugin-health#42]
If I manually log my weight in the morning at 182lbs, then later I log my weight at 183lbs, the plugin is returning a single value of 385lbs when I query for the data through my app

**Comment by dariosalviwork** [comment]
I have tried to reproduce the same in iOS:

if call navigator.health.query(), it gives me 2 data points, as expected

if I call navigator.health.queryAggregated(), it gives an error, as expected

one other thing: weight is stored in kg, not lbs.

Without further details, I will ave to close this issue.

**Comment by anthonyvespoli** [comment]
the issue was actually on my end. Thanks for looking into this
