### ISSUE TITLE
Calories empty in iOS

### ISSUE THREAD

**Issue by kabus202** [dariosalvi78/cordova-plugin-health#43]
Hi, 

I have a problem that the calories stay empty on iOS. I can access my steps

`[{"startDate":"2017-03-09T23:00:00.000Z","endDate":"2017-03-10T23:00:00.000Z","value":3501,"unit":"count"},{"startDate":"2017-03-10T23:00:00.000Z","endDate":"2017-03-11T23:00:00.000Z","value":2719,"unit":"count"},{"startDate":"2017-03-11T23:00:00.000Z","endDate":"2017-03-12T23:00:00.000Z","value":290,"unit":"count"},{"startDate":"2017-03-12T23:00:00.000Z","endDate":"2017-03-13T23:00:00.000Z","value":1031,"unit":"count"},{"startDate":"2017-03-13T23:00:00.000Z","endDate":"2017-03-14T23:00:00.000Z","value":620,"unit":"count"},{"startDate":"2017-03-14T23:00:00.000Z","endDate":"2017-03-15T23:00:00.000Z","value":1092,"unit":"count"},{"startDate":"2017-03-15T23:00:00.000Z","endDate":"2017-03-16T23:00:00.000Z","value":736,"unit":"count"},{"startDate":"2017-03-16T23:00:00.000Z","endDate":"2017-03-17T23:00:00.000Z","value":640.9999999999999,"unit":"count"},{"startDate":"2017-03-17T23:00:00.000Z","endDate":"2017-03-18T23:00:00.000Z","value":2118,"unit":"count"},{"startDate":"2017-03-18T23:00:00.000Z","endDate":"2017-03-19T23:00:00.000Z","value":43,"unit":"count"},{"startDate":"2017-03-19T23:00:00.000Z","endDate":"2017-03-20T23:00:00.000Z","value":0,"unit":"count"}]`

But when I look at calories it remains 0. 
`[{"startDate":"2017-03-09T23:00:00.000Z","endDate":"2017-03-10T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-10T23:00:00.000Z","endDate":"2017-03-11T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-11T23:00:00.000Z","endDate":"2017-03-12T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-12T23:00:00.000Z","endDate":"2017-03-13T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-13T23:00:00.000Z","endDate":"2017-03-14T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-14T23:00:00.000Z","endDate":"2017-03-15T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-15T23:00:00.000Z","endDate":"2017-03-16T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-16T23:00:00.000Z","endDate":"2017-03-17T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-17T23:00:00.000Z","endDate":"2017-03-18T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-18T23:00:00.000Z","endDate":"2017-03-19T23:00:00.000Z","value":0,"unit":"kcal"},{"startDate":"2017-03-19T23:00:00.000Z","endDate":"2017-03-20T23:00:00.000Z","value":0,"unit":"kcal"}]`

Is this a misconfiguration? 

Kind regards,
Kab

**Comment by dariosalvi78** [comment]
I don't know. Have you written some calories?
Check in the health app first.
