### ISSUE TITLE
how to just ask for 'read' permissions?

### ISSUE THREAD

**Issue by aggarwalankush** [dariosalvi78/cordova-plugin-health#44]
I'm using 'requestAuthorization' to read health data as mentioned in docs. But by default, it asks for read and write permissions. How can I just ask for 'read' permission?

**Comment by dariosalvi78** [comment]
Difference between read and write is not supported at the moment. On the to-do list.
Actually the health kit part is ready, the Google fit bit needs an update.
You're welcome to try to fix it.

**Comment by aggarwalankush** [comment]
@dariosalvi78 Thanks for the quick reply and your contributions. I am looking forward to using and contribute to this repo. 

Can you tell me how to just ask for 'read' permissions in health kit? I can try same in android and raise a PR. I'm focusing on this issue because 'isAuthorized' returns true only if user give both read **and** write permissions.

Also, in docs, you mentioned to always call 'requestAuthorization' before query method. I'm testing in iPhone and it's not helping at all. If I disable health kit permission from settings for my app, 'requestAuthorization' doesn't show popup to ask for health permissions again. Don't you think it's a bug?

**Comment by dariosalvi78** [comment]
> Can you tell me how to just ask for 'read' permissions in health kit?

as for iOS, my plugin wraps [Telerik's](https://github.com/Telerik-Verified-Plugins/HealthKit), so you could use that for asking read-only permissions

>  I can implement same in android and raise a PR soon.

that would be very welcome, it should be quite easy to achieve but requires a little change in the API too

> you mentioned to always call 'requestAuthorization' before query method.

in iOS it doesn't make a big difference, but in Android it does, because the method also initialises the Google APIs

> If I disable health kit permission from settings for my app, 'requestAuthorization' doesn't show popup to ask for health permissions again. Don't you think it's a bug?

It's [how it works in HealthKit](https://developer.apple.com/reference/healthkit/hkhealthstore/1614152-requestauthorization) I'm afraid:

> If the user has already chosen to grant or prohibit access to all of the types specified, the completion is called without prompting the user.

**Comment by aggarwalankush** [comment]
@dariosalvi78 I forked the project and worked on some issues I was facing. **All changes are backward compatible.**

1. Added read or write only permissions in `requestAuthorization` for both iOS and Android.
See datatypes in https://github.com/aggarwalankush/cordova-plugin-health#requestauthorization. It now accepts an object specifying read or write only permissions.

2. https://github.com/dariosalvi78/cordova-plugin-health/issues/35 This issue is closed but the solution isn't working. I standardized it like other plugins and added iOS keys strings as variables. See commit description on how to use it- https://github.com/aggarwalankush/cordova-plugin-health/commit/0f8985eb0aa1c3d885203ecd6cb5e2aa5f62d46c

3. I also added a `.editorconfig` file which I generally like in projects to maintain code formatting.

Full commits here - https://github.com/aggarwalankush/cordova-plugin-health/commits/master 

Let me know if I should raise a PR.

**Comment by dariosalviwork** [comment]
thanks, impressive work!

could you please submit a PR?
I'd love to merge it officially.

**Comment by dariosalviwork** [comment]
coolio,

I've tested it on Android and works like a charm!

**Comment by aggarwalankush** [comment]
@dariosalviwork I am facing one more issue in **Android**. I am using 'isAuthorized' and 'requestAuthorization' method and sometimes getting `GoogleApiClient is not connected yet`. As both methods run in threads, that could be causing the issue. I don't know how to test Cordova plugins so couldn't figure out the cause. Maybe you could fix this issue someday or tell me how to build/test Cordova plugin.

**Comment by dariosalviwork** [comment]
testing the plugin is easy, open the Android project in Android studio by importing it from the "platforms" folder. That's it really.
I wonder how you managed to extend the plugin without testing it!

About your issue:

- be aware that the phone needs to be connected to the Internet, at least when requesting authorization the first time
- the thread shouldn't be a problem as all communication is asynchronous. Actually the use of threads [is recommended by Cordova](https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html)
- be sure you nest your calls and make sure you call, eg, a query() only AFTER your requestAuthorization() has called the successCallback

**Comment by aggarwalankush** [comment]
I have an ionic app, I tested using plugin in that app. I was wondering if there was an easy way. I'll see if I can figure out the issue sometime this weekend.

**Comment by dariosalvi78** [comment]
the easiest way is to forget Ionic and use[ a starter cordova app](https://cordova.apache.org/docs/en/latest/guide/cli/), then just open the console using chrome://inspect and run all the code from there
