### ISSUE TITLE
navigator.health.query is not returning sourceBundleId in successCallback.

### ISSUE THREAD

**Issue by Rohithastak** [dariosalvi78/cordova-plugin-health#46]
Hello,
We are trying to fetch heart_rate data from healthkit, I am using navigator.health.query but in success callback its returning Start date, end date,value and unit , source name but not sourceBundleId.
We need to recognize the source from which the data is coming.
Please help.

**Comment by dariosalviwork** [comment]
I have tested here and it works.
I insert data from the health app (I don't have any other apps that does it) and, when I query, I get the sourceBundleId too.

**Comment by dariosalviwork** [comment]
I have also tried with an external app and the sourceBundleId is there.

Are you using Android or iOS?

**Comment by Rohithastak** [comment]
I'm using for iOS with following code for heart_rate 

 navigator.health.query({
            startDate: startDate,
            endDate: endDate,
            dataType: 'heart_rate'
        }, successCallback, errorCallback)

in success callback its returning array

{startDate,  endDate, value, unit, source}

**Comment by dariosalvi78** [comment]
Check that you are using the latest version of the plugin. Rather than that I wouldn't know how to help without further details.

**Comment by dariosalviwork** [comment]
As I haven't received any update on this, I will close the issue. Feel free to re-open it if you have more insights.

**Comment by ken1106** [comment]
I got null value both sourceName and  sourceBundleId on Android, if steps's data coming from the mobile.
But I found the following description from the google API, so sourceBundleId is null is right.
Data coming from **local sensors** or BLE devices will not have a corresponding application.
[Google API](https://developers.google.com/android/reference/com/google/android/gms/fitness/data/DataSource#getAppPackageName())
