### ISSUE TITLE
Duration data in returned object incorrect on Android?

### ISSUE THREAD

**Issue by FPeters84** [dariosalvi78/cordova-plugin-health#47]
Dear @dariosalvi78 ,

First of all: thanks for you awesome plugin. It really is very awesome :)

However I am wondering if the duration information in the returned object for Android is correct?
An example of an object returned if I query for 'Activity' with navigator.health.queryAggregated

{"startDate":"2017-04-22T22:00:00.000Z","endDate":"2017-04-23T21:59:59.000Z","value":{
"still":{"duration":86399000,"calories":1068.8572998046875},
"in_vehicle":{"duration":81471533,"calories":341.9926452636719},
"walking":{"duration":44405366,"calories":762.522216796875},
"running":{"duration":5969930,"calories":1568.8883056640625},
"unknown":{"duration":1936558,"calories":0}
},"unit":"activitySummary"}

If you count everything together, tot total is a bit more than 61 hours, while the timespan is 24 hours.
The "running" information is correct, but for example the "walking" information is wrong.

Thanks for having a look!
Frank

**Comment by FPeters84** [comment]
Forgot to tell: I am using the latest version of the plugin.

I also investigated a bit more, and it seems that the duration for "still" is always the full length of the timeframe. So if the timeframe is 24 hours, the duration of still is always 86399000.
Not sure if this info helps :)

Please feel free to ask if you want me to test a specific query.

Kind regards
Frank

**Comment by dariosalvi78** [comment]
I can't work on it now, but maybe you can try it yourself.
In HealthPlugin.java, can you try to change line 951 to the same as 949?

In other words:
`builder.aggregate(DataType.TYPE_ACTIVITY_SEGMENT, DataType.AGGREGATE_ACTIVITY_SUMMARY);`
instead of 
`builder.aggregate(DataType.TYPE_CALORIES_EXPENDED, DataType.AGGREGATE_CALORIES_EXPENDED);`

let me know if that works...

**Comment by FPeters84** [comment]
@dariosalvi78 

Unfortunately I only know how to build my app in the cloud, so I don't see a way how to edit this line without building it locally. Sorry for that :) 
I will wait until you find time to try this. Thanks in advance!

**Comment by dariosalviwork** [comment]
Hi,
so I have run some tests myself and, basically, the type of query does not change the results.
Here's what I receive if I query over the last 3 days:

![image](https://cloud.githubusercontent.com/assets/10922108/25657106/0cc6e10c-2ff4-11e7-8037-8c363bb9e89e.png)

Remind that the total sum of hours should be 72.
What's puzzling me is that it gives 3 days of walking and almost 24 hours of biking.
I try to keep myself active, but that's far too much :)

I need to dig into it better. Thanks for raising it.

**Comment by dariosalviwork** [comment]
I've done another test, this time bucketing the data by day,
This is what I get:

![image](https://cloud.githubusercontent.com/assets/10922108/25657803/8fb4d13e-2ff7-11e7-97b3-6751685cec9f.png)

now the time window is not exactly the same as the previous query above, but now durations make much more sense.

I am coming to the conclusion that there's a bug in Google Fit. My suggestion for the moment is to use bucketing, but you won't get calories this way though.

I'll keep this issue open until I manage to understand this better.

**Comment by dariosalviwork** [comment]
I've got it. Basically the  way duration is calculated from the datapoint timestamps is not correct, I need to use the FIELD_DURATION, but that is only available when querying TYPE_ACTIVITY_SEGMENT. So there's no way around it, I will need to remove calories from the activity query.

(well, in reality it would be possible to add calories, but it will need an extra query)
