### ISSUE TITLE
How to revoke Authorization?

### ISSUE THREAD

**Issue by bimal72** [dariosalvi78/cordova-plugin-health#48]
Hello,

Once I do 
```
navigator.health.requestAuthorization(['steps'], successCallback, errorCallback)
```
How to revoke or detach this?

**Comment by dariosalviwork** [comment]
programatically? you can't.

The user can revoke permissions via settings in Google Fit or HealthKit.

**Comment by bimal72** [comment]
@dariosalviwork I think in native Android app, problematically we can...

**Comment by dariosalviwork** [comment]
"problematically" everything can be achieved!  :smile: 

I don't know of any way to revoke permissions from Google Fit, but I will be happy to be surprised...
