### ISSUE TITLE
User cancelled the dialog

### ISSUE THREAD

**Issue by Deharlan** [dariosalvi78/cordova-plugin-health#49]
I am getting this error (**User cancelled the dialog**) when I try the simple code as the example in the Ionic Framework.

```
this.health.isAvailable()
.then((available:boolean) => {
  console.log(available);
  this.health.requestAuthorization([
    'distance', 'nutrition',  //read and write permissions
    {
      read: ['steps'],       //read only permission
      write: ['height', 'weight']  //write only permission
    }
  ])
  .then(res => console.log(res))
  .catch(e => console.log(e));
})
.catch(e => console.log(e));
```

**Comment by dariosalvi78** [comment]
I guess this happens on Android.
If the user cancels does not authorise the app, that's the message that you get..

**Comment by Deharlan** [comment]
@dariosalvi78 Yes, I think it is the reason.
But I do not know how to ask for an authorization,
When I call the requestAuthorization function, it asks the user to log in, and checks the data information and then returns with that "User canceled the dialog" log.

**Comment by dariosalviwork** [comment]
that's where the plugin ends and you app begins :)
Show something to the user before to have him prepared of what's coming next. If he rejects, there's not very much you can do about it.

I'll close this issue then...

**Comment by git-clay** [comment]
I am getting this same issue.  

This happens during the "requestAuthorization" function. Google successfully brings up the login display, a user will select an account or login to a new one.  Instead of successfully logging the user in, the error "User cancelled the dialog" is thrown.

**Comment by dariosalviwork** [comment]
I'll reopen the issue, but it seems to be out of the plugin's control.

**Comment by git-clay** [comment]
In that case, is this a issue with the initial google setup / app authorization?

**Comment by dariosalviwork** [comment]
it is likely that you haven't setup the API credentials correctly in the Google console. If you fix it, please tell me and I'll close the issue.

**Comment by git-clay** [comment]
Does the authorization flow need to utilize "in app browser"? Therefore needing the google console 2.0 authorization to be set up for a web application or is this plugin built to utilize the android 2.0 authentication?

**Comment by dariosalviwork** [comment]
The authorisation flow is managed by the plugin [following the official guidelines](https://developers.google.com/fit/android/get-api-key), the browser has nothing to do with it.
Make sure that you have correctly setup the key in the Google API console.

**Comment by git-clay** [comment]
this isnt an issue with the plugin so no need to keep it open. Thanks for your help, I will keep working with the google console
