### ISSUE TITLE
Support new Google Fit health data types (blood glucose, etc)

### ISSUE THREAD

**Issue by sgilroy** [dariosalvi78/cordova-plugin-health#50]
It looks like Google Fit has added support for blood pressure, blood glucose, and some other health data types. It would be great to have support for reading and writing these data types via cordova-plugin-health, and updated documentation to go with it.

References:
https://developers.google.com/android/reference/com/google/android/gms/fitness/data/HealthDataTypes.html#TYPE_BLOOD_GLUCOSE
https://developers.google.com/fit/scenarios/write-blood-glucose-data
https://developers.google.com/fit/scenarios/write-bp-data

I have not seen an explicit announcement for the change, but the above pages say "Last updated February 15, 2017".

These new metrics fall into the category of "restricted data types".

> Note: Because health data is potentially sensitive, Google Fit restricts write access for the data types in HealthDataTypes to only certain developers.﻿

**Comment by dariosalvi78** [comment]
Thanks for letting me know. It was under the radar and it's definitely good news. Consider it in the roadmap.

**Comment by dariosalviwork** [comment]
**Warning** I am going to break the interface, blood glucose is now an object like this:

`{ glucose: 5.5, meal: 'breakfast', sleep: 'fully_awake', source: 'capillary_blood' }`

In Android it is already an object (see commit), I will need to change the iOS code too to reflect this decision.
