### ISSUE TITLE
"GoogleApiClient is not connected yet." Android race condition

### ISSUE THREAD

**Issue by JulianLaval** [dariosalvi78/cordova-plugin-health#54]
Querying Google Fit shortly after requesting authorisation sometimes yields the following:

```
nutrition error: "Cannot connect to Google Fit"
activity error: "Cannot connect to Google Fit"
GoogleApiClient is not connected yet.
nutrition.fat.total error: "Cannot connect to Google Fit"
nutrition.calories error: "Cannot connect to Google Fit"
nutrition.fat.saturated error: "Cannot connect to Google Fit"
nutrition.fat.polyunsaturated error: "Cannot connect to Google Fit"
nutrition.fat.monounsaturated error: "Cannot connect to Google Fit"
nutrition.sodium error: "Cannot connect to Google Fit"
nutrition.cholesterol error: "Cannot connect to Google Fit"
nutrition.carbs.total error: "Cannot connect to Google Fit"
nutrition.potassium error: "Cannot connect to Google Fit"
nutrition.dietary_fiber error: "Cannot connect to Google Fit"
nutrition.sugar error: "Cannot connect to Google Fit"
nutrition.vitamin_a error: "Cannot connect to Google Fit"
nutrition.calcium error: "Cannot connect to Google Fit"
nutrition.vitamin_c error: "Cannot connect to Google Fit"
nutrition.protein error: "Cannot connect to Google Fit"
nutrition.iron error: "Cannot connect to Google Fit"
```

This seems to only occur on first install / reinstall / hard reload. I suspect the root cause may be a race condition where Google Fit isn't yet ready but the authentication callback has successfully returned.

Any ideas on how this can avoided?

Details:
Galaxy S7 emulated in Genymotion
Android 7.1.0
API 25
Latest Play services (10.2.6)

**Comment by dariosalvi78** [comment]
The Google Fit plugin follows the guide given by Google itself. In principle, the callback should be called once a connection to the Fit APIs is 100% guaranteed. If that's not the case, there's not very much I can think of I'm afraid.

It's interesting that you have found that this happens only the first time after the app is installed. Maybe there's a delay in the communication with the Google servers, or maybe your network connection is not very reliable? In both cases, this behaviour shouldn't happen anyway.

I will leave this issue opened until we find something more about it.

**Comment by JulianLaval** [comment]
Weird indeed! Am looking into this on my end, so will update with any findings!

**Comment by JulianLaval** [comment]
After digging a bit deeper, it turned out that in some rare situations I wasn't actually requesting authorisation before querying Google Fit. Wrapping these queries in the `requestAuthorization` callback seems to have fixed it! Closing!
