### ISSUE TITLE
Incorrect activity durations from Google Fit

### ISSUE THREAD

**Issue by JulianLaval** [dariosalvi78/cordova-plugin-health#56]
Weird bug (feature?) with Google Fit - returned activities have the wrong start time if the query startDate param is between said activities' start and end time. Steps to reproduce:
- Create an activity starting at 9am and ending at 10am via Google Fit.
- Query activity with startDate = 9.30am and endDate = any time after 10am
- startDate for the returned activity will be 9.30am rather than 9am.

This differs with HealthKit behaviour, which is to not return this event if the query startDate is between an activity's start and end time.

First of all, can you reproduce? Second, is this expected behaviour?

**Comment by dariosalvi78** [comment]
I think it's just the way it works but I need to test it myself.

One observation: when querying "activity" in iOS, it gets the workouts explicitly input by users (or other apps). This is OK but a bit limited. In Fit, the app is able to determine users' activities automatically.

The Core Motion API includes also an activity detection similar to Google Fit, see [this](https://developer.apple.com/reference/coremotion/cmmotionactivitymanager). It would be awesome if someone could add this to the iOS plugin.

**Comment by JulianLaval** [comment]
Since returned events don't include a unique ID, my current setup relies on checking if an event exists at the start date specified to detect / avoid importing duplicates. This Google Fit behaviour essentially breaks this, as querying activity on interval yields a different start time each time (e.g. 9.31am, 9.32am, ...) which is then recognised as a separate event.

Would be good to know if this is expected behaviour, as I'm unable to find any resources on the topic.

As a temporary solution, I'm changing this to compare against the end date, although unique IDs would be much nicer :)

Agreed on CoreMotion - I see it's on the roadmap already, so although it isn't a priority I might be able to take a crack at it at some point!

**Comment by dariosalvi78** [comment]
Google Fit gives you back whatever is included in a certain time window. So I would expect to give you an activity even if your start date is in the middle of the activity.
You are right, there are no IDs, but you can keep track of the time windows you queried in the past so that you can avoid overlaps. In other words: your start/end dates would become your ID.

I'll keep this opened until I can confirm this behavior, but feel free to close it if you think there's no need.

About the Core Motion API, it would be a really nice plus.

**Comment by JulianLaval** [comment]
I don't know, I still feel that events queried shouldn't be truncated in any circumstance. It should either be all or nothing - if querying an interval of say 9-10am, and you have an event from 8am to 9.05am, it would be wrong to assume that the event only lasted 5min (Google Fit would return the event as 9am-9.05am).

I appreciate there may be some use cases for this behaviour, although it doesn't work for our needs (i.e. having a timeline/logbook of events).

Since I've found an acceptable workaround (i.e. skipping events for which the start time is exactly the query start time), I'm happy to close the issue for the time being.

It might however be worth mentioning in the README as an Android quirk, though? Especially since the behaviour differs from that of Healthkit. Happy to submit a PR.

**Comment by dariosalviwork** [comment]
To me it makes a lot of sense. If I am walking from 9:00 to 11:00 and I query: give me the activity from 10:00 to 12:00 I was indeed walking from 10:00 to 11:00 !

I'll be happy to merge a PR if you want to add a note in the Readme.

Closing this now.
