### ISSUE TITLE
Revoke Authorization once authorized

### ISSUE THREAD

**Issue by bimal72** [dariosalvi78/cordova-plugin-health#57]
Hello,
Is there any way to revoke Authorization, once it is authorized by using 
requestAuthorization()?

**Comment by bimal72** [comment]
Sorry, but in native disconnecting from google fit is possible

https://developers.google.com/fit/android/disconnect

**Comment by dariosalvi78** [comment]
well spotted, thanks.

I am not interested in supporting this use case at the moment, but I will be very happy to merge a Pull Request if you want to try it.
