### ISSUE TITLE
Potential device support error when including cordova-plugin-health to an existing iOS app

### ISSUE THREAD

**Issue by JulianLaval** [dariosalvi78/cordova-plugin-health#59]
Per https://developer.apple.com/library/content/qa/qa1623/_index.html:
> iTunes Connect does not allow uploading an updated version of an app when the update runs on fewer devices than the version of the app currently in the App Store. This is by design.

As it stands, the project's `plugin.xml` includes `healthkit` as a required capability (see UIRequiredDeviceCapabilities info [here](https://developer.apple.com/library/content/qa/qa1397/_index.html)). This is problematic for a number of reasons:

- Adding cordova-plugin-health to an app that has previously been added to the App Store is impossible, as this new key removes support for a number of devices that were previously supported (e.g. iPads), triggering the error mentioned above
- Unless I'm mistaken, new apps that include this key will inherently be unavailable for devices that don't support Apple Health

Having removed this key from my fork, I can confirm that the plugin still works correctly and updates can once again be uploaded to the App Store. Although I haven't yet been able to test the app on a device that doesn't support Apple Health, I would assume that the isAvailable method respond correctly to this scenario.

Bearing all of this in mind, maybe it would be a good idea to remove this requirement altogether, or at least make it optional?

**Comment by dariosalvi78** [comment]
According to my experience, if you don't have the HealthKit capability, the plugin just doesn't work. i would recommend to test it thoroughly.

BTW: why should someone be interested in using this plugin on iPads ?

**Comment by JulianLaval** [comment]
So in our case, the plugin is essentially an extra feature for an app that otherwise works on all devices. If the device supports Apple Health, then great, you can import data, and if not, no worries, the app still works without.

My understanding was that the isAvailable method would achieve this purpose, i.e. return `true` on iOS8+ iPhones and `false` on iPads, <iOS7... Unfortunately, I don't have access to any iOS devices that don't support Health (e.g. an iPad), so haven't been able to test this.

Are you saying that the app will crash on these devices rather than gracefully return `false` on isAvailable?

To be clear, I'm not talking about the HealthKit entitlement itself, merely the Info.plist key that states that the app can only be downloaded on devices that support HealthKit.

**Comment by dariosalvi78** [comment]
OK, I was talking about the entitlement.

If removing that information from the Info.plist doesn't affect anything, then I'm with removing it.

**Comment by dariosalvi78** [comment]
I am looking at the Telerik's plugin and [it seems that they removed that bit too for the same reason](https://github.com/Telerik-Verified-Plugins/HealthKit/blob/master/plugin.xml).

I think it's OK to remove it then. I am happy to merge a PR.

**Comment by JulianLaval** [comment]
Ah, brilliant! I admittedly should have checked the Telerik plugin beforehand, but am glad they reached the same conclusion! Will submit a PR.
