### ISSUE TITLE
add healthkit entitlements in plugin.xml

### ISSUE THREAD

**Issue by dariosalvi78** [dariosalvi78/cordova-plugin-health#60]
add these two to plugin.xml as done in [Telerik's plugin](https://github.com/Telerik-Verified-Plugins/HealthKit/blob/master/plugin.xml):

```
    <config-file target="*/Entitlements-Debug.plist" parent="com.apple.developer.healthkit">
      <true/>
    </config-file>

    <config-file target="*/Entitlements-Release.plist" parent="com.apple.developer.healthkit">
      <true/>
    </config-file>
```

**Comment by JulianLaval** [comment]
Out of curiosity, what does this achieve? Would it remove the need to include HealthKit as an application service when provisioning the certificate?

**Comment by dariosalvi78** [comment]
I have no idea :smile: 
If you compile your app in XCode, as now you need to manually set the entitlement in the project configuration. I guess that this would set the entitlement automatically.

**Comment by JulianLaval** [comment]
This is the Telerik merge that explains it: https://github.com/Telerik-Verified-Plugins/HealthKit/pull/83

Apple Documentation on entitlements here: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html

Seems that you can essentially enable app services / entitlements manually via the developer console or on a  dynamic basis via XCode. TIL 🙂
