### ISSUE TITLE
GoogleApiClient is not connected yet.

### ISSUE THREAD

**Issue by jaassoon** [dariosalvi78/cordova-plugin-health#64]
It sometimes raise the message as title said, but not always. It seems that the onConnected() method will still be called in spite of current state is "isConnecting"
logcat log:
`W/GmsClientEvents(20908): unregisterConnectionCallbacks(): listener org.apache.cordova.health.HealthPlugin$4@1a2e9b7 not found`
`I/cordova-plugin-health(20908): Google Fit connected`
`I/cordova-plugin-health(20908): enter_function_authReqSuccess`
`I/cordova-plugin-health(20908): after_request`
`I/cordova-plugin-health(23675): isConnected=false`
`I/cordova-plugin-health(23675): isConnecting= true`
`I/cordova-plugin-health(20908): authReqSuccess_error3= GoogleApiClient is not connected yet.`

Details:
cordova-plugin-health@0.6.2
Nexus 7 
Android 5.1.1
API 25
compile "com.google.android.gms:play-services-fitness:9.4.0"
compile "com.google.android.gms:play-services-gcm:9.0.2+"

src code:
`private void authReqSuccess(){
        //Create custom data types
        new Thread(new Runnable(){

            @Override
            public void run() {
                try{
                    Log.i(TAG, "enter_function_authReqSuccess");
                    String packageName = cordova.getActivity().getApplicationContext().getPackageName();
                    DataTypeCreateRequest request = new DataTypeCreateRequest.Builder()
                            .setName(packageName+".gender")
                            .addField("gender",Field.FORMAT_STRING)
                            .build();
                    Log.i(TAG, "after_request");
                    Log.i(TAG, "isConnected="+mClient.isConnected());
                    Log.i(TAG, "isConnecting= "+mClient.isConnecting());
                    PendingResult<DataTypeResult> pendingResult =  Fitness.ConfigApi.createCustomDataType(mClient, request);
                    ...
                    authReqCallbackCtx.success();
                } catch (Exception ex){
                    Log.i(TAG, "authReqSuccess_error3= "+ex.getMessage());
                    authReqCallbackCtx.error(ex.getMessage());
                }
            }
        }).start();
    }`

**Comment by dariosalviwork** [comment]
please share the javascript code you are using, make sure you are using the callback correctly.
If the problem persists, I'm afraid there's little we can do about it.

**Comment by jaassoon** [comment]
something like this as below:
```
xxx.fitAuth(
          function(){
            var startDate,dataType,endDate;
            dataType='steps';//default
            startDate= queryDate;
            endDate= $common.dateAdd(new Date(),'day',-1);
            startDate.setHours(0,0,0,0);
            endDate.setHours(23,59,59,0);
            navigator.health.query({
                startDate: startDate,
                endDate: endDate,
                dataType: dataType,
                limit:100000,
                },$resume.stepSuccess,$resume.stepFail
            )
          });
```

where fitAuth is:
```
fitAuth:function(success,fail){
        if(fail!=undefined){
            navigator.health.requestAuthorization(['steps'],success,fail);
            return
        }
        navigator.health.requestAuthorization(['steps'],success,fitAuthFail);
    },
```

**Comment by skyserpent** [comment]
👍

**Comment by dariosalvi78** [comment]
are you still encountering this issue?

**Comment by dariosalviwork** [comment]
this is most likely the same as #100 
I'll close it.
