### ISSUE TITLE
navigator.health.query is not working for some users on iOS

### ISSUE THREAD

**Issue by Rohithastak** [dariosalvi78/cordova-plugin-health#66]
Hello,

I am using this plugin for iOS, its returning correct result for some users and for some users "navigator.health.query" is returning nothing. Neither its going in success callback and nor in error callback. I've also used Try catch block but its not returning anything please help!

try{
alert("inside getHealthData try block");

	navigator.health.query({ 
	    startDate: startDate,  
	    endDate: endDate,  
	    dataType: 'steps'
	    }, 
	    function (data) {  
		 	var stepsCount =JSON.stringify(data);
		       alert("Step data: "+stepsCount.length); 
	    } ,
            function (e) {   
           alert("Date Error :"+JSON.stringify(e)); 
		}

	); 

}catch(ex){
  alert("inside catch block for getHealthData "+ex);
}

It parse well till alert in try but after that nothing happens. 

Thanks

**Comment by dariosalviwork** [comment]
it's really hard to say, the plugin is quite stable in iOS.
Without further details I can't do very much about this issue.

**Comment by Rohithastak** [comment]
Hello,

What actually I m trying to do is asking the user first to give permission  to access his/her step data then fetch his/her step data using 

navigator.health.query({ 
	    startDate: startDate,  
	    endDate: endDate,  
	    dataType: 'steps'
	    }, 

there is no issue with start date and end date, the thing annoying for me is neither success or error callback is called.
Please share what more information you want. It's not working for some users only. Is there issue with any iOS device or setting ?

Thanks

**Comment by dariosalvi78** [comment]
have you managed to fix this issue? Can I close it?

**Comment by Rohithastak** [comment]
Yes i fixed this issue you can close this now.
Thanks
