### ISSUE TITLE
GoogleFit steps/sleep results not usable

### ISSUE THREAD

**Issue by blurry-code** [dariosalvi78/cordova-plugin-health#68]
Hi, I'm trying to send following data from my app to GoogleFit: 
- steps
- distance
- calories
- heart rate
- sleep (sleep.deep, sleep.light, sleep.awake)

Looking mainly at steps and sleep both seem to get distorted. The sleep never matches what I actually send in. For instance 8h30m become 7h. While I could live with differences there (within a reasonable range) the errors on the steps are not usable. There it seems to discard any steps before 6am. But even if I subtract the steps in that time from what Google Fit shows it doesn't work. There are differences of up to 100 Steps.

Now I have no idea if this is an error within my code, within this plugin or if GoogleFit just messes with my data. Anybody else have problems like that?
My favored solution was to send total steps instead of incremented values, but this is not supported with the plugin, is it? 

EDIT: On the apple side of things there seem to be similar problems. When I don't have any sleep records the steps are right. Same is true to Google Fit. As soon as sleep comes into play steps (and distance and calories for that matter) are messed up.

**Comment by dariosalvi78** [comment]
this does not reflect the results of my tests, please post the JS code to confirm

**Comment by blurry-code** [comment]
OK, thanks for the reply. I'll keep searching. Posting the JS code would not help much since the main problem seems to be the way I receive the data. Steps, calories and distance may come in every hour or randomly when the value increases. Hourly and random data points do not come in order though. The values are always total values... 

So as you can see there is some overhead needed and this is probably where I made mistakes. Knowing that you have not had these errors helps a great deal already. I would like to keep this open until I find a final solution/explanation for my error.

**Comment by blurry-code** [comment]
I removed the sleep from the data synchronization between my app and Google Fit / Apple Health.

Now Apple Health works as I want it to. The values are the same. However Google Fit does not receive any distance data whatsoever. Steps are different. The timeline shows only one reading by my app (4am) and the rest of the data was generated by the phone itself. 

I guess my questions for now are:
- Why is Google Fit not receiving any distance values
- Does Google Fit prefers the phones' steps-data over my apps'? Why?

Of cause I use the the same code for both iOS and android. So there simply cannot be any problem in my "android javascript code" simply because there is no android-only code.

**Comment by dariosalvi78** [comment]
The Fit app does some undocumented filtering, check that what you've written is there by making your own queries.

**Comment by dariosalvi78** [comment]
arethere any developments on this? can I close this issue?

**Comment by blurry-code** [comment]
Sorry for not getting back here earlier. The issue with data being modified still exists, but as you stated that is probably due to Google Fit's filtering... Sadly that is something users of our app do not appreciate. I have not done any further in-depth research since I've been busy with other things. If anything comes up I will open a new thread. Thanks for keeping this one open that long.
