### ISSUE TITLE
"activity" value is returning empty

### ISSUE THREAD

**Issue by nicclark** [dariosalvi78/cordova-plugin-health#71]
I apologize if I'm overlooking the obvious, but is there a reason why "activity" values would return empty?  I have permission to access the data and there is data for everyday, but my object always returns like this:  "startDate":"2017-07-31T04:00:00.000Z","endDate":"2017-08-01T04:00:00.000Z","value":{},"unit":"activitySummary"}

![microsoftteams-image](https://user-images.githubusercontent.com/8549128/28943212-ec3c5dfc-786b-11e7-9834-b6ab494b1bcc.png)

**Comment by dariosalviwork** [comment]
please specify the JS used for the query.
Be aware that the activity in iOS is equivalent to workouts.

**Comment by nicclark** [comment]
Thanks for the quick response!  Here is my code...
	navigator.health.queryAggregated({
		startDate: new Date(new Date().getTime() - 1 * 24 * 60 * 60 * 1000),
		endDate: new Date(new Date().getTime() - 1 * 24 * 60 * 60 * 1000),
		dataType: 'activity',
	}, function (data) {
		var activityReturn = JSON.stringify(data);
		alert('Activity: ' + activityReturn);
	}, function (error) {
		alert(error);
	});

**Comment by dariosalvi78** [comment]
OK then it's not a bug, the plugin is just telling you that there are no activities (workouts).
Try storing a workout and you'll see that it will return something back.
