### ISSUE TITLE
steps coming from google fit is not coming properly in cordova health plugin

### ISSUE THREAD

**Issue by blackwill123** [dariosalvi78/cordova-plugin-health#72]
I have used aggregate step function which is used to get data from a particular range ie from 20 october 2016 to 7th august 2017. The problem is i am getting data from 20 oct 2016 to 7th august 2017 but the steps value is zero where as in my google fit is is showing step value. i am getting steps value from 30 july to 8th august 2017. i really dont know what exaclty is happening

```
`var opts = {
            startDate: _start, 
            endDate: _end,
            dataType: _type,
          };
$window.navigator.health.queryAggregated(opts,function(res){
          console.log(opts);
                  $timeout.cancel(healthTimeout);
                  defer.resolve(res);
        }, function(error){
                  $timeout.cancel(healthTimeout);
                  $log.error('pluginError:'+pluginName, error);
                  defer.reject(error);
        });`
```

**Comment by dariosalvi78** [comment]
steps in the Fit app and on the Fit DB don't always match 100%. Do a non aggregate query to see what's in there (but keep the period limited or it will explode).

**Comment by blackwill123** [comment]
In my google fit app, most of the date i have steps data eg :- more than 1k steps but when on fetching data it is showing me 0 steps in most months only i am getting steps of last week only

**Comment by dariosalvi78** [comment]
As said, what Fit displays does nto match exactly what's in the database. To check that the plugin is working properly try a non aggregagated query on a certain period (not too long) and see if the sum matches what you get in the aggregated query.

There is also the possibility to query for the "filtered" steps. These should, in principle, match the ones shown by the Fit app.

See docs:

> It is possible to query for "raw" steps or to select those as filtered by the Google Fit app. In the latter case the query object must contain the field filtered: true.

**Comment by blackwill123** [comment]
How to get the authorization and access token in this plugin.

**Comment by dariosalvi78** [comment]
maybe by [reading the README](https://github.com/dariosalvi78/cordova-plugin-health#android-requirements)?

BTW, this is an unrelated issue, which makes me think that you solved the original question.
Can I close this issue?

**Comment by blackwill123** [comment]
I am getting different ressult in different mobile phones using the same account,in some mobile devices it is showing data from october 2016 while in some mobile device it is showing data from feb 2017and for few it is picking up from may 2017

**Comment by dariosalvi78** [comment]
Google Fit should, in principle, aggregate from all devices used by a single user because, eventually, all the data goes to their servers. It is likely that the single phones, though, are picking different mixes of data.
I believe this is an issue related to your experimental conditions and not to the plugin. Especially the fact that you are using the same account on different phones may affect it.

To confirm, you can use another app like [Fittle](https://play.google.com/store/apps/details?id=me.spire.fitviewer&hl=en) to query Google Fit and see if data matches the results of the plugin.

I'm closing the issue now, feel free to re-open it if you find something new.
