### ISSUE TITLE
monitorSampleType when app is not running

### ISSUE THREAD

**Issue by faldunate** [dariosalvi78/cordova-plugin-health#74]
Hello guys,

I'm using healthkit to obtain some fit data like steps, distance, and calories, I can obtain that information without a problem.

The problem starts when I try to bring that information to my endpoint, monitorSampleType seems to work it when the app is foreground and background, but when the app is not running, this doesn't work. I understand that HKObserverQuery activates my application when the information is updated in healthkit, but this is not happening.

I activated background fetch of capabilities and I edited my schema to check the option of "launch due to a background fetch event".

this is my code:

```
this.health.monitorSampleType({ 
     'sampleType': 'HKQuantityTypeIdentifierStepCount', 
     'unit': 'count' 
}).then((data) => { 
     this.sendActivity(data).subscribe(response => { 
        console.log(response); 
     }); 
});
```

xcode logs:

`
Ionic Native: deviceready event fired after 2037 ms Setting up ObserverQuery Background devliery enabled HKQuantityTypeIdentifierStepCount Executing ObserverQuery HealthKit plugin received a monitorSampleType, passing it to JS.
`

Am I doing something wrong?

**Comment by dariosalviwork** [comment]
sorry but monitorSampleType is not supported in this plugin, you need to ask in [the original Telerik's plugin repo](https://github.com/Telerik-Verified-Plugins/HealthKit)
