### ISSUE TITLE
Healthkit Sleep Analysis "Awake" value

### ISSUE THREAD

**Issue by mpedersen15** [dariosalvi78/cordova-plugin-health#75]
Hi there,

First, thank you for the great plugin. I'm looking to integrate with Apple HealthKit mainly for Sleep Analysis and it looks like this plugin only supports the "inBed" and "asleep" values in the "sleep" activity. So, I was wondering if you were planning on adding the "awake" value as well? I would love to be able to distinguish if I'm awake and out of bed vs awake and in bed.

**Comment by dariosalviwork** [comment]
I missed that value somehow. Now it should be fixed but I haven't tested it. Let me know if it works.

**Comment by mpedersen15** [comment]
Works perfectly! Thank you for the quick fix!
