### ISSUE TITLE
Not getting meal and sleep in query response

### ISSUE THREAD

**Issue by marioshtika** [dariosalvi78/cordova-plugin-health#77]
Hello, 
I am using Health App to retrieve the date for blood glucose. I am using the query method as mentioned in your documentation.
But it returns the data without 'meal' and 'sleep'. 

```
[
    {
        "startDate":"2017-10-06T10:55:00.000Z",
        "endDate":"2017-10-06T10:55:00.000Z",
        "value":{
            "glucose":5.550748607260001
        },
        "unit":"mmol/L",
        "sourceName":"Health",
        "source-BundleId":"com.apple.Health"
    }
]

```
I am using a simulator iPhone 8 Plus with iOS 11.0.
Am I doing something wrong?

**Comment by dariosalviwork** [comment]
meal and sleep are only returned if they are written into HK (with the HKMetadataKeyBloodGlucoseMealTime and HKMetadataKeyBloodGlucoseSleepTime metadata).
Also, meal and sleep are only returned by query() not by queryAggregated().

Does this answer your question?

**Comment by marioshtika** [comment]
Hello and thank you for the quick response.

The data I am retrieving are created by Health App itself.

When I tried the [Telerik-Verified-Plugins/HealthKit](https://github.com/Telerik-Verified-Plugins/HealthKit) I could retrieve the meta data like this response.metadata.HKBloodGlucoseMealTime 

I don't understand the difference between [HKBloodGlucoseMealTime](https://developer.apple.com/documentation/healthkit/hkbloodglucosemealtime?language=objc) and [HKMetadataKeyBloodGlucoseMealTime](https://developer.apple.com/documentation/healthkit/hkmetadatakeybloodglucosemealtime)

**Comment by dariosalviwork** [comment]
mmmm, interesting. I can see that HKBloodGlucoseMealTime datatype was introduced very recently (iOS11) so I was not aware of its existence.

I don't understand why it's passed as metadata.HKBloodGlucoseMealTime by Telerik's plugin (and not as HKMetadataKeyBloodGlucoseMealTime), but, anyway, the solution is simple and only involves health.js. I'll see if I can do it on the fly...

**Comment by dariosalviwork** [comment]
should be fixed by the latest commit. Haven't tested it though, let me know if it works.

PS: I have assumed that response.metadata.HKBloodGlucoseMealTime is either 0 or 1, but correct me if I'm wrong

**Comment by marioshtika** [comment]
Thank you @dariosalviwork.
It works perfectly :)

Can I ask you (if its possible) to create a new release with your new changes, because I am installing this plugin through packages.

Thank you in advance. For everything. And keep the good work :)

**Comment by dariosalviwork** [comment]
v 1.0.1 published.
