### ISSUE TITLE
add workout exercises to Android plugin

### ISSUE THREAD

**Issue by ghost** [dariosalvi78/cordova-plugin-health#78]
see documentation [here](https://developers.google.com/android/reference/com/google/android/gms/fitness/data/DataType#TYPE_WORKOUT_EXERCISE) and [here](https://developers.google.com/android/reference/com/google/android/gms/fitness/data/WorkoutExercises).

It could use the same `workout` keyword as in HK although the meaning would not be the same because [workouts in HK](https://developer.apple.com/documentation/healthkit/hkworkoutactivitytype) are more similar to [activity segments](https://developers.google.com/android/reference/com/google/android/gms/fitness/data/DataType.html#TYPE_ACTIVITY_SEGMENT) in Fit. If and when HK will introduce a similar concept, the two datatypes could be made more similar.

**Comment by dariosalviwork** [comment]
after conversations, it may make sense to call it "sport_activity" instead of workout.

**Comment by dariosalvi78** [comment]
am going to close all Google Fit related issues as this is discontinued
