### ISSUE TITLE
Error when querying aggregate active calories for android

### ISSUE THREAD

**Issue by Earthstar** [dariosalvi78/cordova-plugin-health#80]
When you call `queryAggregated` for `calories.active`, you get an error:

```
"Must specify a valid minimum duration for an activity segment: -1636476902"
```

This is because when you fetch the `calories.basal` data, the code doesn't pass through the `bucket` parameter. See: https://github.com/dariosalvi78/cordova-plugin-health/blob/4898a1b07d13a18095d888a5565d2556246533dd/www/android/health.js#L88-92

**Comment by dariosalviwork** [comment]
oops. Wanna try fixing it yourself? I'll be happy to merge a PR !

**Comment by Earthstar** [comment]
Already done!
