### ISSUE TITLE
Improve feedback when Android OAUTH is not set up correctly

### ISSUE THREAD

**Issue by marcovtwout** [dariosalvi78/cordova-plugin-health#83]
When the Android OAUTH client ID is not set up correctly, requestPermission() always returns to the error handler with message `User cancelled the dialog`.

As expained by another user here (https://github.com/dariosalvi78/cordova-plugin-health/issues/49#issuecomment-310928713):

> This happens during the "requestAuthorization" function. Google successfully brings up the login display, a user will select an account or login to a new one. Instead of successfully logging the user in, the error "User cancelled the dialog" is thrown.

The error message is misleading here, is there any way it can be improved?

**Comment by dariosalvi78** [comment]
I'm afraid not. The exception is thrown by the Google APIs and I have no way to check what's the actual reason.

**Comment by marcovtwout** [comment]
Even if the internal fault reason is unavailable, maybe you could add it as a hint text when this message is thrown (for example: `User cancelled the dialog - Are you sure Google API Client OAUTH is set up correctly?`)

Or perhaps listed as a common error in README.md?

**Comment by marcovtwout** [comment]
Thanks!
