### ISSUE TITLE
Wrong value in Calories

### ISSUE THREAD

**Issue by marioshtika** [dariosalvi78/cordova-plugin-health#85]
Hello, I am using Health App to retrieve activities.

In the Health App I have created a record **(Updated)**:

**SAMPLE DETAILS**
```
Workout Type: Running
Duration: 1 Hour
Start Time: Oct 25, 2017 at 2:30:00 PM
End Time: Oct 25, 2017 at 2:44:00 PM
Source: Health
Date Added to Health: Oct 25, 2017 at 2:44:29 PM
Was User Entered: Yes
```
**WORKOUT SAMPLES**
```
Total Active Energy: 125 kcal
Total Walking + Running Distance: 0.5 km
```

And the returned data are:
```
[
    {
        "startDate":"2017-10-25T11:30:00.000Z",
        "endDate":"2017-10-25T11:44:00.000Z",
        "value":"running",
        "unit":"activity-Type"
        "calories": 29,
        "distance": 500,
        "sourceName": "Health",
        "sourceBundleId":"com.apple.Health",
    }
]
```

The calorie value is **29** instead of **125**

Am I doing something wrong?

**Comment by dariosalviwork** [comment]
It is obviosulynot returning your workout: start date and end date are 10 AM (not 10 PM to 11 PM) and the activity is walking not running. Check your query: does the time frame include 10 AM?

**Comment by dariosalviwork** [comment]
from README:

> When querying for activities, only events whose startDate and endDate are both in the query range will be returned.

**Comment by marioshtika** [comment]
I am sorry, it was a copy/paste error :) now the data is correct.
The difference in date/time is the UTC difference. I am ok with that.
My problem is in the calorie value. It does not show me the same value.
Thank you in advance. Again :)

**Comment by dariosalvi78** [comment]
what does the Health app show? it should give you the same value.

**Comment by dariosalvi78** [comment]
I guess your problem is the unit: try googling "125 kj to kcal"

how have you input the data?

**Comment by marioshtika** [comment]
Maybe you are right if I convert 125 kj to kcal it is approximately 29.
But my measure in the Health Application it is in kcal
![screen shot 2017-10-25 at 16 19 47](https://user-images.githubusercontent.com/3079663/32000886-cc57cdd4-b9a0-11e7-8f56-df1048d1fc50.png)

**Comment by dariosalviwork** [comment]
you may have spotted a bug!
can you, please, try to see if fix works?

**Comment by dariosalvi78** [comment]
hey, did the fix work?

**Comment by marioshtika** [comment]
Hello @dariosalvi78, I am sorry for the late response.
I am going to try it tomorrow and I am going to reply to you first thing in the morning.
Thank you in advance.

**Comment by marioshtika** [comment]
Hello @dariosalvi78. The fix worked perfectly. Thank you again.
Can you make a new release so that I can install it through packages?
Thank you in advance.

**Comment by dariosalviwork** [comment]
released.

**Comment by marioshtika** [comment]
Hello @dariosalviwork 

this may be not an issue related with the plugin, but after your last release when i run 

```
cordova plugin add cordova-plugin-health --variable HEALTH_READ_PERMISSION='App needs read access' --variable HEALTH_WRITE_PERMISSION='App needs write access'
```

It still installs the version 1.0.1 not 1.0.2

Am I doing something wrong? 
Thank you in advance.

**Comment by dariosalvi78** [comment]
Sorry, I forgot to publish it on npm.
It should work now...

**Comment by marioshtika** [comment]
Thank you again. And sorry for the too many questions.
I am new at this but in the future, I would like to contribute and help you with this great plugin.

**Comment by dariosalvi78** [comment]
that would be greatly appreciated!
