### ISSUE TITLE
config.xml rewritten by ionic cordova build

### ISSUE THREAD

**Issue by danieldonev** [dariosalvi78/cordova-plugin-health#86]
FIrst, thank you for the amazing plugin. It works awesome in Ionic.

My problem is when I have tried to deploy my app to App store i get the following error.

<img width="750" alt="screen shot 2017-10-28 at 22 52 47" src="https://user-images.githubusercontent.com/8080092/32138426-cec8e104-bc32-11e7-99c8-39a44ff92333.png">

My config.xml

```
  <plugin name="cordova-plugin-health" spec="^1.0.0">
        <variable name="HEALTH_READ_PERMISSION" value="We need you approval to analyse your current health state" />
        <variable name="HEALTH_WRITE_PERMISSION" value="We need you approval to analyse your current health state" />
   </plugin>
```

Can you help men with my problem ?

EDIT 1:

this is my app info.plist file entry

```
<key>NSHealthShareUsageDescription</key>
<string></string>
<key>NSHealthUpdateUsageDescription</key>
<string></string>
```

So why then the information from the config.xml is not propagated to the info.plist file?

**Comment by dariosalvi78** [comment]
Not sure what confide.xml is, the info,plist is obviously empty.
The README clearly says:

> Installation
> 
> In Cordova:
> `cordova plugin add cordova-plugin-health --variable HEALTH_READ_PERMISSION='App needs read access' --variable HEALTH_WRITE_PERMISSION='App needs write access'`
> HEALTH_READ_PERMISSION and HEALTH_WRITE_PERMISSION are shown when the app tries to grant access to data in HealthKit.
This will populate your info.plist automatically. Alternatively, you can specify the strings yourself.

**Comment by danieldonev** [comment]
@dariosalvi78 

I had spelling mistake - it is config.xml

I have installed the plugin in the exactly same way as written in the README file.

But when i run `ionic cordova build ios --prod --release --device` , my entries containing the text (from the config.xml) are replaced with 

```
<plugin name="cordova-plugin-health" spec="^1.0.0">
        <variable name="HEALTH_READ_PERMISSION" value=" " />
        <variable name="HEALTH_WRITE_PERMISSION" value=" " />
</plugin>
```

**Comment by dariosalvi78** [comment]
I don't know really. I usually compile with Xcode directly.

Try adding `--variable HEALTH_READ_PERMISSION='App needs read access' --variable HEALTH_WRITE_PERMISSION='App needs write access'` to the `cordova build` command ?

**Comment by danieldonev** [comment]
Well I guess I can do that, but it would be nice the plugin to work as expected when the command 'ionic cordova build ios --prod --release --device' is executed (not to reset the values and write it to the .plist ).

**Comment by dariosalvi78** [comment]
The config.xml is correctly configured at installation time. It may be a problem introduce by ionic, I have no control over it.

**Comment by danieldonev** [comment]
I have found the problem.

`config.xml` values are overwritten by the ones in the `package.json`.

The proper plugin variable values must be stated in the `package.json`.

**Comment by dariosalvi78** [comment]
you mean the plugin's package.json or your project's package.json?

**Comment by danieldonev** [comment]
@dariosalvi78 I have updated my previous comment.

**Comment by dariosalvi78** [comment]
Thanks, could you please suggest a modification to the README either by posting it here, or by doing a pull request so that people who run into the same issue know what to do?
That would be appreciated....

**Comment by danieldonev** [comment]
@dariosalvi78
I am not sure in which paragraph it should go, but the explanation that I would like to have is: 

"Changing `HEALTH_READ_PERMISSION` or `HEALTH_WRITE_PERMISSION`, after the initial installation can be done **ONLY** in the project's `package.json` file. 

Changes of this values directly in the `config.xml` will be overwritten when `cordova prepare` is called as a part of any command pipeline"

**Comment by dariosalviwork** [comment]
could you post an example of what would need to be inside the package.json ?

**Comment by marcovtwout** [comment]
I ran into the same issue when using the Ionic Package cloud service to build the app. Config.xml is configured correctly, but the values are missing from Info.plist. I will try the solution in https://github.com/dariosalvi78/cordova-plugin-health/issues/86#issuecomment-340455831 and report back here.

**Comment by marcovtwout** [comment]
Yes, that works! When cloud building with Ionic Package, `package.json` needs to be configured like this:

```
{
  "cordova": {
    "plugins": {
     "cordova-plugin-health": {
        "HEALTH_READ_PERMISSION": "App needs read access",
        "HEALTH_WRITE_PERMISSION": "App needs write access"
      },
    },
  }
}
```

Could you add this to the README?

**Comment by pushparajsamant** [comment]
Just FYI if your plugins folder has a fetch.json and it has a usage description, then it is picked up from there when you delete and readd the platform.
