### ISSUE TITLE
Support insulin

### ISSUE THREAD

**Issue by JulianLaval** [dariosalvi78/cordova-plugin-health#89]
Implement the `insulinDelivery` event type [introduced in iOS11](https://developer.apple.com/documentation/healthkit/hkquantitytypeidentifier/2867753-insulindelivery).

As far as I can tell, this isn't yet available in Android, so the feature would be restricted to iOS for the time  being.

Happy to submit a PR!

**Comment by dariosalvi78** [comment]
happy to merge a PR!
