### ISSUE TITLE
Plugin dont exist in Android

### ISSUE THREAD

**Issue by iAdil** [dariosalvi78/cordova-plugin-health#9]
Plugin dont exist in Android  plugins.healthkit
In iPhone everything is good.
Samsung S4 
Android 5.0.1
Google Fit & Play are installed

**Comment by dariosalvi78** [comment]
what do you mean with "dont exist"?
Have you called the isAvailable() function?
It may be that the Google Services are outdated on your phone.

**Comment by iAdil** [comment]
in iOS console.log(plugins.healthkit); return true
in Android console.log(plugins.healthkit); return false

So i even can't call isAvaiable function.

Google Services version 9.4.52

**Comment by dariosalvi78** [comment]
it's `navigator.health` not `plugins.healthkit`, please read the documentation carefully.

**Comment by iAdil** [comment]
Oh sorry, my fault. I just use windows.healthkit becouse cant right call request authorization function in navigator.health.
Please help, is that right syntax for funtion?:
navigator.health.requestAuthorization({
    "readTypes"  : ["HKQuantityTypeIdentifierStepCount"],
}
