### ISSUE TITLE
Issue with storing Blood Glucose

### ISSUE THREAD

**Issue by JulianLaval** [dariosalvi78/cordova-plugin-health#90]
https://github.com/dariosalvi78/cordova-plugin-health/blob/03af089f37a0e24e8ea81cccf7c4bb9a598335ed/www/ios/health.js#L487

When storing a meal time associated with a blood glucose event, `data.metadata.HKBloodGlucoseMealTime` is set to either 0 (`before_meal`) or 1 (`after_meal`).

However, the [HealthKit documentation](https://developer.apple.com/documentation/healthkit/HKBloodGlucoseMealTime) specifies that these enums should be set to 1 ([preprandial](https://developer.apple.com/documentation/healthkit/hkbloodglucosemealtime/2888308-preprandial)) and 2 ([postprandial](https://developer.apple.com/documentation/healthkit/hkbloodglucosemealtime/2888310-postprandial)).

I take it this is a bug? Happy to submit a PR that rectifies it.

**Comment by dariosalvi78** [comment]
yes, thanks for spotting this. Happy to merge the PR.
