### ISSUE TITLE
restructure the code!

### ISSUE THREAD

**Issue by ghost** [dariosalvi78/cordova-plugin-health#97]
the code is quite messy at the moment:

the Android part is all in one big Java class, and would need to be split in smaller bits, the iOS code is basically a wrapper around Telerik's plugin, so it would be just better to have it mapped to this plugin use cases rather than Telerik's.

This issue will stay around for a while I'm afraid, but it's good to keep track of it.

**Comment by dariosalvi78** [comment]
gonna close this, because the new plugin has some restructuring already, tho not as modular as I wanted, but I give up
