### ISSUE TITLE
Wrong unit value in cycling distance from HealthKit

### ISSUE THREAD

**Issue by jmhernandezivitalia** [dariosalvi78/cordova-plugin-health#99]
Hello,
I am using Health App to retrieve activities. I am using the query method as mentioned in your documentation.

navigator.health.query({
  startDate: new Date(new Date().getTime() - 30 * 24 * 60 * 60 * 1000), // last 30 days
  endDate: new Date(), // now
  dataType: 'distance'
}, successCallback, errorCallback)
The data returned a Runtime Error

If I only have bicycle activities I get this error. 

"undefined is not an object (evaluating 'data[i].unit')"

On the other hand, if I have bicycle and running activities, there is no error.

**Comment by dariosalviwork** [comment]
strano !!! (I guess from you name that you speak Italian).

I've never found this issue myself, but I'll need to check. If you find a solution, I'd be happy to accept a pull request.

**Comment by dariosalvi78** [comment]
any update on this issue?

**Comment by dariosalviwork** [comment]
I have tried myself and you are right. I will see if I can solve it.
